# Add the following to your venv/bin/activate
export SECRET_KEY='alongrandomstring'
export DEBUG='True'
export ALLOWED_HOSTS='auctions.mydomain.com'
export DATABASE_ENGINE='django.db.backends.mysql'
export DATABASE_NAME='auctions'
export DATABASE_USER='mysqluser'
export DATABASE_PASSWORD='supersecret'
export DATABASE_HOST='127.0.0.1'
export DATABASE_PORT='3306'
export BASE_URL='http://auctions.mydomain.com'
export EMAIL_USE_TLS='True'
export EMAIL_HOST='smtp.gmail.com'
export EMAIL_PORT='587'
export EMAIL_HOST_USER='mygmailuser@gmail.com'
export EMAIL_HOST_PASSWORD='mygmailpass'
export DEFAULT_FROM_EMAIL="Notifications"
export TIME_ZONE='America/New York'
export SITE_DOMAIN="mydomain.com"