"""
Django settings for fishauctions project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import datetime
import os
import sys
from decimal import Decimal
from pathlib import Path
from urllib.parse import urlsplit

from fishauctions._env import env_has_real_value, parse_bool_env, require_secure_prod_secrets

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

ADMINS = [("Admin", os.environ.get("ADMIN_EMAIL", "admin@example.com"))]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "unsecure")

# SECURITY WARNING: don't run with debug turned on in production!
# Default fail-closed: unset DEBUG => False. Dev environments must opt in
# explicitly with DEBUG=true (see .env.example and docker-compose.yaml).
# This protects against an env-var misconfiguration in production silently
# leaving debug on, which also flips EMAIL_BACKEND, PAYPAL_API_BASE, and
# SQUARE_ENVIRONMENT to non-production paths.
DEBUG = parse_bool_env(os.environ.get("DEBUG"), default=False)

# Fail fast on insecure defaults in production. The validated set is
# intentionally narrow: feature-conditional secrets (PAYPAL_*, SQUARE_*,
# AWS_*, RECAPTCHA_*) fail visibly at use time and forcing them at
# startup would block deploys that don't use those features.
if not DEBUG:
    require_secure_prod_secrets(
        {
            "SECRET_KEY": SECRET_KEY,
            "DATABASE_PASSWORD": os.environ.get("DATABASE_PASSWORD"),
            "REDIS_PASSWORD": os.environ.get("REDIS_PASSWORD"),
        }
    )

# Template string for undefined variables - empty string means silently ignore them
TEMPLATE_STRING_IF_INVALID = ""

ALLOWED_HOSTS = [
    "localhost",
    "web",
    "nginx",  # Allow Selenium tests to connect via nginx service name
    "127.0.0.1",
    "0.0.0.0",
    os.environ.get("SITE_DOMAIN", ""),
    os.environ.get("ALLOWED_HOST_1", ""),
    os.environ.get("ALLOWED_HOST_2", ""),
    os.environ.get("ALLOWED_HOST_3", ""),
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://127.0.0.1",
    "https://" + os.environ.get("SITE_DOMAIN", ""),
    "https://" + os.environ.get("ALLOWED_HOST_1", ""),
    "https://" + os.environ.get("ALLOWED_HOST_2", ""),
    "https://" + os.environ.get("ALLOWED_HOST_3", ""),
]


# Log files go to /home/logs, which docker-compose bind-mounts from the host's
# ./logs directory -- so they survive container recreation (i.e. every deploy) and
# can be grepped on the host without docker exec. (Django previously wrote to
# /home/app/logs, a container-internal path: invisible from the host and wiped on
# every redeploy.) If the mount is unwritable -- a host chown mistake -- fall back
# to a writable dir with a loud stderr warning INSTEAD of letting the file handlers
# raise at logging-setup time: that would crash-loop web AND both celery services
# over log-file ownership, a far worse failure than losing file logs.
def _first_writable_dir(candidates):
    for candidate in candidates:
        try:
            candidate.mkdir(parents=True, exist_ok=True)
        except OSError:
            continue
        if os.access(candidate, os.W_OK):
            return candidate
    return None


_preferred_log_dir = Path("/home/logs")
LOG_DIR = _first_writable_dir([_preferred_log_dir, Path("/home/app/logs"), BASE_DIR / "logs"])
if LOG_DIR is None:
    # Nothing writable at all: keep the preferred path so the handler's own
    # startup error names the directory the operator should fix.
    LOG_DIR = _preferred_log_dir
elif LOG_DIR != _preferred_log_dir:
    sys.stderr.write(
        f"WARNING: {_preferred_log_dir} is not writable; log files will go to {LOG_DIR} instead.\n"
        f"On the host, from the project root, run: sudo chown -R <PUID>:<PGID> ./logs (or rerun ./update.sh)\n"
    )

# web, celery worker, and celery beat share the /home/logs mount, so each service
# writes its own files (root.log vs root-celery.log vs root-beat.log, set via
# LOG_SERVICE_NAME in docker-compose.yaml): RotatingFileHandler is not
# multiprocess-safe, and concurrent writers race on the rollover rename,
# clobbering each other's backups. Within the web service several gunicorn
# workers still share one file -- a pre-existing tradeoff that stays size-bounded
# (each process enforces maxBytes on its own handle); worst case is an
# occasionally garbled line, not unbounded growth.
_log_service = os.environ.get("LOG_SERVICE_NAME", "")
_log_suffix = f"-{_log_service}" if _log_service else ""

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module}.{funcName}:{lineno} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{name} {levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "django_file": {
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / f"django{_log_suffix}.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "root_file": {
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / f"root{_log_suffix}.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "mail_admins": {"level": "ERROR", "class": "django.utils.log.AdminEmailHandler"},
        "null": {
            "class": "logging.NullHandler",
        },
    },
    "root": {
        "handlers": ["console", "root_file"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["django_file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "weasyprint": {
            # 'handlers': ["null"],
            "level": "WARNING",
            "propagate": False,
        },
        "fontTools": {
            # 'handlers': ["null"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
        # Consumer/websocket errors are otherwise invisible (console/file only, which
        # nobody watches). Route ERROR+ to mail_admins so a broken consumer pages us the
        # same way an unhandled 500 does. INFO/WARNING (e.g. WS lifecycle logs) still
        # only go to console/file because mail_admins is level ERROR.
        "auctions.consumers": {
            "handlers": ["console", "root_file", "mail_admins"],
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        # Bidding logic: a swallowed error here means a bid may have failed, so page us.
        "auctions.bidding": {
            "handlers": ["console", "root_file", "mail_admins"],
            "level": os.getenv("LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        # Unhandled exceptions escaping the websocket ASGI app (see asgi.py middleware).
        "auctions.websocket": {
            "handlers": ["console", "root_file", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

if DEBUG:
    # Never email admins in development: strip the mail_admins handler from every logger.
    for _logger_config in LOGGING.get("loggers", {}).values():
        handlers = _logger_config.get("handlers")
        if handlers and "mail_admins" in handlers:
            _logger_config["handlers"] = [h for h in handlers if h != "mail_admins"]

# Channels
CHANNEL_LAYERS = {
    "default": {
        # Use the pub/sub layer, NOT the BRPOP-based RedisChannelLayer.  The BRPOP layer's
        # background receive task blocks on bzpopmin(timeout=brpop_timeout=5s); with redis-py
        # 7.x that blocking read dies at the 5s mark and crashes the consumer with no graceful
        # disconnect, so lot-page sockets dropped/reconnected every ~6s and in-person online
        # bids vanished silently.  Pub/sub uses SUBSCRIBE and has no such blocking loop.
        "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
        "CONFIG": {
            "hosts": [
                (
                    "redis://:"
                    + os.environ.get("REDIS_PASSWORD", "unsecure")
                    + "@"
                    + os.environ.get("REDIS_HOST", "redis")
                    + ":6379/0"
                )
            ],
            # "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Application definition
INSTALLED_APPS = [
    "auctions",
    "dal",
    "dal_select2",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "django_summernote",
    # 'site_settings',
    "crispy_forms",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "django_filters",
    "bootstrap_datepicker_plus",
    "el_pagination",
    "easy_thumbnails",
    "post_office",
    "location_field",
    "channels",
    # 'debug_toolbar', # having this enabled is handy for sql queries but silences errors in channels
    # if enabling debug_toolbar, uncomment the line in MIDDLEWARE below and a line in urls.py
    "markdownfield",
    "qr_code",
    "django_tables2",
    "django_htmx",
    "crispy_bootstrap5",
    "django_recaptcha",
    "chartjs",
    "django_ses",
    "webpush",
    "django_celery_beat",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
]
ASGI_APPLICATION = "fishauctions.asgi.application"
MIDDLEWARE = [
    # "debug_toolbar.middleware.DebugToolbarMiddleware", # see line 170 above
    "django.middleware.security.SecurityMiddleware",
    "auctions.middleware.MobileAppMiddleware",  # Sets request.is_mobile_app from the User-Agent
    "auctions.middleware.CrossOriginIsolationMiddleware",  # Required for WebAssembly/Vosklet
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "fishauctions.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "auctions.context_processors.google_analytics",
                "auctions.context_processors.google_oauth",
                "auctions.context_processors.theme",
                "auctions.context_processors.add_location",
                "auctions.context_processors.dismissed_cookies_tos",
                "auctions.context_processors.site_config",
                "auctions.context_processors.add_tz",
                "auctions.context_processors.user_clubs",
                "auctions.context_processors.label_print_method",
            ],
            "string_if_invalid": TEMPLATE_STRING_IF_INVALID,
        },
    },
]

WSGI_APPLICATION = "fishauctions.wsgi.application"

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.environ.get("TIME_ZONE", "America/New_York")

USE_I18N = False

USE_L10N = False

USE_TZ = True

DATETIME_FORMAT = "M j, Y P e"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SITE_ID = 1
SITE_DOMAIN = os.environ.get("SITE_DOMAIN", "127.0.0.1")
SETUP_COMPLETE = parse_bool_env(os.environ.get("SETUP_COMPLETE") or None, default=False)
# Single club mode is on by default: most self-hosters run one club. The club is
# named after NAVBAR_BRAND, so there's no separate SINGLE_CLUB_NAME to configure.
SINGLE_CLUB_MODE = parse_bool_env(os.environ.get("SINGLE_CLUB_MODE") or None, default=True)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "/home/app/web/staticfiles/"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
]

# for https://pypi.org/project/django-webpush/
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": os.environ.get("VAPID_PUBLIC_KEY", "abcde"),
    "VAPID_PRIVATE_KEY": os.environ.get("VAPID_PRIVATE_KEY", "abc"),
    "VAPID_ADMIN_EMAIL": os.environ.get("ADMIN_EMAIL", "admin@example.com"),
}

# Use MariaDB for both dev and testing
DATABASES = {
    "default": {
        "ENGINE": os.environ.get(
            "DATABASE_ENGINE", "django.db.backends.mysql"
        ),  # mysql_server_has_gone_away does not appear to resolve this issue
        "NAME": os.environ.get("DATABASE_NAME", "auctions"),
        "USER": os.environ.get("DATABASE_USER", "mysqluser"),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD", "unsecure"),
        "HOST": os.environ.get("DATABASE_HOST", "db"),
        "PORT": os.environ.get("DATABASE_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        "CONN_MAX_AGE": 0,  # don't reuse connections for ASGI
        "CONN_HEALTH_CHECKS": True,
        "TEST": {
            "CHARSET": "utf8mb4",
            "COLLATION": "utf8mb4_unicode_ci",
        },
    }
}

# Django's test runner automatically creates a separate test database (test_auctions)
# and cleans it up after tests complete, so no special configuration needed for tests

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
# BASE_URL = os.environ.get('BASE_URL', 'http://127.0.0.1:8000')

ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/login/"
ACCOUNT_FORMS = {
    "signup": "auctions.forms.CustomSignupForm",
    "reset_password": "auctions.forms.CustomResetPasswordForm",
}
ACCOUNT_USERNAME_VALIDATORS = "auctions.validators.USERNAME_VALIDATORS"
# ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_LOGIN_METHODS = {"username", "email"}
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_SIGNUP_FIELDS = ["email*", "first_name*", "last_name*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
ACCOUNT_CHANGE_EMAIL = True

SESSION_COOKIE_AGE = 1209600 * 100

# The mobile WebView handoff relies on the session cookie being server-set with these flags so the
# native app never has to read or reconstruct it. HttpOnly/SameSite=Lax are Django defaults, set
# explicitly here; Secure is enabled whenever we're not in local dev (production is HTTPS-only behind
# nginx — see SECURE_PROXY_SSL_HEADER). Dev runs over plain http on port 80, so Secure would drop the
# cookie there; gating on DEBUG keeps local login working.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "post_office.EmailBackend"

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

POST_OFFICE_EMAIL_BACKEND = os.environ.get("POST_OFFICE_EMAIL_BACKEND", "django_ses.SESBackend")
_site_domain_raw = os.environ.get("SITE_DOMAIN", "127.0.0.1").strip()
_parsed_site_domain = urlsplit(_site_domain_raw if "://" in _site_domain_raw else f"//{_site_domain_raw}")
EMAIL_ROUTING_DOMAIN = (_parsed_site_domain.hostname or _site_domain_raw).strip().lower()
SES_ROUTE_EMAILS_ENABLED = POST_OFFICE_EMAIL_BACKEND == "django_ses.SESBackend" and bool(EMAIL_ROUTING_DOMAIN)
# Firebase Cloud Messaging (mobile push). A path to (or the inline JSON of) a service-account key.
# Absent ⇒ push is disabled globally and every notification falls back to email — the same
# graceful-degradation pattern as SES_ROUTE_EMAILS_ENABLED. See auctions.notifications.push_configured.
FIREBASE_CREDENTIALS_JSON = os.environ.get("FIREBASE_CREDENTIALS_JSON", "").strip()
INBOUND_ROUTING_SECRET = os.environ.get("INBOUND_ROUTING_SECRET", "").strip()
DEFAULT_FROM_EMAIL = (
    f"info@{EMAIL_ROUTING_DOMAIN}"
    if SES_ROUTE_EMAILS_ENABLED
    else os.environ.get("DEFAULT_FROM_EMAIL", "user@example.com")
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

POST_OFFICE = {
    "MAX_RETRIES": 4,
    "RETRY_INTERVAL": datetime.timedelta(minutes=15),  # Schedule to be retried 15 minutes later
    "BACKENDS": {
        "default": POST_OFFICE_EMAIL_BACKEND,
    },
    "CELERY_ENABLED": True,  # Enable Celery for immediate email delivery
}
# django-ses configuration
AWS_SES_AUTO_THROTTLE = 0.5
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
# https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-files.html
# AWS_SESSION_PROFILE = os.environ.get('AWS_SESSION_PROFILE', 'default')
AWS_SES_REGION_NAME = os.environ.get("AWS_SES_REGION_NAME", "us-east-1")
AWS_SES_REGION_ENDPOINT = os.environ.get("AWS_SES_REGION_ENDPOINT", "email.us-east-1.amazonaws.com")
USE_SES_V2 = True
AWS_SES_CONFIGURATION_SET = os.environ.get("AWS_SES_CONFIGURATION_SET", "")
AWS_SES_FROM_EMAIL = DEFAULT_FROM_EMAIL

EMAIL_USE_TLS = parse_bool_env(os.environ.get("EMAIL_USE_TLS") or None, default=True)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = os.environ.get("EMAIL_PORT", 587)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_SUBJECT_PREFIX = ""

RECAPTCHA_PUBLIC_KEY = os.environ.get("RECAPTCHA_PUBLIC_KEY", "")
RECAPTCHA_PRIVATE_KEY = os.environ.get("RECAPTCHA_PRIVATE_KEY", "")
RECAPTCHA_ENABLED = env_has_real_value(RECAPTCHA_PUBLIC_KEY) and env_has_real_value(RECAPTCHA_PRIVATE_KEY)

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
# It sure seems like forms fail silently even with this set to False
# CRISPY_FAIL_SILENTLY = False
# BOOTSTRAP4 = {
#     'include_jquery': True,
# }

MEDIA_URL = "media/"
MEDIA_ROOT = "/home/app/web/mediafiles/"

EL_PAGINATION_PER_PAGE = 20
# SITE_URL = os.environ.get('SITE_URL', BASE_URL)

THUMBNAIL_ALIASES = {
    "": {
        "ad": {"size": (250, 150), "crop": False},
        "lot_list": {"size": (250, 150), "crop": "smart"},
        # 'lot_full': {'size': (600, 600), 'crop': False},
        # Club icon: used inline next to club names.
        "club_icon": {"size": (128, 128), "crop": "smart"},
        "club_icon_small": {"size": (32, 32), "crop": "smart"},
        # Google Wallet logo: 660×660 JPEG as recommended by Google.
        # PNG/WEBP source images are converted; upscaling is avoided (result may
        # be smaller than 660 if the source is small, which is fine).
        # upscale=True ensures the output is exactly 660x660 even when the source
        # is shorter than 660px in one dimension (Google Wallet rejects non-square logos).
        "google_wallet_logo": {"size": (660, 660), "crop": "smart", "upscale": True, "format": "JPEG", "quality": 90},
    },
}
THUMBNAIL_DEFAULT_STORAGE_ALIAS = "default"

# Cloudflare Images (https://developers.cloudflare.com/images/)
# When all three of account id, API token and account hash are set, images that have
# been migrated (see the migrate_to_cloudflare_images management command) are served
# from Cloudflare instead of local files, using named variants that mirror
# THUMBNAIL_ALIASES above (see auctions/cloudflare_images.py).  Documented in .env.example.
CLOUDFLARE_IMAGES_ACCOUNT_ID = os.environ.get("CLOUDFLARE_IMAGES_ACCOUNT_ID", "")
CLOUDFLARE_IMAGES_API_TOKEN = os.environ.get("CLOUDFLARE_IMAGES_API_TOKEN", "")
CLOUDFLARE_IMAGES_ACCOUNT_HASH = os.environ.get("CLOUDFLARE_IMAGES_ACCOUNT_HASH", "")
# Optional: serve from your own (Cloudflare-proxied) domain instead of imagedelivery.net
CLOUDFLARE_IMAGES_DOMAIN = os.environ.get("CLOUDFLARE_IMAGES_DOMAIN", "")
CLOUDFLARE_IMAGES_ENABLED = bool(
    CLOUDFLARE_IMAGES_ACCOUNT_ID and CLOUDFLARE_IMAGES_API_TOKEN and CLOUDFLARE_IMAGES_ACCOUNT_HASH
)

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Trust X-Forwarded-Proto header from nginx proxy for HTTPS detection
# This is required for request.build_absolute_uri() to generate https:// URLs
# when behind a reverse proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
        "FETCH_USERINFO": True,
    }
}
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = True

INTERNAL_IPS = [
    #    '127.0.0.1', # uncomment this to enable the django debug toolbar
]

VIEW_WEIGHT = 1
BID_WEIGHT = 10
WEIGHT_AGAINST_TOP_INTEREST = 20

GOOGLE_MEASUREMENT_ID = os.environ.get("GOOGLE_MEASUREMENT_ID", "")
GOOGLE_TAG_ID = os.environ.get("GOOGLE_TAG_ID", "")
GOOGLE_ADSENSE_ID = os.environ.get("GOOGLE_ADSENSE_ID", "")
# Master on/off switch for all ads (AdSense and internal campaign ads). Default on.
SHOW_ADS = parse_bool_env(os.environ.get("SHOW_ADS") or None, default=True)

GOOGLE_OAUTH_LINK = os.environ.get("GOOGLE_OAUTH_LINK", "")
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

LOCATION_FIELD_PATH = "/static/location_field"
GOOGLE_MAPS_API_KEY = os.environ.get("GOOGLE_MAPS_API_KEY", "")
GOOGLE_MAPS_ENABLED = env_has_real_value(GOOGLE_MAPS_API_KEY)

LOCATION_FIELD = {
    "map.provider": "google",
    "map.zoom": 13,
    "search.provider": "google",
    "search.suffix": "",
    # Google
    "provider.google.api": "//maps.google.com/maps/api/js?sensor=false",
    "provider.google.api_key": GOOGLE_MAPS_API_KEY,
    "provider.google.api_libraries": "",
    "provider.google.map.type": "ROADMAP",
    # misc
    "resources.root_path": LOCATION_FIELD_PATH,
    "resources.media": {
        "js": (LOCATION_FIELD_PATH + "/js/form.js",),
    },
}

GOOGLE_MAPS_SERVER_API_KEY = os.environ.get("GOOGLE_MAPS_SERVER_API_KEY", "")

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# when a user adds an unverified email address to their auction, send an email about the site
SEND_WELCOME_EMAIL = True

DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000

NAVBAR_BRAND = os.environ.get("NAVBAR_BRAND", "auction.fish")
WEBSITE_FOCUS = os.environ.get("WEBSITE_FOCUS", "items")
COPYRIGHT_MESSAGE = os.environ.get(
    "COPYRIGHT_MESSAGE",
    "bottom text",
)
SHOW_FOOTER_ICON = parse_bool_env(os.environ.get("SHOW_FOOTER_ICON") or None, default=True)
I_BRED_THIS_FISH_LABEL = os.environ.get("I_BRED_THIS_FISH_LABEL", "I bred this fish/propagated this plant")
ALLOW_USERS_TO_CREATE_AUCTIONS = parse_bool_env(os.environ.get("ALLOW_USERS_TO_CREATE_AUCTIONS") or None, default=True)
ALLOW_USERS_TO_CREATE_LOTS = parse_bool_env(os.environ.get("ALLOW_USERS_TO_CREATE_LOTS") or None, default=True)
PAYPAL_ENABLED_FOR_USERS = parse_bool_env(os.environ.get("PAYPAL_ENABLED_FOR_USERS") or None, default=False)
SQUARE_ENABLED_FOR_USERS = parse_bool_env(os.environ.get("SQUARE_ENABLED_FOR_USERS") or None, default=False)
USERS_ARE_TRUSTED_BY_DEFAULT = parse_bool_env(os.environ.get("USERS_ARE_TRUSTED_BY_DEFAULT") or None, default=True)
UNTRUSTED_MESSAGE = os.environ.get(
    "UNTRUSTED_MESSAGE", "You cannot currently promote auctions.  Please contact the website administrator for access."
)
ENABLE_PROMO_PAGE = parse_bool_env(os.environ.get("ENABLE_PROMO_PAGE") or None, default=False)
ENABLE_CLUB_FINDER = parse_bool_env(os.environ.get("ENABLE_CLUB_FINDER") or None, default=True)
ENABLE_HELP = parse_bool_env(os.environ.get("ENABLE_HELP") or None, default=False)
MAILING_ADDRESS = os.environ.get("MAILING_ADDRESS", "No address configured")
WEEKLY_PROMO_MESSAGE = os.environ.get("WEEKLY_PROMO_MESSAGE", "")

# the following words are very common and should not be used when generating recommended lots or assigning categories
IGNORE_WORDS = [
    "albino",
    "red",
    "blue",
    "pair",
    "super",
    "fish",
    "black",
    "breeding",
    "group",
    "fry",
    "female",
    "water",
    "male",
    "trio",
    "green",
    "lot",
    "fin",
    "yellow",
    "gold",
    "large",
    "donation",
    "young",
    "filter",
    "white",
    "fire",
    "blood",
    "and",
    "orange",
    "bag",
    "qty",
    "juvies",
    "starter",
    "adult",
    "hardy",
    "with",
    "small",
    "size",
    "breeders",
    "brown",
    "breeder",
    "pack",
    "two",
    "pink",
    "proven",
    "better",
    "than",
    "more",
    "adults",
    "inch",
    "from",
    "wild",
    "bunch",
    "superb",
    "the",
    "double",
    "reverse",
    "new",
    "test",
]
ONLINE_TUTORIAL_YOUTUBE_ID = "mNcOjAakC4c"
ONLINE_TUTORIAL_CHAPTERS = (
    (0, "Intro"),
    (45, "Account creation"),
    (1 * 60 + 25, "Auction creation"),
    (1 * 60 + 49, "Setting the location to exchange lots"),
    (2 * 60 + 37, "Rules"),
    (4 * 60 + 2, "Joining the auction"),
    (5 * 60 + 2, "Adding lots"),
    (6 * 60 + 30, "Copying lots"),
    (6 * 60 + 51, "Issues with joining your auction"),
    (8 * 60 + 58, "Bidding and proxy bidding"),
    (9 * 60 + 49, "Sniping and the end of the auction"),
    (11 * 60 + 11, "Invoices"),
    (12 * 60 + 9, "PayPal Batch Invoicing"),
    (13 * 60 + 12, "What happens if someone doesn't pay?"),
    (14 * 60 + 20, "Lot labels"),
    (15 * 60 + 23, "Stats"),
    (17 * 60 + 13, "Multi-location auctions"),
    (19 * 60 + 29, "Help and support"),
)
IN_PERSON_TUTORIAL_YOUTUBE_ID = "BXnoMMU_aCQ"
IN_PERSON_TUTORIAL_CHAPTERS = (
    (0, "Intro"),
    (36, "Account creation"),
    (1 * 60 + 17, "Auction creation"),
    (1 * 60 + 45, "Rules"),
    (2 * 60 + 54, "Location"),
    (3 * 60 + 22, "Joining the auction"),
    (3 * 60 + 44, "Adding users manually"),
    (4 * 60 + 31, "Users joining your auction"),
    (4 * 60 + 47, "Auction administrators"),
    (5 * 60 + 42, "Adding lots"),
    (6 * 60 + 10, "Editing lots"),
    (6 * 60 + 34, "Users adding lots"),
    (7 * 60 + 38, "Lot labels"),
    (8 * 60 + 37, "The auction itself: Set lot winners"),
    (9 * 60 + 50, "Some common issues with selling lots"),
    (11 * 60 + 1, "Invoices and payments"),
    (13 * 60 + 3, "Auction hall layout"),
    (14 * 60 + 5, "Images and lots"),
    (14 * 60 + 45, "Selling fees discounts for club members"),
    (15 * 60 + 52, "Changing bidder numbers"),
    (16 * 60 + 38, "Stats"),
    (18 * 60 + 54, "Attrition and Buy Now"),
    (22 * 60 + 50, "Reusing rules in your next auction"),
    (23 * 60 + 25, "Copying users between auctions"),
    (24 * 60 + 00, "Advertising"),
    (24 * 60 + 52, "Help and Support"),
)
HYBRID_TUTORIAL_YOUTUBE_ID = "tLR7l4Xsgtc"
HYBRID_TUTORIAL_CHAPTERS = (
    (0, "Intro"),
    (13, "Enable online bidding"),
    (33, "Bidding"),
    (59, "Seeing the max bid"),
    (1 * 60 + 27, "Setting winners"),
    (2 * 60 + 3, "Buy Now"),
    (2 * 60 + 45, "Payment"),
)
SUMMERNOTE_THEME = "bs5"

SUMMERNOTE_CONFIG = {
    "iframe": True,
    "summernote": {
        # Change editor size
        "width": "100%",
        "disableDragAndDrop": True,
        # 'height': '480',
        # https://summernote.org/deep-dive/#custom-toolbar-popover
        "toolbar": [
            ["style", ["style"]],
            ["font", ["bold", "italic", "clear"]],
            # ["color", ["color"]],
            [
                "para",
                [
                    "ul",
                    "ol",
                ],
            ],
            [
                "insert",
                [
                    "link",
                ],
            ],  # 'picture', 'video']],
            ["view", ["codeview"]],
            # ['view', ['fullscreen', 'codeview', 'help']],
        ],
    },
    "js": (
        ("/static/summernote/bs5-hack.js"),
        ("/static/summernote/clean-on-paste.js"),
    ),
    # Require users to be authenticated for uploading attachments.
    # 'attachment_require_authentication': True,
    # Set `upload_to` function for attachments.
    # 'attachment_upload_to': my_custom_upload_to_func(),
    # Set custom storage class for attachments.
    # 'attachment_storage_class': 'my.custom.storage.class.name',
    # Set custom model for attachments (default: 'django_summernote.Attachment')
    # 'attachment_model': 'my.custom.attachment.model',  # must inherit 'django_summernote.AbstractAttachment'
    # Set to `False` to return attachment paths in relative URIs.
    # 'attachment_absolute_uri': True,
}

X_FRAME_OPTIONS = "SAMEORIGIN"

PAYPAL_API_BASE = os.environ.get("PAYPAL_API_BASE", "")
if not PAYPAL_API_BASE:
    if DEBUG:
        PAYPAL_API_BASE = "https://api-m.sandbox.paypal.com"
    else:
        PAYPAL_API_BASE = "https://api-m.paypal.com"
PAYPAL_CLIENT_ID = os.environ.get("PAYPAL_CLIENT_ID", "")
PAYPAL_SECRET = os.environ.get("PAYPAL_SECRET", "")
# these next two are only used for making payments on behalf of others
PARTNER_MERCHANT_ID = os.environ.get("PARTNER_MERCHANT_ID", "")
PAYPAL_BN_CODE = os.environ.get("PAYPAL_BN_CODE", "")
PAYPAL_WEBHOOK_ID = os.environ.get("PAYPAL_WEBHOOK_ID", "")
PAYPAL_PLATFORM_FEE = Decimal(str(os.environ.get("PAYPAL_PLATFORM_FEE", "0") or "0"))

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://:"
        + os.environ.get("REDIS_PASSWORD", "unsecure")
        + "@"
        + os.environ.get("REDIS_HOST", "redis")
        + ":6379/3",
    }
}

# Celery Configuration
# https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html

# Celery Broker URL using Redis
CELERY_BROKER_URL = (
    "redis://:" + os.environ.get("REDIS_PASSWORD", "unsecure") + "@" + os.environ.get("REDIS_HOST", "redis") + ":6379/1"
)

# Celery Result Backend using Redis
CELERY_RESULT_BACKEND = (
    "redis://:" + os.environ.get("REDIS_PASSWORD", "unsecure") + "@" + os.environ.get("REDIS_HOST", "redis") + ":6379/2"
)

# Celery Settings
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery Beat Scheduler (for periodic tasks)
CELERY_BEAT_SCHEDULER = "fishauctions.custom_scheduler:FixedDatabaseScheduler"

# Task time limits (in seconds)
CELERY_TASK_SOFT_TIME_LIMIT = 300  # 5 minutes
CELERY_TASK_TIME_LIMIT = 600  # 10 minutes

# Worker settings
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
# Square settings - OAuth only, no platform credentials
SQUARE_ENVIRONMENT = os.environ.get("SQUARE_ENVIRONMENT", "sandbox" if DEBUG else "production")
SQUARE_APPLICATION_ID = os.environ.get("SQUARE_APPLICATION_ID", "")
SQUARE_CLIENT_SECRET = os.environ.get("SQUARE_CLIENT_SECRET", "")  # For OAuth token exchange
# Webhook signature key for verifying Square webhook notifications
SQUARE_WEBHOOK_SIGNATURE_KEY = os.environ.get("SQUARE_WEBHOOK_SIGNATURE_KEY", "")
# Email domains blocked by Square payment links (comma-separated)
_blocked_domains_raw = os.environ.get(
    "SQUARE_BLOCKED_EMAIL_DOMAINS", "example.com,example.org,example.net,test.com,invalid.com"
)
SQUARE_BLOCKED_EMAIL_DOMAINS = []
for domain in _blocked_domains_raw.split(","):
    stripped = domain.strip().lower()
    if stripped:
        SQUARE_BLOCKED_EMAIL_DOMAINS.append(stripped)

# Field encryption key for django-encrypted-model-fields
# This should be a Fernet key - generate with: from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())
# FIELD_ENCRYPTION_KEY is required for encrypted model fields (SquareSeller OAuth tokens)
_encryption_key = os.environ.get("FIELD_ENCRYPTION_KEY", "")
if not _encryption_key:
    from cryptography.fernet import Fernet
    from django.core.exceptions import ImproperlyConfigured

    # Generate a key and show the user how to add it to .env
    generated_key = Fernet.generate_key().decode()
    env_line = f"FIELD_ENCRYPTION_KEY={generated_key}"
    print("\n" + "=" * 80)  # noqa: T201
    print("FIELD_ENCRYPTION_KEY is required but not set!")  # noqa: T201
    print("Add this line to your .env file:")  # noqa: T201
    print(f"\n{env_line}\n")  # noqa: T201
    print("=" * 80 + "\n")  # noqa: T201
    msg = f"FIELD_ENCRYPTION_KEY environment variable is required. Add this to your .env file: {env_line}"
    raise ImproperlyConfigured(msg)
FIELD_ENCRYPTION_KEY = _encryption_key

# Mailchimp OAuth integration settings (one global app; each club authorizes it)
MAILCHIMP_CLIENT_ID = os.environ.get("MAILCHIMP_CLIENT_ID", "")
MAILCHIMP_CLIENT_SECRET = os.environ.get("MAILCHIMP_CLIENT_SECRET", "")

# Brevo integration: each club connects with its own API key (no site-level config needed).

# Discord bot integration settings
DISCORD_PUBLIC_KEY = os.environ.get("DISCORD_PUBLIC_KEY", "")
DISCORD_BOT_TOKEN = os.environ.get("DISCORD_BOT_TOKEN", "")
DISCORD_BOT_CLIENT_ID = os.environ.get("DISCORD_BOT_CLIENT_ID", "")

# Google Wallet membership card integration (optional). See readme.md.
# Set GOOGLE_WALLET_KEYFILE in .env to the filename of your Google service account
# JSON key. The file must live in the same directory as .env (the project BASE_DIR).
# If either the issuer ID or the keyfile is missing/unreadable, the "Add to Google
# Wallet" button is hidden and the auto-create-class signal no-ops.
GOOGLE_WALLET_ISSUER_ID = os.environ.get("GOOGLE_WALLET_ISSUER_ID", "")
GOOGLE_WALLET_KEYFILE = os.environ.get("GOOGLE_WALLET_KEYFILE", "")
GOOGLE_WALLET_SERVICE_ACCOUNT_EMAIL = ""
GOOGLE_WALLET_SERVICE_ACCOUNT_KEY = ""
if GOOGLE_WALLET_KEYFILE:
    import json as _json

    _wallet_keyfile_path = BASE_DIR / GOOGLE_WALLET_KEYFILE
    try:
        with _wallet_keyfile_path.open() as _f:
            _wallet_key = _json.load(_f)
        GOOGLE_WALLET_SERVICE_ACCOUNT_EMAIL = _wallet_key.get("client_email", "")
        GOOGLE_WALLET_SERVICE_ACCOUNT_KEY = _wallet_key.get("private_key", "")
    except (OSError, ValueError) as _wallet_err:
        # File missing or invalid JSON — leave email/key empty so is_configured() returns False.
        # We intentionally don't raise so a misconfigured prod box still boots; the wallet
        # button just won't appear and the create-class signal no-ops.
        import logging as _logging

        _logging.getLogger(__name__).warning(
            "GOOGLE_WALLET_KEYFILE=%s could not be loaded (%s: %s); Google Wallet disabled.",
            _wallet_keyfile_path,
            type(_wallet_err).__name__,
            _wallet_err,
        )

# Apple Wallet membership card integration (optional). See readme.md.
# Drop your Pass Type ID .p12 cert and the Apple WWDR intermediate .pem next to .env
# and point these settings at the filenames. If any one is missing the "Add to
# Apple Wallet" button is hidden and pkpass downloads return 404.
APPLE_WALLET_CERT_FILE = os.environ.get("APPLE_WALLET_CERT_FILE", "")
APPLE_WALLET_CERT_PASSWORD = os.environ.get("APPLE_WALLET_CERT_PASSWORD", "")
APPLE_WALLET_WWDR_FILE = os.environ.get("APPLE_WALLET_WWDR_FILE", "")
APPLE_WALLET_PASS_TYPE_IDENTIFIER = os.environ.get("APPLE_WALLET_PASS_TYPE_IDENTIFIER", "")
APPLE_WALLET_TEAM_IDENTIFIER = os.environ.get("APPLE_WALLET_TEAM_IDENTIFIER", "")
APPLE_WALLET_ORGANIZATION_NAME = os.environ.get("APPLE_WALLET_ORGANIZATION_NAME", "")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "api_key_default": "1000/hour",
        "mobile_auth": "10/min",
        # Catch-all for mobile reads/writes. Sized for admin bulk workflows that live here — checkout
        # is 2 calls/buyer (create+confirm) and labels are 1 call/lot, so a busy auction hour is
        # several hundred calls; 200/hour blocked that mid-checkout.
        "mobile_api": "1000/hour",
        # Search-as-you-type: each query fires a search + a log call on a ~300ms debounce, so a fast
        # typer briefly peaks ~6 req/sec. 120/min tolerates that burst while capping sustained abuse.
        "mobile_search": "120/min",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
}
