# Generated by Django 3.1.1 on 2020-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
