# Generated by Django 3.1.1 on 2020-09-18 00:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('user', 'active', 'lot_name', 'description')},
        ),
    ]
