# Generated by Django 3.1.1 on 2020-09-18 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200918_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bill_for_unsold_lots',
        ),
        migrations.AddField(
            model_name='auction',
            name='unsold_lot_fee',
            field=models.PositiveIntegerField(default=0, help_text="The amount, in dollars, that each seller will be charged if their lot doesn't sell", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='lot',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
    ]
