# Generated by Django 3.1.1 on 2020-10-04 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='area',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='test',
        ),
        migrations.AddField(
            model_name='auction',
            name='location',
            field=models.ForeignKey(blank=True, help_text='State or region of this auction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.location'),
        ),
    ]
