# Generated by Django 3.1.1 on 2020-10-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201004_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
