# Generated by Django 3.1.1 on 2020-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
