# Generated by Django 3.1.1 on 2020-10-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_lot_transportable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
