# Generated by Django 3.1.1 on 2020-09-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200925_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='breeder_points',
            field=models.BooleanField(default=True),
        ),
    ]
