# Generated by Django 3.1.1 on 2020-10-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201004_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_bought',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_sold',
        ),
    ]
