# Generated by Django 3.1.1 on 2020-09-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200927_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='alternate_pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
