# Generated by Django 3.1.1 on 2020-09-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200927_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='pickup_location',
            field=models.CharField(default='default', help_text='Find the location on Google maps, click Menu>Share or Embed Map and paste the embed link here', max_length=255),
            preserve_default=False,
        ),
    ]
