# Generated by Django 3.1.1 on 2020-10-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201004_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='rank_total_lots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='rank_total_spent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='rank_unique_species',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
