# Generated by Django 3.1.1 on 2020-10-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
