# Generated by Django 3.1.1 on 2020-09-27 15:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200927_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
