# Generated by Django 3.1.1 on 2020-09-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='code_to_add_lots',
            field=models.CharField(blank=True, help_text='People in your club will enter this code to put their lots in this auction', max_length=255, null=True),
        ),
    ]
