# Generated by Django 3.1.1 on 2020-10-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201005_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='location',
            field=models.CharField(blank=True, help_text='State or region of this auction', max_length=300, null=True),
        ),
    ]
