# Generated by Django 3.1.1 on 2020-10-02 13:21

import autoslug.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_code_to_add_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='alternate_pickup_location',
            field=models.CharField(blank=True, help_text='Description of alternate pickup location', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='alternate_pickup_location_map',
            field=models.CharField(blank=True, help_text='Google Maps link to alternate pickup location', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='code_to_add_lots',
            field=models.CharField(blank=True, help_text='This is like a password: People in your club will enter this code to put their lots in this auction', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='lot_entry_fee',
            field=models.PositiveIntegerField(default=0, help_text='The amount, in dollars, that the seller will be charged if a lot sells', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='pickup_location',
            field=models.CharField(help_text='Description of pickup location', max_length=300),
        ),
        migrations.AlterField(
            model_name='auction',
            name='pickup_location_map',
            field=models.CharField(help_text='Find the location on Google maps, click Menu>Share or Embed Map and paste the embed link here', max_length=2000),
        ),
        migrations.AlterField(
            model_name='auction',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='unsold_lot_fee',
            field=models.PositiveIntegerField(default=0, help_text="The amount, in dollars, that the seller will be charged if their lot doesn't sell", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
