# Generated by Django 3.1.1 on 2020-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201005_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lot',
            name='banned',
            field=models.BooleanField(default=False, help_text="This lot will be hidden from views, and users won't be able to bid on it"),
        ),
        migrations.AlterField(
            model_name='lot',
            name='donation',
            field=models.BooleanField(default=False, help_text='All proceeds from this lot will go to the club'),
        ),
    ]
