# Generated by Django 3.1.1 on 2020-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201008_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email_visible',
            field=models.BooleanField(default=True, help_text='Show your email address on your user page.  This will be visible only to logged in users.'),
        ),
    ]
