# Generated by Django 3.1.1 on 2020-10-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201010_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='number_total_bids',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='rank_total_bids',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
