# Generated by Django 3.1.1 on 2020-11-01 01:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0021_auto_20201025_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name_plural': 'Users watching'},
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('user', 'lot_name', 'description')},
        ),
    ]
