# Generated by Django 3.1.1 on 2020-11-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20201031_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='use_list_view',
            field=models.BooleanField(default=False, help_text='Show a list of all lots instead of showing tiles'),
        ),
    ]
