# Generated by Django 3.1.1 on 2020-11-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_userdata_use_list_view'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='lot',
        #     unique_together=set(),
        # ),
    ]
