# Generated by Django 3.1.1 on 2020-11-02 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201102_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='last_bid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
