# Generated by Django 3.1.1 on 2020-11-03 01:30

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_bid_last_bid_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='description_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='text_rendered'),
        ),
    ]
