# Generated by Django 3.1.1 on 2020-11-03 12:57

from django.db import migrations
import easy_thumbnails.fields
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20201102_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, help_text='To add a link: [Link text](https://www.google.com)', null=True, rendered_field='description_rendered'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Add a picture of the item here', upload_to='images/'),
        ),
    ]
