# Generated by Django 3.1.1 on 2020-11-13 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0028_auto_20201103_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lot_submission_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='notes_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, help_text='To add a link: [Link text](https://www.google.com)', null=True, rendered_field='notes_rendered'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='i_bred_this_fish',
            field=models.BooleanField(default=False, help_text='Check to get breeder points for this lot', verbose_name='I bred this fish/propagated this plant'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_name',
            field=models.CharField(default='', help_text='Short description of this lot', max_length=255),
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('public', models.BooleanField(default=False, help_text='Allow auctions created by other users to select this pickup location')),
                ('description', models.CharField(help_text='e.x. First floor of parking garage near Sears entrance', max_length=300)),
                ('google_map_iframe', models.CharField(blank=True, help_text='Find the location on Google maps, click Menu>Share or Embed Map and paste the embed link here.  You must embed an iframe, not a link.', max_length=2000, null=True)),
                ('pickup_time', models.DateTimeField()),
                ('second_pickup_time', models.DateTimeField(blank=True, help_text="If you'll have a dropoff for sellers in the morning and then a pickup for buyers in the afternoon at this location, this should be the pickup time.", null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('pickup_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.pickuplocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='pickup_locations',
            field=models.ManyToManyField(blank=True, to='auctions.PickupLocation'),
        ),
    ]
