# Generated by Django 3.1.1 on 2020-11-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20201113_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='pickup_locations',
        ),
        migrations.RemoveField(
            model_name='pickuplocation',
            name='public',
        ),
        migrations.RemoveField(
            model_name='pickuplocation',
            name='user',
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction'),
        ),
    ]
