# Generated by Django 3.1.1 on 2020-11-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0031_auto_20201113_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctiontos',
            name='pickup_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.pickuplocation'),
            preserve_default=False,
        ),
    ]
