# Generated by Django 3.1.1 on 2020-11-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20201115_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='pickup_location',
            field=models.CharField(blank=True, help_text='Description of pickup location', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='pickup_location_map',
            field=models.CharField(blank=True, help_text='Find the location on Google maps, click Menu>Share or Embed Map and paste the embed link here', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
