# Generated by Django 3.1.1 on 2020-11-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20201115_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctiontos',
            options={'verbose_name': 'Auction pickup location', 'verbose_name_plural': 'Auction pickup locations'},
        ),
        migrations.AddField(
            model_name='lot',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
