# Generated by Django 3.1.1 on 2020-11-20 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_auto_20201120_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lot_promotion_cost',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
