# Generated by Django 3.1.1 on 2020-11-23 16:38

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_auction_lot_promotion_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('body', markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='body_rendered')),
                ('body_rendered', markdownfield.models.RenderedMarkdownField(null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='first_bid_payout',
            field=models.PositiveIntegerField(default=0, help_text='The first time a user bids in this auction, give them a credit in this amount.  This will appear on their invoice', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='adjustment',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='adjustment_direction',
            field=models.CharField(blank=True, choices=[('PAY_SELLER', 'Pay the seller'), ('PAY_CLUB', 'Charge the seller')], max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='adjustment_notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.lot'),
        ),
    ]
