# Generated by Django 3.1.1 on 2020-11-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20201123_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='extra_js',
            field=models.CharField(blank=True, max_length=16000, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='sealed_bid',
            field=models.BooleanField(default=False, help_text="Users won't be able to see what the current bid is"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='adjustment_direction',
            field=models.CharField(choices=[('PAY_SELLER', 'Pay the seller'), ('PAY_CLUB', 'Charge the seller')], default='PAY_CLUB', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='adjustment_notes',
            field=models.CharField(default='Corrected', max_length=150),
        ),
    ]
