# Generated by Django 3.1.1 on 2020-11-28 17:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_auto_20201127_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='promote_this_auction',
            field=models.BooleanField(default=True, help_text='Show in the list of auctions on the main page and post to social media about updates to this auction.  Uncheck if this is a test auction.'),
        ),
        migrations.AddField(
            model_name='lot',
            name='feedback_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='lot',
            name='feedback_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
