# Generated by Django 3.1.1 on 2020-11-28 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_auto_20201128_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='winner_feedback_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='lot',
            name='winner_feedback_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
