# Generated by Django 3.1.4 on 2020-12-22 22:28

from django.db import migrations, models
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_lot_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Waiting for payment'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='local_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='other_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='payment_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='payment_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='payment_other_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='payment_other_method',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='payment_paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lot',
            name='ship_to_continental_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='address',
            field=models.CharField(blank=True, help_text='Search Google maps with this address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='location_coordinates',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email_me_about_new_auctions',
            field=models.BooleanField(blank=True, default=True, help_text='When new nearby auctions are created, notify me'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email_me_about_new_auctions_distance',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='Notifications will be sent when new auctions are less than this many miles from your address', null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email_me_about_new_local_lots',
            field=models.BooleanField(blank=True, default=True, help_text="When new nearby lots (that aren't part of an auction) are created, notify me"),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email_me_about_new_lots_ship_to_continental_us',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='has_unsubscribed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='local_distance',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='Lots are considered local if they are less than this many miles from your address.', null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='location_coordinates',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='paypal_email_address',
            field=models.CharField(blank=True, help_text='This is your Paypal address, if different from your email address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='unsubscribe_link',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='adjustment_direction',
            field=models.CharField(choices=[('PAY_SELLER', 'Discount'), ('PAY_CLUB', 'Charge extra')], default='PAY_CLUB', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='name',
            field=models.CharField(default='', help_text='This will be the name shown to users', max_length=50),
        ),
    ]
