# Generated by Django 3.1.4 on 2020-12-27 16:27

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_auto_20201222_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuplocation',
            name='location_coordinates',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='address',
            field=models.CharField(blank=True, help_text='Your complete mailing address.  If you sell lots in an auction, your check will be mailed here.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_me_about_new_auctions',
            field=models.BooleanField(blank=True, default=True, help_text='When new auctions are created with pickup locations near my location, notify me'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_me_about_new_auctions_distance',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='miles, from your address', null=True, verbose_name='New auction distance'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_visible',
            field=models.BooleanField(default=True, help_text='Show your email address on your user page.  This will be visible only to logged in users.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location_coordinates',
            field=location_field.models.plain.PlainLocationField(blank=True, help_text='Make sure your location is correct - you will get notifications about nearby auctions', max_length=63, null=True, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='use_list_view',
            field=models.BooleanField(default=False, help_text='Show a list of all lots instead of showing pictures'),
        ),
    ]
