# Generated by Django 3.1.4 on 2020-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_auto_20201227_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email_me_about_new_lots_ship_to_continental_us',
        ),
        migrations.AddField(
            model_name='userdata',
            name='email_me_about_new_lots_ship_to_location',
            field=models.BooleanField(blank=True, default=True, help_text='Email me when new lots are created that can be shipped to my location'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='local_distance',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='miles, from your address', null=True),
        ),
    ]
