# Generated by Django 3.1.4 on 2020-12-28 19:36

import django.core.validators
from django.db import migrations, models
import location_field.models.plain
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0048_auto_20201227_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='ship_to_continental_us',
        ),
        migrations.AddField(
            model_name='lot',
            name='shipping_locations',
            field=models.ManyToManyField(to='auctions.Location'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='first_bid_payout',
            field=models.PositiveIntegerField(default=0, help_text="This is a feature to encourage bidding.  Give each bidder this amount, for free.  <a href='/blog/encouraging-participation/' target='_blank'>More information</a>", validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, help_text='To add a link: [Link text](https://www.google.com)', null=True, rendered_field='notes_rendered', verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='promote_this_auction',
            field=models.BooleanField(default=True, help_text='Notify users and post on social media about this auction.  Uncheck if this is a test or private auction.'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='location_coordinates',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_me_about_new_lots_ship_to_location',
            field=models.BooleanField(blank=True, default=True, help_text='Email me when new lots are created that can be shipped to my location', verbose_name='Email me about lots that can be shipped'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='local_distance',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='miles, from your address', null=True, verbose_name='New local lot distance'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='location_coordinates',
            field=location_field.models.plain.PlainLocationField(blank=True, help_text='Make sure your map marker is correctly placed - you will get notifications about nearby auctions', max_length=63, null=True, verbose_name='Map'),
        ),
    ]
