# Generated by Django 3.1.4 on 2020-12-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0049_auto_20201228_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='shipping_locations',
            field=models.ManyToManyField(blank=True, help_text='Hold control to select more than one location', null=True, to='auctions.Location'),
        ),
    ]
