# Generated by Django 3.1.4 on 2020-12-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0050_auto_20201228_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_name',
            field=models.CharField(default='', help_text='Short description of this lot', max_length=40),
        ),
        migrations.AlterField(
            model_name='lot',
            name='shipping_locations',
            field=models.ManyToManyField(blank=True, help_text='Control + click to select more than one location', to='auctions.Location'),
        ),
    ]
