# Generated by Django 3.1.4 on 2020-12-30 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0051_auto_20201230_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='other',
        ),
        migrations.AddField(
            model_name='lot',
            name='buy_now_price',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The minimum bid for this lot. Lot will not be sold unless someone bids at least this much', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='lot',
            name='other_text',
            field=models.CharField(blank=True, help_text='Shipping methods, temperature restrictions, etc.', max_length=200, null=True, verbose_name='Shipping notes'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='reserve_price',
            field=models.PositiveIntegerField(default=2, help_text='The minimum bid for this lot. Lot will not be sold unless someone bids at least this much', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
