# Generated by Django 3.1.4 on 2020-12-31 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0052_auto_20201230_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='date_of_last_user_edit',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='auction',
            field=models.ForeignKey(blank=True, help_text="You must read the auction's rules and select a pickup location, and this lot must be brought to that location", null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='buy_now_price',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='This lot will be sold instantly for this price if someone is willing to pay this much', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='lot',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Optional.  Add a picture of the item here.', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='payment_cash',
            field=models.BooleanField(default=False, verbose_name='Cash accepted'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='payment_other',
            field=models.BooleanField(default=False, verbose_name='Other payment method accepted'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='payment_other_address',
            field=models.CharField(blank=True, help_text='The address or username you wish to get payment at', max_length=200, null=True, verbose_name='Payment address'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='payment_other_method',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='payment_paypal',
            field=models.BooleanField(default=False, verbose_name='Paypal accepted'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='promoted',
            field=models.BooleanField(default=False, help_text='This does nothing right now lol', verbose_name='Promote this lot'),
        ),
    ]
