# Generated by Django 3.1.4 on 2021-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0055_auto_20210103_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lothistory',
            options={'ordering': ['timestamp'], 'verbose_name': 'Chat history', 'verbose_name_plural': 'Chat history'},
        ),
        migrations.AddField(
            model_name='lothistory',
            name='current_price',
            field=models.PositiveIntegerField(blank=True, help_text='Price of the lot immediately AFTER this message', null=True),
        ),
    ]
