# Generated by Django 3.1.4 on 2021-01-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0056_auto_20210103_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lothistory',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.lot'),
        ),
        migrations.AlterField(
            model_name='lothistory',
            name='message',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='lothistory',
            name='seen',
            field=models.BooleanField(default=False, help_text='Has the lot submitter seen this message?'),
        ),
    ]
