# Generated by Django 3.1.4 on 2021-01-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0058_auction_max_lots_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuplocation',
            name='google_map_iframe',
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='pickup_location_contact_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='pickup_location_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='pickup_location_contact_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='users_must_coordinate_pickup',
            field=models.BooleanField(default=False, help_text='Contact for pickup time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='max_lots_per_user',
            field=models.PositiveIntegerField(blank=True, help_text="A user won't be able to add more than this many lots to this auction", null=True),
        ),
    ]
