# Generated by Django 3.1.4 on 2021-01-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0059_auto_20210107_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='email_fifth_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='email_first_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='email_fourth_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='email_second_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='email_third_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lot',
            field=models.ForeignKey(blank=True, help_text='not used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.lot'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_location_contact_email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Contact person's email"),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_location_contact_name',
            field=models.CharField(blank=True, help_text='Name of the person coordinating this pickup location.  Contact info is only shown to logged in users.', max_length=200, null=True, verbose_name="Contact person's name"),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_location_contact_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Contact person's phone"),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='users_must_coordinate_pickup',
            field=models.BooleanField(default=False, help_text='The pickup time fields will not be used'),
        ),
    ]
