# Generated by Django 3.1.4 on 2021-01-16 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0060_auto_20210112_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_visible',
            field=models.BooleanField(default=True, help_text="Show your email address on your user page.  This will be visible only to logged in users.  <a href='/blog/privacy/' target='_blank'>Privacy information</a>"),
        ),
    ]
