# Generated by Django 3.1.4 on 2021-01-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0061_auto_20210116_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='userdata',
            name='use_dark_theme',
            field=models.BooleanField(default=True, help_text='Uncheck to use the blindingly bright light theme'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='auction',
            field=models.ForeignKey(blank=True, help_text="If your auction isn't listed here, it may not exist or has already ended", null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='name',
            field=models.CharField(default='', help_text='Location name shown to users.  e.x. University Mall in VT', max_length=50),
        ),
    ]
