# Generated by Django 3.1.4 on 2021-01-17 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0062_auto_20210116_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='promotion_budget',
            field=models.PositiveIntegerField(default=2, help_text="The most money you're willing to spend on ads for this lot.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='userdata',
            name='can_submit_standalone_lots',
            field=models.BooleanField(default=False),
        ),
    ]
