# Generated by Django 3.1.4 on 2021-01-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0063_auto_20210117_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='alternate_pickup_location',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='alternate_pickup_location_map',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='alternate_pickup_time',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='pickup_location_map',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='blog_post',
        ),
    ]
