# Generated by Django 3.1.4 on 2021-01-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0065_remove_invoice_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
