# Generated by Django 3.1.4 on 2021-01-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0066_auto_20210117_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email_me_when_people_comment_on_my_lots',
            field=models.BooleanField(blank=True, default=True, help_text="Notifications will be sent once a day, only for messages you haven't seen"),
        ),
    ]
