# Generated by Django 3.1.4 on 2021-01-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0067_userdata_email_me_when_people_comment_on_my_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='date_contacted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='homepage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
