# Generated by Django 3.1.4 on 2021-01-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0069_auto_20210122_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
