# Generated by Django 3.1.4 on 2021-01-30 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0071_auto_20210123_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiontos',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
