# Generated by Django 3.1.4 on 2021-02-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0072_auctiontos_createdon'),
    ]

    operations = [
        migrations.AddField(
            model_name='lothistory',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Set to true automatically when the notification email is sent'),
        ),
    ]
