# Generated by Django 3.1.4 on 2021-02-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0073_lothistory_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='allow_additional_lots_as_donation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='dismissed_cookies_tos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='promote_this_auction',
            field=models.BooleanField(default=True, help_text="Show this to everyone in the list of auctions. <span class='text-warning'>Uncheck if this is a test or private auction</span>."),
        ),
    ]
