# Generated by Django 3.1.4 on 2021-03-11 13:49

import django.core.validators
from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0074_auto_20210205_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='show_ads',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='allow_additional_lots_as_donation',
            field=models.BooleanField(default=True, help_text="If you don't set max lots per user, this has no effect"),
        ),
        migrations.AlterField(
            model_name='auction',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, default='', help_text='To add a link: [Link text](https://www.google.com)', null=True, rendered_field='notes_rendered', verbose_name='Rules'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='quantity',
            field=models.PositiveIntegerField(help_text='How many of this item are in this lot?', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
