# Generated by Django 3.1.4 on 2021-03-14 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0075_auto_20210311_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterestcategory',
            name='as_percent',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='show_ads',
            field=models.BooleanField(blank=True, default=True, help_text='100% of ad profits support the Tropical Fish Club of Burlington'),
        ),
    ]
