# Generated by Django 3.1.4 on 2021-03-20 00:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0076_auto_20210314_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='images/')),
                ('title', models.CharField(default='', max_length=40)),
                ('text', models.CharField(blank=True, max_length=40, null=True)),
                ('external_url', models.URLField(max_length=300)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_ads', models.PositiveIntegerField(default=10000000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
                ('max_clicks', models.PositiveIntegerField(default=10000000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
                ('bid', models.FloatField(default=0.51, help_text="At the moment, this is not actually the cost per click, it's the percent chance of showing this ad.  If the top ad fails, the next one will be selected.  If there are none left, google ads will be loaded.  Expects 0-1")),
                ('auction', models.ForeignKey(blank=True, help_text='If set, this campaign will only be run on a particular auction (leave blank for site-wide)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction')),
                ('category', models.ForeignKey(blank=True, help_text='If set, this ad will only be shown to users interested in this particular category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category', verbose_name='Category')),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdCampaignResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseid', models.CharField(blank=True, default=uuid.uuid4, max_length=255)),
                ('session', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.adcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
