# Generated by Django 3.1.4 on 2021-03-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0077_adcampaign_adcampaignresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='body_html',
            field=models.CharField(default='', max_length=300),
        ),
    ]
