# Generated by Django 3.1.4 on 2021-03-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0078_adcampaign_body_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcampaign',
            name='begin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
