# Generated by Django 3.1.4 on 2021-03-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0079_auto_20210320_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adcampaign',
            name='start_date',
        ),
    ]
