# Generated by Django 3.1.4 on 2021-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0081_auto_20210321_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='lothistory',
            name='bid_amount',
            field=models.PositiveIntegerField(blank=True, help_text='For any kind of debugging', null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_name',
            field=models.CharField(help_text='Short description of this lot', max_length=40),
        ),
    ]
