# Generated by Django 3.1.7 on 2021-04-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0083_auto_20210415_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='lot',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.lot'),
        ),
        migrations.AddField(
            model_name='lothistory',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='make_stats_public',
            field=models.BooleanField(default=False, help_text="Allow any user who has a link to this auction's stats to see them.  Uncheck to only allow the auction creator to view stats"),
        ),
        migrations.AlterField(
            model_name='lotimage',
            name='is_primary',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
