# Generated by Django 3.1.7 on 2021-04-16 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0086_auto_20210415_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='clone_complete',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='cloned_from',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='clone_complete',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='cloned_from',
        ),
        migrations.AddField(
            model_name='lot',
            name='deactivated',
            field=models.BooleanField(default=False, help_text="You can deactivate your own lots to remove all bids and stop bidding.  Lots can be reactivated at any time, but existing bids won't be kept"),
        ),
        migrations.AddField(
            model_name='lot',
            name='relist_countdown',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='lot',
            name='relist_if_not_sold',
            field=models.BooleanField(default=False, help_text='When this lot ends without being sold, create a new copy of it'),
        ),
        migrations.AddField(
            model_name='lot',
            name='relist_if_sold',
            field=models.BooleanField(default=False, help_text='When this lot sells, create a new copy of it'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The total balance in your account', max_digits=6),
        ),
        migrations.AddField(
            model_name='userdata',
            name='show_ad_controls',
            field=models.BooleanField(blank=True, default=False, help_text='Show a tab for ads on all pages'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='species_category',
            field=models.ForeignKey(blank=True, help_text='An accurate category will help people find this lot more easily', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category', verbose_name='Category'),
        ),
    ]
