# Generated by Django 3.1.7 on 2021-04-16 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0087_auto_20210416_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='lot_run_duration',
            field=models.PositiveIntegerField(default=10, help_text='Days to run this lot for', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
