# Generated by Django 3.1.7 on 2021-04-23 18:09

import datetime
import django.core.validators
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0089_auto_20210419_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lot_submission_start_date',
            field=models.DateTimeField(null=True, blank=True, help_text='Users can submit (but not bid on) lots on this date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='buy_now_price',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="This lot will be sold instantly for this price if someone is willing to pay this much.  Leave blank unless you know exactly what you're doing", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
