# Generated by Django 3.1.7 on 2021-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0090_auto_20210423_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='lot_submission_start_date',
            field=models.DateTimeField(blank=True, help_text='Users can submit (but not bid on) lots on this date', null=True),
        ),
    ]
