# Generated by Django 3.2.4 on 2021-06-12 19:48

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0092_auto_20210612_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=100)),
                ('answer', markdownfield.models.MarkdownField(blank=True, help_text='To add a link: [Link text](https://www.google.com)', null=True, rendered_field='answer_rendered')),
                ('answer_rendered', markdownfield.models.RenderedMarkdownField(null=True)),
                ('question', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='question_text', unique=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='bump_cost',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='The amount a user will be charged each time they move a lot to the top of the list', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='lot',
            name='last_bump_date',
            field=models.DateTimeField(blank=True, help_text="Any time a lot is bumped, this date gets changed.  It's used for sorting by newest lots.", null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='number_of_bumps',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
