# Generated by Django 3.2.4 on 2021-06-16 01:09

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0093_auto_20210612_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='question', unique=True),
        ),
    ]
