# Generated by Django 4.0.3 on 2022-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0096_userdata_last_ip_address_alter_auction_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiontos',
            name='confirm_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctiontos',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Grant admin permissions to help run this auction'),
        ),
        migrations.AddField(
            model_name='lot',
            name='refunded',
            field=models.BooleanField(default=False, help_text="Don't charge the winner or pay the seller for this lot."),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='show_ads',
            field=models.BooleanField(blank=True, default=True, help_text="Ads have been disabled site-wide indefinitely, so this option doesn't do anything right now."),
        ),
    ]
