# Generated by Django 4.0.3 on 2022-05-22 22:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0098_auction_is_deleted_auction_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auctiontos'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_end',
            field=models.DateTimeField(blank=True, help_text='Bidding will end on this date.  If last-minute bids are placed, bidding can go up to 1 hour past this time on those lots.', null=True, verbose_name='Bidding end date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_start',
            field=models.DateTimeField(help_text='Bidding will be open on this date.  Must be in the future.', verbose_name='Auction start date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='lot_entry_fee',
            field=models.PositiveIntegerField(default=0, help_text='The amount the seller will be charged if a lot sells', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='lot_submission_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lot submission ends'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='lot_submission_start_date',
            field=models.DateTimeField(blank=True, help_text='Users can submit (but not bid on) lots on this date', null=True, verbose_name='Lot submission opens'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(help_text='This is the name people will see when joining your auction', max_length=255, verbose_name='Auction name'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='unsold_lot_fee',
            field=models.PositiveIntegerField(default=0, help_text="The amount the seller will be charged if their lot doesn't sell", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winning_bid_percent_to_club',
            field=models.PositiveIntegerField(default=0, help_text='In addition to the Lot entry fee, this percent of the winning price will be taken by the club', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
