# Generated by Django 4.0.3 on 2022-06-18 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0099_pickuplocation_contact_person_alter_auction_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiontos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='latitude',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='longitude',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
