# Generated by Django 4.0.3 on 2022-09-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0100_alter_auctiontos_user_alter_pickuplocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiontos',
            name='manually_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='description',
            field=models.CharField(blank=True, help_text='e.x. First floor of parking garage near Sears entrance', max_length=300, null=True),
        ),
    ]
