# Generated by Django 4.0.3 on 2022-09-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0101_auctiontos_manually_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctiontos',
            name='manually_added',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
