# Generated by Django 4.0.3 on 2022-09-23 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0102_alter_auctiontos_manually_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='no_login_link',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, verbose_name='This link will be emailed to the user, allowing them to view their invoice directly without logging in'),
        ),
        migrations.AddField(
            model_name='lot',
            name='custom_lot_number',
            field=models.CharField(blank=True, help_text='You can override the default lot number with this', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='auctiontos',
            name='bidder_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='auctiontos',
            name='confirm_email_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='auctiontos',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Grant admin permissions to help run this auction'),
        ),
        migrations.AlterField(
            model_name='auctiontos',
            name='print_reminder_email_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='auctiontos',
            name='second_confirm_email_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='lot',
            name='banned',
            field=models.BooleanField(default=False, help_text="This lot will be hidden from views, and users won't be able to bid on it.  Removed lots are not charged in invoices.", verbose_name='Removed'),
        ),
    ]
