# Generated by Django 4.0.3 on 2022-09-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0103_invoice_no_login_link_lot_custom_lot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='calculated_total',
            field=models.IntegerField(blank=True, help_text="This field is set automatically, you shouldn't need to manually change it", null=True),
        ),
    ]
