# Generated by Django 4.0.3 on 2023-01-28 22:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0105_alter_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLabelPrefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_width', models.FloatField(default=8.5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100.0)])),
                ('page_height', models.FloatField(default=11, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100.0)])),
                ('label_width', models.FloatField(default=2.51, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100.0)])),
                ('label_height', models.FloatField(default=0.96, validators=[django.core.validators.MinValueValidator(0.4), django.core.validators.MaxValueValidator(50.0)])),
                ('label_margin_right', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.2), django.core.validators.MaxValueValidator(5.0)])),
                ('label_margin_bottom', models.FloatField(default=0.02, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('page_margin_top', models.FloatField(default=0.55, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('page_margin_bottom', models.FloatField(default=0.45, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('page_margin_left', models.FloatField(default=0.18, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('page_margin_right', models.FloatField(default=0.18, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('font_size', models.FloatField(default=8, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(25)])),
                ('unit', models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
