# Generated by Django 4.0.3 on 2023-01-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0106_userlabelprefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlabelprefs',
            name='unit',
            field=models.CharField(choices=[('in', 'Inches'), ('cm', 'Centimeters')], default='in', max_length=20),
        ),
    ]
