# Generated by Django 4.0.3 on 2023-01-31 23:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0107_alter_userlabelprefs_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='allow_bidding_on_lots',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='email_users_when_invoices_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='pre_register_lot_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Decrease the club cut if users add lots through this website', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='auction',
            name='pre_register_lot_entry_fee_discount',
            field=models.PositiveIntegerField(default=0, help_text='Decrease the lot entry fee by this amount if users add lots through this website', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='lot',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added this lot -- used for pre-registration discounts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lot',
            name='category_automatically_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctiontos',
            name='bidder_number',
            field=models.CharField(blank=True, default='', help_text='Must be unique, blank to automatically generate', max_length=20),
        ),
    ]
