# Generated by Django 4.0.3 on 2023-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0109_auctiontos_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctiontos',
            name='memo',
        ),
        migrations.AddField(
            model_name='invoice',
            name='memo',
            field=models.CharField(blank=True, default='', help_text='Only other auction admins can see this', max_length=500, null=True),
        ),
    ]
