# Generated by Django 4.0.3 on 2023-02-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0110_remove_auctiontos_memo_invoice_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email_me_about_new_in_person_auctions',
            field=models.BooleanField(blank=True, default=True, help_text='When new in-person auctions are created near my location, notify me'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email_me_about_new_in_person_auctions_distance',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='miles, from your address', null=True, verbose_name='New in-person auction distance'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_me_about_new_auctions',
            field=models.BooleanField(blank=True, default=True, help_text="When new <span class='text-info'>online</span> auctions are created with pickup locations near my location, notify me"),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_me_about_new_auctions_distance',
            field=models.PositiveIntegerField(blank=True, default=100, help_text='miles, from your address', null=True, verbose_name='New online auction distance'),
        ),
    ]
