# Generated by Django 4.0.3 on 2023-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0111_userdata_email_me_about_new_in_person_auctions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotAutoCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auctions.lot',),
        ),
        migrations.AddField(
            model_name='lot',
            name='category_checked',
            field=models.BooleanField(default=False),
        ),
    ]
