# Generated by Django 4.1.7 on 2023-03-14 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0112_lotautocategory_lot_category_checked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctiontos',
            options={'verbose_name': 'User in auction', 'verbose_name_plural': 'Users in auction'},
        ),
        migrations.AddField(
            model_name='userlabelprefs',
            name='empty_labels',
            field=models.IntegerField(default=0, help_text='To print on partially used label sheets, skip this many blank labels.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userlabelprefs',
            name='preset',
            field=models.CharField(choices=[('lg', 'Small (Avery 5160)'), ('sm', 'Large (Avery 18262)'), ('custom', 'Custom')], default='lg', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlabelprefs',
            name='label_height',
            field=models.FloatField(default=0.98, validators=[django.core.validators.MinValueValidator(0.4), django.core.validators.MaxValueValidator(50.0)]),
        ),
    ]
