# Generated by Django 4.1.7 on 2023-03-14 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0113_alter_auctiontos_options_userlabelprefs_empty_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlabelprefs',
            name='empty_labels',
            field=models.IntegerField(default=0, help_text='To print on partially used label sheets, print this many blank labels before printing the actual labels.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userlabelprefs',
            name='label_margin_right',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='userlabelprefs',
            name='page_margin_right',
            field=models.FloatField(default=0.18, validators=[django.core.validators.MinValueValidator(0.05)]),
        ),
        migrations.AlterField(
            model_name='userlabelprefs',
            name='preset',
            field=models.CharField(choices=[('sm', 'Small (Avery 5160)'), ('lg', 'Large (Avery 18262)'), ('custom', 'Custom')], default='lg', max_length=20),
        ),
    ]
