# Generated by Django 4.1.7 on 2023-03-25 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0114_alter_userlabelprefs_empty_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='only_approved_sellers',
            field=models.BooleanField(default=False, help_text='Require admin approval before users can add lots'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='auctiontos_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctiontos', to='auctions.auctiontos'),
        ),
        migrations.AlterField(
            model_name='userlabelprefs',
            name='empty_labels',
            field=models.IntegerField(default=0, help_text='To print on partially used label sheets, print this many blank labels before printing the actual labels.  Just remember to set this back to 0 when starting a new sheet of labels!', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userlabelprefs',
            name='preset',
            field=models.CharField(choices=[('sm', 'Small (Avery 5160)'), ('lg', 'Large (Avery 18262)'), ('custom', 'Custom')], default='lg', max_length=20, verbose_name='Label size'),
        ),
    ]
