# Generated by Django 4.1.7 on 2023-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0115_auction_only_approved_sellers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
