# Generated by Django 4.2.1 on 2023-07-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0116_pageview_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='auction',
            field=models.ForeignKey(blank=True, help_text="Only filled out when a user views an auction's rules page", null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='pageview',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageview',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pageview',
            name='referrer',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='session_id',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='title',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='lot_number',
            field=models.ForeignKey(blank=True, help_text="Only filled out when a user views a specific lot's page", null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.lot'),
        ),
    ]
