# Generated by Django 4.2.1 on 2023-07-20 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0119_alter_lot_reference_link_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='duplicate_check_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='date_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
