# Generated by Django 4.2.1 on 2023-07-31 15:37

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0121_alter_pageview_duplicate_check_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_start',
            field=models.DateTimeField(help_text='Bidding starts on this date', verbose_name='Auction start date'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='allow_bidding_by_default',
            field=models.BooleanField(default=True, help_text='This is not used'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='allow_selling_by_default',
            field=models.BooleanField(default=True, help_text='This is not used'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='Only users that you have granted admin permissions to will show up here.  Their phone and email will be shown to users who select this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auctiontos'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='description',
            field=models.CharField(blank=True, help_text="Notes, shipping charges, etc.  For example: 'Parking lot near Sears entrance'", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='location_coordinates',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Location name shown to users.  e.x. University Mall in VT', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='second_pickup_time',
            field=models.DateTimeField(blank=True, help_text="Only for <a href='/blog/multiple-location-auctions/'>multi-location auctions</a>; people will return to pick up lots from other locations at this time.", null=True),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='users_must_coordinate_pickup',
            field=models.BooleanField(default=False, help_text='You probably want this unchecked, to have everyone arrive at the same time.'),
        ),
    ]
