# Generated by Django 4.2.1 on 2023-07-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0122_alter_auction_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pageview',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pageview',
            name='user_agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
