# Generated by Django 4.2.1 on 2023-11-07 14:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0123_pageview_ip_address_pageview_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='invoice_payment_instructions',
            field=models.CharField(blank=True, default='', help_text="Shown to the user on their invoice.  For example, 'You will receive a seperate PayPal invoice with payment instructions'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='minimum_bid',
            field=models.PositiveIntegerField(default=2, help_text='Lowest price a lot can sell for.', validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='pageview',
            name='os',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('ANDROID', 'Android'), ('IPHONE', 'iPhone'), ('WINDOWS', 'Windows'), ('OSX', 'OS X')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='pageview',
            name='platform',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MOBILE', 'Phone'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='show_email_warning_sent',
            field=models.BooleanField(blank=True, default=False, help_text='When a user has their email address hidden and sells a lot, this is checked'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='username_is_email_warning_sent',
            field=models.BooleanField(blank=True, default=False, help_text='Warning email has been sent because this user made their username an email'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='username_visible',
            field=models.BooleanField(blank=True, default=True, help_text='Uncheck to bid anonymously.'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_end',
            field=models.DateTimeField(blank=True, help_text='Bidding will end on this date.  If last-minute bids are placed, bidding can go up to 1 hour past this time on those lots.  Note: This will not change the end date of existing lots.', null=True, verbose_name='Bidding end date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='only_approved_sellers',
            field=models.BooleanField(default=False, help_text='Require admin approval before users can add lots.  This will not change permissions for users that have already joined.'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_visible',
            field=models.BooleanField(default=False, help_text="Show your email address on your user page.  This will be visible only to logged in users.  <a href='/blog/privacy/' target='_blank'>Privacy information</a>"),
        ),
        migrations.CreateModel(
            name='AuctionCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('NONE', 'No response'), ('VIEWED', 'Clicked'), ('JOINED', 'Joined')], default='NONE', max_length=20)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
