# Generated by Django 4.2.1 on 2023-11-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0127_auction_lot_entry_fee_for_club_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='send_reminder_emails_about_joining_auctions',
            field=models.BooleanField(blank=True, default=True, help_text="Get an annoying reminder email when you view an auction but don't join it."),
        ),
        migrations.AlterField(
            model_name='auctioncampaign',
            name='result',
            field=models.CharField(choices=[('ERR', 'No email sent'), ('NONE', 'No response'), ('VIEWED', 'Clicked'), ('JOINED', 'Joined')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='auctiontos',
            name='is_club_member',
            field=models.BooleanField(blank=True, default=False, help_text='Check to use the alternative split for this auction', verbose_name='Club member'),
        ),
    ]
