# Generated by Django 4.2.1 on 2024-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0128_userdata_send_reminder_emails_about_joining_auctions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='require_phone_number',
            field=models.BooleanField(default=False, help_text='Require users to have entered a phone number before they can join this auction'),
        ),
        migrations.AddField(
            model_name='auction',
            name='set_lot_winners_url',
            field=models.CharField(blank=True, choices=[('', 'Standard, bidder number/lot number only'), ('presentation', 'Show a picture of the lot'), ('autocomplete', 'Autocomplete, search by name or bidder number')], default='presentation', max_length=20),
        ),
        migrations.AlterField(
            model_name='auctiontos',
            name='is_club_member',
            field=models.BooleanField(blank=True, default=False, verbose_name='Club member'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email_me_about_new_auctions',
            field=models.BooleanField(blank=True, default=True, help_text='When new online auctions are created with pickup locations near my location, notify me', verbose_name='Email me about new online auctions'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='send_reminder_emails_about_joining_auctions',
            field=models.BooleanField(blank=True, default=True, help_text="Get an annoying reminder email when you view an auction but don't join it"),
        ),
    ]
