# Generated by Django 5.0.3 on 2024-04-25 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0129_auction_require_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='buy_now',
            field=models.CharField(blank=True, choices=[('disable', "Don't allow"), ('allow', 'Allow'), ('required', 'Required for all lots')], default='allow', help_text='Allow lots to be sold without bidding, for a user-specified price', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='reserve_price',
            field=models.CharField(blank=True, choices=[('disable', "Don't allow"), ('allow', 'Allow'), ('required', 'Required for all lots')], default='allow', help_text='Allow users to set a minimum bid on their lots', max_length=20),
        ),
        migrations.AddField(
            model_name='lot',
            name='label_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email_me_about_new_chat_replies',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='reference_link',
            field=models.URLField(blank=True, help_text='A URL with additional information about this lot.  YouTube videos will be automatically embedded.', null=True),
        ),
        migrations.CreateModel(
            name='ChatSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('last_notificaiton_sent', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.lot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
