# Generated by Django 5.0.3 on 2024-04-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0130_auction_buy_now_auction_reserve_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='buy_now',
            field=models.CharField(choices=[('disable', "Don't allow"), ('allow', 'Allow'), ('required', 'Required for all lots')], default='allow', help_text='Allow lots to be sold without bidding, for a user-specified price', max_length=20),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=models.CharField(choices=[('disable', "Don't allow"), ('allow', 'Allow'), ('required', 'Required for all lots')], default='allow', help_text='Allow users to set a minimum bid on their lots', max_length=20),
        ),
    ]
