# Generated by Django 5.0.3 on 2024-05-02 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0132_rename_last_notificaiton_sent_chatsubscription_last_notification_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('adjustment_type', models.CharField(choices=[('ADD', 'Charge extra'), ('DISCOUNT', 'Discount'), ('ADD_PERCENT', 'Charge extra percent'), ('DISCOUNT_PERCENT', 'Discount percent')], default='ADD', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(default='Corrected', max_length=150)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.invoice')),
                ('user', models.ForeignKey(blank=True, help_text='The auction admin who created this adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
