# Generated by Django 5.0.8 on 2024-08-17 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0139_alter_auction_buy_now_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='advanced_lot_adding',
            field=models.BooleanField(default=False, help_text='Show lot number, quantity and description fields when bulk adding lots'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='buy_now',
            field=models.CharField(choices=[('disable', "Don't allow"), ('allow', 'Allow'), ('required', 'Required for all lots'), ('forced', 'Required, and disable bidding')], default='allow', help_text="Allow lots to be sold without bidding, for a user-specified price.  If required with bidding disabled, people will only buy now and won't be able to bid against each other.", max_length=20),
        ),
        migrations.AlterField(
            model_name='auction',
            name='minimum_bid',
            field=models.PositiveIntegerField(default=2, help_text='Lowest price any lot will be sold for', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='only_approved_bidders',
            field=models.BooleanField(default=False, help_text='Require admin approval before users can bid.  This only applies to new users: Users that you manually add and users who have a paid invoice in a past auctions will be allowed to bid.'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=models.CharField(choices=[('disable', "Don't allow"), ('allow', 'Allow'), ('required', 'Required for all lots')], default='allow', help_text='Allow users to set a minimum bid on their lots', max_length=20, verbose_name='Seller set minimum bid'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='reserve_price',
            field=models.PositiveIntegerField(default=2, help_text='Also called a reserve price. Lot will not be sold unless someone bids at least this much', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)], verbose_name='Minimum bid'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='address',
            field=models.CharField(blank=True, help_text="Enter an address to search the map below.  What you enter here won't be shown to users.", max_length=500, null=True),
        ),
    ]
