# Generated by Django 5.0.8 on 2024-08-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0140_auction_advanced_lot_adding_alter_auction_buy_now_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiontos',
            name='email_address_status',
            field=models.CharField(blank=True, choices=[('BAD', 'Invalid'), ('UNKNOWN', 'Unknown'), ('VALID', 'Verified')], default='UNKNOWN', max_length=20),
        ),
    ]
