# Generated by Django 5.0.8 on 2024-09-07 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0143_auction_extra_promo_link_auction_extra_promo_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="date_online_bidding_ends",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Online bidding ends"),
        ),
        migrations.AddField(
            model_name="auction",
            name="date_online_bidding_starts",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Online bidding opens"),
        ),
        migrations.AddField(
            model_name="lot",
            name="max_bid_revealed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="max_bid_revealed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="date_end",
            field=models.DateTimeField(
                blank=True,
                help_text="Bidding will end on this date.  If last-minute bids are placed, bidding can go up to 1 hour past this time on those lots.",
                null=True,
                verbose_name="Bidding end date",
            ),
        ),
    ]
