# Generated by Django 5.0.8 on 2024-09-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0145_auction_allow_deleting_bids_bid_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="auto_add_images",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Images taken from older lots with the same name",
                verbose_name="Automatically add images to lots",
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="auto_add_images",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="If another lot with the same name has been added previously",
                verbose_name="Automatically add images to my lots",
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="share_lot_images",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Images will be added to other lots without an image that have the same name",
                verbose_name="Allow my lot images to be used on other lots",
            ),
        ),
    ]
