# Generated by Django 5.0.8 on 2024-09-13 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0146_auction_auto_add_images_userdata_auto_add_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="message_users_when_lots_sell",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="When you enter a lot number on the set lot winners screen, send a notification to any users watching that lot",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="auto_add_images",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Images taken from older lots with the same name in any auctions created by you or other admins",
                verbose_name="Automatically add images to lots",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="buy_now_price",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="This lot will be sold with no bidding for this price, if someone is willing to pay this much",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="auto_add_images",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="If another lot with the same name has been added previously.  Images are only added to lots that are part of an auction.",
                verbose_name="Automatically add images to my lots",
            ),
        ),
    ]
