# Generated by Django 5.1 on 2024-09-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0148_userdata_push_notifications_when_lots_sell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="email_me_when_people_comment_on_my_lots",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Notifications will be sent once a day, only for messages you haven't seen.  If you'd like to get a notification right away, <a href='https://github.com/iragm/fishauctions/issues/224'>leave a comment here</a>",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="push_notifications_when_lots_sell",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="For in-person auctions, get a notification when bidding starts on a lot that you've watched<span class='d-none' id='subscribe_message_area'></span>",
            ),
        ),
    ]
