# Generated by Django 5.1 on 2024-10-07 12:56

from django.db import migrations, models


def copy_description(apps, schema_editor):
    Lot = apps.get_model("auctions", "Lot")
    for lot in Lot.objects.all():
        lot.summernote_description = lot.description_rendered[:10000] or ""
        lot.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0151_lot_summernote_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="summernote_description",
            field=models.CharField(blank=True, default="", max_length=10000, verbose_name="Description"),
        ),
        migrations.RunPython(copy_description),
    ]
