# Generated by Django 5.1 on 2024-10-07 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0153_auction_summernote_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="notes_rendered",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="description",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="description_rendered",
        ),
    ]
