# Generated by Django 5.1 on 2024-10-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0154_remove_auction_notes_remove_auction_notes_rendered_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="label_print_fields",
            field=models.CharField(
                blank=True,
                default="lot_name,min_bid_label,buy_now_label,quantity_label,seller_name_label,donation_label",
                max_length=1000,
                null=True,
            ),
        ),
    ]
