# Generated by Django 5.1 on 2024-10-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0155_auction_label_print_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_on_label",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="auction",
            name="label_print_fields",
            field=models.CharField(
                blank=True,
                default="qr_code,lot_name,min_bid_label,buy_now_label,quantity_label,seller_name,donation_label",
                max_length=1000,
                null=True,
            ),
        ),
    ]
