# Generated by Django 5.1.1 on 2024-10-18 01:08

from django.db import migrations, models


def migrate_buy_now_to_online_bidding(apps, schema_editor):
    Auction = apps.get_model("auctions", "Auction")
    auctions = Auction.objects.filter(buy_now="forced")
    auctions.update(online_bidding="buy_now_only")


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0158_alter_pickuplocation_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="online_bidding",
            field=models.CharField(
                blank=True,
                choices=[
                    ("allow", "Allow buy now and bidding"),
                    ("buy_now_only", "Allow buy now only"),
                    ("disable", "No online bidding"),
                ],
                default="allow",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="label_needs_reprinting",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_buy_now_to_online_bidding),
    ]
