# Generated by Django 5.1.1 on 2024-10-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0159_auction_online_bidding_lot_label_needs_reprinting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="allow_bidding_on_lots",
        ),
        migrations.AddField(
            model_name="auction",
            name="reprint_reminder_sent",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="buy_now",
            field=models.CharField(
                choices=[("disable", "Don't allow"), ("allow", "Allow"), ("required", "Required for all lots")],
                default="allow",
                help_text="Allow lots to be sold without bidding, for a user-specified price.  If required with bidding disabled, people will only buy now and won't be able to bid against each other.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="online_bidding",
            field=models.CharField(
                choices=[
                    ("allow", "Allow buy now and bidding"),
                    ("buy_now_only", "Allow buy now only"),
                    ("disable", "No online bidding"),
                ],
                default="allow",
                max_length=20,
            ),
        ),
    ]
