# Generated by Django 5.1.1 on 2024-10-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0160_remove_auction_allow_bidding_on_lots_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="reprint_reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
