# Generated by Django 5.1.1 on 2024-11-14 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0163_alter_auction_summernote_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="force_donation_threshold",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Most auctions should leave this blank.  Force lots to be a donation if they sell for this amount or less.",
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
                verbose_name="Donation threshold",
            ),
        ),
    ]
