# Generated by Django 5.1.1 on 2024-11-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0164_auction_force_donation_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="summernote_description",
            field=models.TextField(blank=True, default="", verbose_name="Rules"),
        ),
        migrations.AlterField(
            model_name="lot",
            name="summernote_description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
    ]
