# Generated by Django 5.1.1 on 2025-02-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0165_alter_auction_summernote_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="use_seller_dash_lot_numbering",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="lot_number_int",
            field=models.IntegerField(blank=True, null=True, verbose_name="Lot number"),
        ),
    ]
