# Generated by Django 5.1.1 on 2025-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0166_auction_use_seller_dash_lot_numbering_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="use_seller_dash_lot_numbering",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
