# Generated by Django 5.1.1 on 2025-02-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0167_alter_auction_use_seller_dash_lot_numbering"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="allow_bulk_adding_lots",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to force users to add lots one at a time to encourage use of descriptions and pictures.",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="copy_users_when_copying_this_auction",
            field=models.BooleanField(default=False, help_text="Save yourself a few clicks when bulk importing users"),
        ),
        migrations.AddField(
            model_name="auction",
            name="custom_checkbox_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shown when users add lots.  Leave blank to disable",
                max_length=50,
                null=True,
                verbose_name="Custom checkbox name",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="custom_field_1_name",
            field=models.CharField(
                blank=True,
                default="Notes",
                help_text="What's the custom field used for?  This is shown to users",
                max_length=50,
                null=True,
                verbose_name="Custom field name",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="use_cares_field",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="auction",
            name="use_quantity_field",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="custom_checkbox",
            field=models.BooleanField(default=False, verbose_name="Custom checkbox"),
        ),
        migrations.AddField(
            model_name="lot",
            name="custom_field_1",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
