# Generated by Django 5.1.1 on 2025-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0170_auction_use_donation_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="message_users_when_lots_sell",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Recommended if you are recording winners as lots sell.  When you enter a lot number on the set lot winners screen, send a notification to any users watching that lot",
            ),
        ),
    ]
