# Generated by Django 5.1.1 on 2025-03-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0171_alter_auction_message_users_when_lots_sell"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auction",
            old_name="use_cares_field",
            new_name="use_custom_checkbox_field",
        ),
        migrations.AlterField(
            model_name="auction",
            name="allow_bulk_adding_lots",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to force users to add lots one at a time.  This encourage more detail and pictures about each lot.",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="use_i_bred_this_fish_field",
            field=models.BooleanField(blank=True, default=True, verbose_name="Use Breeder Points field"),
        ),
    ]
