# Generated by Django 5.1.1 on 2025-03-02 18:56

from django.db import migrations, models


def update_reference_links(apps, schema_editor):
    Lot = apps.get_model("auctions", "Lot")
    for lot in Lot.objects.filter(reference_link__contains=" "):
        lot.reference_link = lot.reference_link.replace(" ", "%20")
        lot.save()


def update_label_print_fields(apps, schema_editor):
    Auction = apps.get_model("auctions", "Auction")
    suffix = ",custom_field_1,i_bred_this_fish_label,custom_checkbox_label"
    for auction in Auction.objects.all():
        if auction.label_print_fields:
            if suffix not in auction.label_print_fields:
                auction.label_print_fields += suffix
        else:
            auction.label_print_fields = suffix.lstrip(",")
        auction.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0173_auction_use_description_auction_use_reference_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="allow_bulk_adding_lots",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to force users to add lots one at a time.  Turning this off encourages more detail and pictures about each lot, but makes adding lots take longer. Admins can always bulk add lots for other users.",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="label_print_fields",
            field=models.CharField(
                blank=True,
                default="qr_code,lot_name,min_bid_label,buy_now_label,quantity_label,seller_name,donation_label,custom_field_1,i_bred_this_fish_label,custom_checkbox_label",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="use_categories",
            field=models.BooleanField(
                default=True,
                help_text="Not shown on the bulk add lots form.  Check to use categories like Cichlids, Livebearers, etc.  This option is required if you want to promote your auction on the main auctions list.",
                verbose_name="Use category field",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="use_custom_checkbox_field",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Optional information such as CARES, native species, difficult to keep, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="lot_name",
            field=models.CharField(max_length=40),
        ),
        migrations.RunPython(update_reference_links),
        migrations.RunPython(update_label_print_fields),
    ]
