# Generated by Django 5.1.1 on 2025-03-06 15:30

from django.db import migrations, models

import auctions.models


def create_or_update_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("post_office", "EmailTemplate")

    templates = [
        {"name": "auction_first", "subject": "foo", "content": "bar", "html_content": "html"},
    ]

    for template in templates:
        EmailTemplate.objects.update_or_create(
            name=template["name"],
            defaults={
                "subject": template["subject"],
                "content": template["content"],
                "html_content": template["html_content"],
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0174_alter_auction_allow_bulk_adding_lots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="can_create_club_auctions",
            field=models.BooleanField(default=auctions.models.get_default_can_create_auctions),
        ),
        migrations.AlterField(
            model_name="auction",
            name="allow_bulk_adding_lots",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to force users to add lots one at a time.  Turning this off encourage more detail and pictures about each lot, but makes adding lots take longer. Admins can always bulk add lots for other users.",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="can_submit_standalone_lots",
            field=models.BooleanField(default=auctions.models.get_default_can_submit_lots),
        ),
        migrations.RunPython(create_or_update_email_templates),
    ]
