# Generated by Django 5.1.6 on 2025-03-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0175_userdata_can_create_club_auctions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="admin_validated",
            field=models.BooleanField(default=False),
        ),
    ]
