# Generated by Django 5.1.6 on 2025-03-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0176_lot_admin_validated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageview",
            name="date_start",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="session_id",
            field=models.CharField(blank=True, db_index=True, max_length=600, null=True),
        ),
    ]
