# Generated by Django 5.1.6 on 2025-03-21 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0178_create_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctiontos",
            name="possible_duplicate",
            field=models.ForeignKey(
                blank=True,
                help_text="There's a chance this user is a duplicate if this is set",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate",
                to="auctions.auctiontos",
            ),
        ),
    ]
