# Generated by Django 5.1.6 on 2025-03-27 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0179_auctiontos_possible_duplicate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="use_seller_dash_lot_numbering",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Include the seller's bidder number with the lot number.  This option is not recommended as users find it confusing.",
            ),
        ),
        migrations.AlterField(
            model_name="auctiontos",
            name="is_admin",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=False,
                verbose_name="Grant admin permissions to help run this auction",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="custom_lot_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="You can override the default lot number with this",
                max_length=9,
                null=True,
                verbose_name="Lot number",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="latitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="longitude",
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="lot_number_int",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="Lot number"),
        ),
        migrations.AlterField(
            model_name="lot",
            name="winning_price",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="date_end",
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="latitude",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="longitude",
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
