# Generated by Django 5.1.6 on 2025-04-09 15:32

from django.db import migrations


def update_invoice_ready_email(apps, schema_editor):
    EmailTemplate = apps.get_model("post_office", "EmailTemplate")

    EmailTemplate.objects.update_or_create(
        name="invoice_ready",
        defaults={
            "subject": "{{ subject }}",
            "content": """Hello {{ name }},

{{ subject }}.  {% if invoice.status == "UNPAID" %}{% if invoice.user_should_be_paid %}You will be paid{% else %}You owe a total of{% endif %} ${{ invoice.absolute_amount|floatformat:2}}{% endif %}

{% if invoice.status == "PAID" %}Your invoice has been paid in full.  Here is a list of lots you won and sold for your records.{% endif %}
https://{{domain}}/invoices/{{invoice.no_login_link}}/

{% if location %}
{% if invoice.auction.is_online %}
You must meet at {{ location }} to exchange your lots.

See you there!{% endif %}{% endif %}

{% if invoice.status == "UNPAID" and not invoice.user_should_be_paid %}{{ invoice.auction.invoice_payment_instructions | default:""}}{% endif %}

Best wishes,
{{domain}}""",
            "html_content": """Hello {{ name }},<br><br>

{{ subject }}.  {% if invoice.status == "UNPAID" %}{% if invoice.user_should_be_paid %}You will be paid{% else %}You owe a total of{% endif %} ${{ invoice.absolute_amount|floatformat:2}}{% endif %}<br><br>

{% if invoice.status == "PAID" %}Your invoice has been paid in full.  Here is a list of lots you won and sold for your records.<br>{% endif %}
<a href='https://{{domain}}/invoices/{{invoice.no_login_link}}/?src=notification'>Click here to view your invoice</a><br><br>

{% if location %}
{% if invoice.auction.is_online %}
You must meet at {{ location }} to exchange your lots.<br><br>

See you there!<br><br>{% endif %}{% endif %}

{% if invoice.status == "UNPAID" and not invoice.user_should_be_paid %}{{ invoice.auction.invoice_payment_instructions | default:""}}<br><br>{% endif %}

Best wishes,<br>
{{domain}}""",
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0182_auto_20250409_1115"),
    ]

    operations = [
        migrations.RunPython(update_invoice_ready_email),
    ]
