# Generated by Django 5.1.6 on 2025-04-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0183_auto_20250409_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="message_users_when_lots_sell",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Recommended if you are recording winners as lots sell.  When you enter a lot number on the set lot winners screen, send a notification to any users watching that lot",
                verbose_name="Allow push notifications for watched lots",
            ),
        ),
        migrations.AlterField(
            model_name="auctiontos",
            name="bidder_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Must be unique, blank to automatically generate",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auctiontos",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="auctiontos",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=181, null=True),
        ),
    ]
