# Generated by Django 5.1.6 on 2025-05-03 23:58

from django.db import migrations, models


def resave_all_auction_tos(apps, schema_editor):
    AuctionTOS = apps.get_model("auctions", "AuctionTOS")
    for tos in AuctionTOS.objects.all():
        tos.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0184_alter_auction_message_users_when_lots_sell_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="promote_this_auction",
            field=models.BooleanField(default=True, help_text="Show this to everyone in the list of auctions"),
        ),
        migrations.AlterField(
            model_name="auctioncampaign",
            name="result",
            field=models.CharField(
                choices=[
                    ("ERR", "No email sent"),
                    ("NONE", "No response"),
                    ("VIEWED", "Clicked"),
                    ("JOINED", "Joined"),
                ],
                db_index=True,
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pageview",
            name="source",
            field=models.CharField(blank=True, db_index=True, default="", max_length=200, null=True),
        ),
        migrations.RunPython(resave_all_auction_tos),
    ]
