# Generated by Django 5.2.1 on 2025-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0185_alter_auction_promote_this_auction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlabelprefs",
            name="preset",
            field=models.CharField(
                choices=[
                    ("sm", "Small (Avery 5160) (Not recommended)"),
                    ("lg", "Large (Avery 18262)"),
                    ("thermal_sm", 'Thermal 3"x2"'),
                    ("thermal_very_sm", 'Thermal 1⅛" x 3½" (30252)'),
                    ("custom", "Custom"),
                ],
                default="lg",
                max_length=20,
                verbose_name="Label size",
            ),
        ),
    ]
