# Generated by Django 5.2.5 on 2025-09-25 18:25

import django.db.models.deletion
from django.db import migrations, models


def resave_lots(apps, schema_editor):
    Lot = apps.get_model("auctions", "Lot")
    for lot in Lot.objects.all():
        lot.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0187_alter_userlabelprefs_preset_auctionhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="auctiontos_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auctiontos_winner",
                to="auctions.auctiontos",
                verbose_name="Winner",
            ),
        ),
        migrations.RunPython(resave_lots, reverse_code=migrations.RunPython.noop),
    ]
