# Generated by Django 5.2.5 on 2025-10-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0188_alter_lot_auctiontos_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctiontos",
            name="add_to_calendar",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="abbreviation",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
