# Generated by Django 5.2.5 on 2025-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0189_auctiontos_add_to_calendar_alter_club_abbreviation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="alternative_split_label",
            field=models.CharField(
                default="club member",
                help_text="Label to use instead of 'club member' for users with alternate fees (appears in invoices, user tables, etc.)",
                max_length=50,
                verbose_name="Alternative split label",
            ),
        ),
    ]
