# Generated by Django 5.2.5 on 2025-10-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0189_auctiontos_add_to_calendar_alter_club_abbreviation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="paypal_email_address",
            field=models.EmailField(
                blank=True,
                help_text="To enable PayPal payments, enter the email address associated with your PayPal account",
                max_length=255,
                null=True,
            ),
        ),
    ]
