# Generated by Django 5.2.5 on 2025-10-26 15:50

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0190_auction_paypal_email_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoicePayment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "external_id",
                    models.CharField(blank=True, help_text="Provider transaction id", max_length=255, null=True),
                ),
                ("payer_name", models.CharField(blank=True, max_length=200, null=True)),
                ("payer_email", models.CharField(blank=True, max_length=200, null=True)),
                ("payer_address", models.CharField(blank=True, max_length=500, null=True)),
                ("memo", models.CharField(blank=True, max_length=500, null=True)),
                ("payment_method", models.CharField(blank=True, default="PayPal", max_length=50, null=True)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="auctions.invoice"
                    ),
                ),
            ],
        ),
    ]
