# Generated by Django 5.2.7 on 2025-10-27 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0191_invoicepayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="paypal_enabled",
            field=models.BooleanField(default=auctions.models.get_default_paypal_enabled),
        ),
        migrations.CreateModel(
            name="PayPalSeller",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("paypal_user_id", models.CharField(max_length=255, unique=True)),
                ("paypal_merchant_id", models.CharField(blank=True, max_length=64, null=True)),
                ("paypal_merchant_id_in_paypal", models.CharField(blank=True, max_length=64, null=True)),
                ("payer_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("connected_on", models.DateTimeField(auto_now_add=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
