# Generated by Django 5.2.7 on 2025-10-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0192_userdata_paypal_enabled_paypalseller"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="dismissed_paypal_banner",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="auction",
            name="dismissed_promo_banner",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="auction",
            name="enable_online_payments",
            field=models.BooleanField(
                blank=True, default=False, help_text="Allow users to use PayPal to pay their invoices themselves"
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="never_show_paypal_connect",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="auction",
            name="paypal_email_address",
            field=models.EmailField(
                blank=True,
                help_text="Not currently used, this is configured in the model PayPalSeller",
                max_length=255,
                null=True,
            ),
        ),
    ]
