# Generated by Django 5.2.7 on 2025-10-29 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0193_auction_dismissed_paypal_banner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paypalseller",
            name="paypal_merchant_id_in_paypal",
        ),
        migrations.RemoveField(
            model_name="paypalseller",
            name="paypal_user_id",
        ),
        migrations.RemoveField(
            model_name="paypalseller",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="paypalseller",
            name="token_expires_at",
        ),
    ]
