# Generated by Django 5.2.7 on 2025-10-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0194_remove_paypalseller_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypalseller",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
    ]
