# Generated by Django 5.2.7 on 2025-10-31 19:02

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0195_paypalseller_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicepayment",
            name="amount_available_to_refund",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AlterField(
            model_name="auction",
            name="enable_online_payments",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Allow users to use PayPal to pay their invoices themselves.",
                verbose_name="PayPal payments",
            ),
        ),
    ]
