# Generated by Django 5.2.7 on 2025-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0196_invoicepayment_amount_available_to_refund_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceadjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[("ADD", "Charge extra"), ("DISCOUNT", "Discount")], default="ADD", max_length=20
            ),
        ),
    ]
