# Generated by Django 5.2.7 on 2025-11-04 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0190_auction_alternative_split_label"),
        ("auctions", "0197_alter_invoiceadjustment_adjustment_type"),
    ]

    operations = []
