# Generated by Django 5.2.7 on 2025-11-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0198_merge_20251104_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="memo",
            field=models.CharField(blank=True, default="", help_text="Only auction admins can see this", max_length=500, null=True),
        ),
    ]
