# Generated by Django 5.0.6 on 2025-11-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0198_merge_20251104_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="weekly_promo_emails_sent",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this auction was included in weekly promotional emails",
            ),
        ),
    ]
