# Generated by Django 5.0.6 on 2025-11-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0199_auction_weekly_promo_emails_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="google_drive_link",
            field=models.URLField(
                blank=True,
                help_text="Link to a Google Sheet with user information.  Make sure the sheet is shared with 'anyone with the link can view'.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="last_sync_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time user data was synchronized from Google Drive",
                null=True,
            ),
        ),
    ]
