# Generated by Django 5.0.6 on 2025-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0200_auction_google_drive_link_auction_last_sync_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="distance_unit",
            field=models.CharField(
                blank=True,
                choices=[("mi", "Miles"), ("km", "Kilometers")],
                default="mi",
                help_text="Unit for displaying distances",
                max_length=10,
                verbose_name="Distance unit",
            ),
        ),
    ]
