# Generated by Django 5.0.6 on 2025-11-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0201_set_distance_unit_for_canadian_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="distance_unit",
            field=models.CharField(
                choices=[("mi", "Miles"), ("km", "Kilometers")],
                default="mi",
                help_text="Unit for displaying distances",
                max_length=10,
                verbose_name="Distance unit",
            ),
        ),
    ]
