# Generated by Django 5.0.6 on 2025-11-08 17:45

from django.db import migrations, models


def set_existing_users_trusted(apps, schema_editor):
    """Set all existing users to trusted"""
    UserData = apps.get_model("auctions", "UserData")
    UserData.objects.all().update(is_trusted=True)


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0203_alter_userdata_distance_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="is_trusted",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_existing_users_trusted, migrations.RunPython.noop),
    ]
