# Generated by Django 5.2.8 on 2025-11-10 16:58

import django.core.validators
from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0204_userdata_is_trusted"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="cached_stats",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Cached auction statistics data to avoid recalculating on every page load",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="last_stats_update",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of when auction statistics were last calculated", null=True
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="next_update_due",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp for when the next statistics update should be run", null=True
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="alternative_split_label",
            field=models.CharField(
                default="Alternate fees",
                help_text="Label used for people getting alternate fees.  For example, club member, vendor, etc.",
                max_length=50,
                verbose_name="Alternate split label",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="google_drive_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link to a Google Sheet with user information.  Make sure the sheet is shared with 'anyone with the link can view'.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="lot_entry_fee_for_club_members",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Used instead of the standard entry fee, when you mark someone as using alternative fees",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="winning_bid_percent_to_club_for_club_members",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Used instead of the standard split, when you mark someone as using alternative fees",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="is_trusted",
            field=models.BooleanField(
                default=auctions.models.get_default_is_trusted,
                help_text="Trusted users can promote auctions, accept payments, and send invoice notification emails",
            ),
        ),
    ]
