# Generated by Django 5.2.8 on 2025-11-15 16:22

import auctions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0205_auction_cached_stats_auction_last_stats_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='dismissed_square_banner',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='enable_square_payments',
            field=models.BooleanField(blank=True, default=False, help_text='Allow users to use Square to pay their invoices themselves.', verbose_name='Square payments'),
        ),
        migrations.AddField(
            model_name='auction',
            name='square_email_address',
            field=models.EmailField(blank=True, help_text='Not currently used, this is configured in the model SquareSeller', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='never_show_square_connect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='square_enabled',
            field=models.BooleanField(default=auctions.models.get_default_square_enabled),
        ),
        migrations.CreateModel(
            name='SquareSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_merchant_id', models.CharField(blank=True, max_length=64, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('connected_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
