# Generated by Django 5.0.6 on 2025-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0205_auction_cached_stats_auction_last_stats_update_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="preferred_currency",
            field=models.CharField(
                choices=[("USD", "US Dollar ($)"), ("CAD", "Canadian Dollar ($)"), ("GBP", "British Pound (£)")],
                default="USD",
                help_text="Currency to display for prices",
                max_length=10,
                verbose_name="Preferred currency",
            ),
        ),
    ]
