# Generated by Django 5.0.6 on 2025-11-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0206_userdata_preferred_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="preferred_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("CAD", "Canadian Dollar ($)"),
                    ("GBP", "British Pound (£)"),
                    ("EUR", "Euro (€)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("AUD", "Australian Dollar ($)"),
                    ("CHF", "Swiss Franc (CHF)"),
                    ("CNY", "Chinese Yuan (¥)"),
                ],
                default="USD",
                help_text="Currency to display for prices",
                max_length=10,
                verbose_name="Preferred currency",
            ),
        ),
    ]
