# Generated by Django 5.2.8 on 2025-11-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0206_auction_dismissed_square_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squareseller',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='squareseller',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='squareseller',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
