# Generated by Django 5.2.8 on 2025-11-23 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0207_alter_userdata_preferred_currency"),
        ("auctions", "0209_add_no_more_refunds_field"),
    ]

    operations = []
