# Generated by Django 5.2.8 on 2025-11-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0215_alter_auction_email_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_notification_due",
            field=models.DateTimeField(
                blank=True,
                help_text="When set, a celery task will send an invoice notification email after this time",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="preferred_currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("CAD", "Canadian Dollar ($)"),
                    ("GBP", "British Pound (£)"),
                    ("EUR", "Euro (€)"),
                    ("JPY", "Japanese Yen (¥)"),
                    ("AUD", "Australian Dollar ($)"),
                    ("CHF", "Swiss Franc (CHF)"),
                    ("CNY", "Chinese Yuan (¥)"),
                ],
                default="USD",
                help_text="This currency will be used in any auctions you create",
                max_length=10,
                verbose_name="Preferred currency",
            ),
        ),
    ]
