# Generated by Django 5.2.10 on 2026-01-15 21:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0219_update_privacy_blog_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='next_update_due',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Timestamp for when the next statistics update should be run', null=True),
        ),
        migrations.CreateModel(
            name='SquareCustomerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_customer_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text="Square customer ID for this buyer under the seller's account", null=True)),
                ('square_card_id', encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Square card ID (payment method token) for saved card', null=True)),
                ('card_last_4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('card_exp_month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('card_exp_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2020)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card is currently active and can be used for payments')),
                ('square_seller', models.ForeignKey(help_text="The seller's Square account where this customer is registered", on_delete=django.db.models.deletion.CASCADE, related_name='customer_cards', to='auctions.squareseller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Square Customer Card',
                'verbose_name_plural': 'Square Customer Cards',
                'indexes': [models.Index(fields=['user', 'square_seller'], name='auctions_sq_user_id_6aaec6_idx'), models.Index(fields=['square_customer_id'], name='auctions_sq_square__9ff942_idx'), models.Index(fields=['is_active'], name='auctions_sq_is_acti_254df9_idx')],
                'unique_together': {('user', 'square_seller')},
            },
        ),
    ]
