# Generated by Django 5.2.11 on 2026-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0220_alter_auction_next_update_due_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="next_promo_email_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
