# Generated by Django 5.2.11 on 2026-02-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0221_userdata_next_promo_email_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="last_promo_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
