# Generated by Django 5.2.11 on 2026-02-21 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0222_userdata_last_promo_email_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="next_promo_email_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
