# Generated by Django 5.2.11 on 2026-02-25 21:59

import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0223_auctiontos_unique_auction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="If filled out, an image will be added to this lot using this URL when saving",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="use_images_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Images are managed from this lot",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_source_for",
                to="auctions.lot",
            ),
        ),
        migrations.AddField(
            model_name="lotimage",
            name="url",
            field=models.URLField(
                blank=True, help_text="Or enter a URL to an image instead of uploading one", null=True
            ),
        ),
        migrations.AlterField(
            model_name="lotimage",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, help_text="Select an image to upload", null=True, upload_to="images/"
            ),
        ),
    ]
