# Generated by Django 5.2.12 on 2026-03-23 17:11

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0226_lot_slug_always_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="only_whole_dollar_bids",
            field=models.BooleanField(
                default=True,
                help_text="Require bids, minimum bids, and lot prices to be whole dollar amounts.  Uncheck to allow bids with cents (e.g. $5.50).",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="minimum_bid",
            field=models.DecimalField(
                decimal_places=2,
                default=2,
                help_text="Lowest price any lot will be sold for",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))]
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="buy_now_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="This lot will be sold with no bidding for this price, if someone is willing to pay this much",
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="reserve_price",
            field=models.DecimalField(
                decimal_places=2,
                default=2,
                help_text="Also called a reserve price. Lot will not be sold unless someone bids at least this much",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(2000),
                ],
                verbose_name="Minimum bid",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="winning_price",
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="lothistory",
            name="bid_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="For any kind of debugging", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lothistory",
            name="current_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price of the lot immediately AFTER this message",
                max_digits=10,
                null=True,
            ),
        ),
    ]
