# Generated by Django 5.2.12 on 2026-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0227_auction_only_whole_dollar_bids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="show_nearby_auctions",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="When your location is set, only show auctions near you on the auction list. Auctions you've joined or created are always shown.",
                verbose_name="Only show nearby auctions",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="email_me_about_new_auctions_distance",
            field=models.PositiveIntegerField(
                blank=True,
                default=100,
                help_text="miles, from your address. Also used to filter the auction list when your location is set.",
                null=True,
                verbose_name="New online auction distance",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="email_me_about_new_in_person_auctions_distance",
            field=models.PositiveIntegerField(
                blank=True,
                default=100,
                help_text="miles, from your address. Also used to filter the auction list when your location is set.",
                null=True,
                verbose_name="New in-person auction distance",
            ),
        ),
    ]
