# Generated by Django 5.2.12 on 2026-03-31 14:26

from django.db import migrations, models


def clean_duplicate_invoices(apps, schema_editor):
    """Delete duplicate Invoice records, keeping the oldest one per AuctionTOS."""
    Invoice = apps.get_model("auctions", "Invoice")
    from django.db.models import Count

    duplicate_tos_ids = (
        Invoice.objects.values("auctiontos_user_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
        .values_list("auctiontos_user_id", flat=True)
    )
    for tos_id in duplicate_tos_ids:
        invoices = Invoice.objects.filter(auctiontos_user_id=tos_id).order_by("date")
        keep_pk = invoices.first().pk
        Invoice.objects.filter(auctiontos_user_id=tos_id).exclude(pk=keep_pk).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0227_auction_only_whole_dollar_bids_and_more"),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_invoices, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(fields=("auctiontos_user",), name="unique_invoice_per_auctiontos"),
        ),
    ]
