# Generated by Django 5.2.13 on 2026-04-22 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0228_userdata_show_nearby_auctions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='use_custom_dropdown_field',
            field=models.BooleanField(blank=True, default=False, help_text='Optional dropdown shown when users add lots.'),
        ),
        migrations.AddField(
            model_name='lot',
            name='custom_dropdown',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='auction',
            name='label_print_fields',
            field=models.CharField(blank=True, default='qr_code,lot_name,min_bid_label,buy_now_label,quantity_label,seller_name,donation_label,custom_field_1,i_bred_this_fish_label,custom_checkbox_label,custom_dropdown_label', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='AuctionDropdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=15)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
