# Generated by Django 5.2.13 on 2026-04-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0229_auction_use_custom_dropdown_field_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="custom_dropdown_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shown when users add lots",
                max_length=50,
                null=True,
                verbose_name="Custom dropdown name",
            ),
        ),
    ]
