# Generated by Django 5.2.13 on 2026-04-23 16:40

from django.db import migrations, models


def set_custom_dropdown_mode(apps, schema_editor):
    Auction = apps.get_model("auctions", "Auction")
    Auction.objects.filter(use_custom_dropdown_field__in=["1", "True", "true"]).update(
        use_custom_dropdown_field="allow"
    )
    Auction.objects.filter(use_custom_dropdown_field__in=["0", "False", "false", ""]).update(
        use_custom_dropdown_field="disable"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0230_auction_custom_dropdown_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="custom_field_1",
            field=models.CharField(
                choices=[("disable", "Off"), ("allow", "Optional"), ("required", "Required for all lots")],
                default="disable",
                help_text="Additional information on the label such as notes, scientific name, collection location...",
                max_length=20,
                verbose_name="Custom text field",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="custom_field_1_name",
            field=models.CharField(
                blank=True,
                default="Notes",
                help_text="What's the custom field used for?  This is shown to users",
                max_length=50,
                null=True,
                verbose_name="Custom text field name",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="use_custom_dropdown_field",
            field=models.CharField(
                choices=[("disable", "Off"), ("allow", "Optional"), ("required", "Required for all lots")],
                default="disable",
                help_text="Dropdown shown when users add lots.",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_custom_dropdown_mode, migrations.RunPython.noop),
    ]
