# Generated by Django 5.2.13 on 2026-04-25 17:32

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0232_delete_baiduspider_pageviews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubPermission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("permission_admin", "Full admin access"),
                            ("permission_view", "View members"),
                            ("permission_export", "Export member data"),
                            ("permission_add_edit", "Add and edit members"),
                            ("permission_edit_club", "Edit club settings"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="club",
            name="allow_integrated_payments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="club",
            name="allow_joining",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="club",
            name="discord_server_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="membership_annual_fee",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="membership_system",
            field=models.CharField(
                choices=[("january_first", "January 1st renewal"), ("rolling", "Rolling annual membership")],
                default="january_first",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_clubs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="slug",
            field=autoslug.fields.AutoSlugField(default="", editable=False, populate_from="name", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userdata",
            name="email_me_about_new_auctions_distance",
            field=models.PositiveIntegerField(
                blank=True,
                default=100,
                help_text="miles, from your address. Also used to filter the auction list when your location is set.",
                null=True,
                verbose_name="Nearby online auction distance",
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="email_me_about_new_in_person_auctions_distance",
            field=models.PositiveIntegerField(
                blank=True,
                default=100,
                help_text="miles, from your address. Also used to filter the auction list when your location is set.",
                null=True,
                verbose_name="Nearby in-person auction distance",
            ),
        ),
        migrations.CreateModel(
            name="ClubDiscordRole",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role_name", models.CharField(max_length=100)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="discord_roles", to="auctions.club"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(blank=True, max_length=800, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "applies_to",
                    models.CharField(
                        blank=True,
                        choices=[("RULES", "Rules"), ("MEMBERS", "Members"), ("SETTINGS", "Settings")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="history", to="auctions.club"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Club history",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ClubRole",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="roles", to="auctions.club"
                    ),
                ),
                ("permissions", models.ManyToManyField(blank=True, to="auctions.clubpermission")),
            ],
        ),
        migrations.CreateModel(
            name="ClubMember",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                (
                    "email_address_status",
                    models.CharField(
                        blank=True,
                        choices=[("BAD", "Invalid"), ("UNKNOWN", "Unknown"), ("VALID", "Verified")],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("memo", models.TextField(blank=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("discord_id", models.CharField(blank=True, max_length=100, null=True)),
                ("bap_points", models.PositiveIntegerField(default=0)),
                ("hap_points", models.PositiveIntegerField(default=0)),
                ("membership_last_paid", models.DateField(blank=True, null=True)),
                ("createdon", models.DateTimeField(auto_now_add=True, verbose_name="date joined")),
                ("contact", models.BooleanField(default=True)),
                ("non_essential_emails", models.BooleanField(default=True)),
                ("do_not_contact", models.BooleanField(default=False)),
                ("discord_roles", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("joined", "Joined via website"),
                            ("discord", "Added from Discord"),
                            ("manually_added", "Manually added"),
                        ],
                        default="manually_added",
                        max_length=20,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_club_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="members", to="auctions.club"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("roles", models.ManyToManyField(blank=True, to="auctions.clubrole")),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
