# Generated by Django 5.2.13 on 2026-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0233_clubpermission_club_allow_integrated_payments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubmember",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="clubmember",
            name="do_not_contact",
        ),
        migrations.RemoveField(
            model_name="clubmember",
            name="non_essential_emails",
        ),
        migrations.AddField(
            model_name="clubmember",
            name="contact_status",
            field=models.CharField(
                choices=[
                    ("contact", "Contact normally"),
                    ("non_essential", "No non-essential emails"),
                    ("do_not_contact", "Do not contact"),
                ],
                default="contact",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="clubhistory",
            name="applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RULES", "Rules"),
                    ("MEMBERS", "Members"),
                    ("MEMBERSHIP", "Membership"),
                    ("SETTINGS", "Settings"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
