# Generated by Django 5.2.13 on 2026-04-26 15:51

from django.db import migrations, models


def consolidate_club_roles(apps, schema_editor):
    """Merge per-club duplicate role names into a single global role."""
    db_alias = schema_editor.connection.alias
    ClubRole = apps.get_model("auctions", "ClubRole")
    ClubMemberRoles = apps.get_model("auctions", "ClubMember").roles.through

    seen = {}
    for role in ClubRole.objects.using(db_alias).order_by("name", "pk"):
        if role.name not in seen:
            seen[role.name] = role.pk
        else:
            canonical_pk = seen[role.name]
            for link in ClubMemberRoles.objects.using(db_alias).filter(clubrole_id=role.pk):
                ClubMemberRoles.objects.using(db_alias).get_or_create(
                    clubmember_id=link.clubmember_id,
                    clubrole_id=canonical_pk,
                )
            role.delete()


def reverse_consolidate(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0237_create_default_club_roles"),
    ]

    operations = [
        migrations.RunPython(consolidate_club_roles, reverse_consolidate),
        migrations.RemoveField(
            model_name="clubrole",
            name="club",
        ),
        migrations.AlterField(
            model_name="clubrole",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
