# Generated by Django 5.2.13 on 2026-04-26 17:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0238_make_clubrole_global"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="About this club"),
        ),
        migrations.AlterField(
            model_name="club",
            name="slug",
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from="name", unique=True),
        ),
    ]
