# Generated by Django 5.2.13 on 2026-04-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0239_club_description_alter_club_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="enable_club_page",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, this club will appear on the club map and have a public detail page.",
                verbose_name="Enable public club page",
            ),
        ),
    ]
