# Generated by Django 5.2.13 on 2026-04-29 17:33

import django.db.models.deletion
from django.db import migrations, models


def create_manage_auctions_permission_and_role(apps, schema_editor):
    ClubPermission = apps.get_model("auctions", "ClubPermission")
    ClubRole = apps.get_model("auctions", "ClubRole")

    perm, _ = ClubPermission.objects.get_or_create(
        name="permission_manage_auctions",
        defaults={"description": "Manage auctions"},
    )
    role, created = ClubRole.objects.get_or_create(name="Manage auctions")
    if created:
        role.permissions.set([perm])


def reverse_migration(apps, schema_editor):
    pass  # Don't delete on reverse - they may be in use


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0241_clubmember_possible_duplicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auctions",
                to="auctions.club",
            ),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="possible_duplicate",
            field=models.ForeignKey(
                blank=True,
                help_text="Another club member with the same last name; may be a duplicate",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_of",
                to="auctions.clubmember",
            ),
        ),
        migrations.AlterField(
            model_name="clubpermission",
            name="name",
            field=models.CharField(
                choices=[
                    ("permission_admin", "Full admin access"),
                    ("permission_view", "View members"),
                    ("permission_export", "Export member data"),
                    ("permission_add_edit", "Add and edit members"),
                    ("permission_edit_club", "Edit club settings"),
                    ("permission_manage_auctions", "Manage auctions"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.RunPython(create_manage_auctions_permission_and_role, reverse_migration),
    ]
