# Generated by Django 5.2.13 on 2026-05-04 10:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


def generate_club_uuids(apps, schema_editor):
    """Backfill UUIDs for any existing Club rows."""
    Club = apps.get_model("auctions", "Club")
    for club in Club.objects.filter(uuid=None):
        club.uuid = uuid.uuid4()
        club.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0243_clubdiscordrole_role_id_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(generate_club_uuids, migrations.RunPython.noop),
        migrations.AddField(
            model_name="clubdiscordrole",
            name="bap_points_for_role",
            field=models.PositiveIntegerField(
                default=0, help_text="Assign this role when a member reaches this many BAP points (0 = not used)"
            ),
        ),
        migrations.AddField(
            model_name="clubdiscordrole",
            name="hap_points_for_role",
            field=models.PositiveIntegerField(
                default=0, help_text="Assign this role when a member reaches this many HAP points (0 = not used)"
            ),
        ),
        migrations.AddField(
            model_name="clubdiscordrole",
            name="is_paid_role",
            field=models.BooleanField(
                default=False, help_text="Assign this role to members with a current paid membership"
            ),
        ),
        migrations.AddField(
            model_name="clubdiscordrole",
            name="is_unpaid_role",
            field=models.BooleanField(
                default=False, help_text="Assign this role to members with an expired membership"
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="discord_role_auto_managed",
            field=models.BooleanField(
                default=True,
                help_text="When checked, the Discord role is assigned automatically based on membership status and BAP/HAP points.",
                verbose_name="Automatically manage Discord role",
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="discord_role_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Only used when automatic role management is disabled.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manually_assigned_members",
                to="auctions.clubdiscordrole",
                verbose_name="Discord role (manual override)",
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="discord_username",
            field=models.CharField(blank=True, help_text="Discord username (e.g. cooluser)", max_length=100, null=True),
        ),
    ]
