# Generated by Django 5.2.13 on 2026-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0244_discord_role_fields_club_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="bap_points",
            field=models.PositiveIntegerField(
                default=5,
                help_text="BAP points awarded for a sold lot in this category. Set to 0 to make this category ineligible.",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="auto_add_points",
            field=models.BooleanField(
                default=True,
                help_text="Automatically award BAP points when a lot sells. Uncheck to require admin approval before awarding points.",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="days_between_same_name_lots",
            field=models.IntegerField(
                default=0,
                help_text="Minimum days between awarding BAP points for lots with the same name. Leave at 0 to allow points every time.",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="min_quantity",
            field=models.IntegerField(default=5, help_text="Minimum quantity in a lot to be eligible for BAP points."),
        ),
        migrations.AddField(
            model_name="club",
            name="only_active_members_can_participate",
            field=models.BooleanField(
                default=True, help_text="Only club members with an active (paid) membership can earn BAP points."
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="points_per_lot",
            field=models.IntegerField(
                default=0,
                help_text="Fixed BAP points per eligible lot. Leave at 0 to use per-category points based on difficulty.",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="separate_cap",
            field=models.BooleanField(default=False, help_text="Track Culture Award Program separately."),
        ),
        migrations.AddField(
            model_name="club",
            name="separate_hap",
            field=models.BooleanField(
                default=False, help_text="Track HAP (Horticultural Award Program) separately from BAP."
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="bap_auto_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_long_enough", "Not long enough since last submission"),
                    ("category_not_eligible", "Category not eligible (BAP points = 0)"),
                    ("not_club_member", "Not a club member"),
                    ("not_bred", "Didn't breed this fish"),
                    ("not_active_member", "Not an active club member"),
                    ("not_sold", "Not sold"),
                    ("low_quantity", "Quantity below club minimum"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="bap_points_awarded",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lot",
            name="manually_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="clubpermission",
            name="name",
            field=models.CharField(
                choices=[
                    ("permission_admin", "Full admin access"),
                    ("permission_view", "View members"),
                    ("permission_export", "Export member data"),
                    ("permission_add_edit", "Add and edit members"),
                    ("permission_edit_club", "Edit club settings"),
                    ("permission_manage_auctions", "Manage auctions"),
                    ("permission_manage_bap", "Manage BAP points"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
