# Generated by Django 5.2.13 on 2026-05-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0245_category_bap_points_club_auto_add_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="enable_breeder_award_program",
            field=models.BooleanField(
                default=False,
                help_text="Enable the Breeder Award Program (BAP) for this club. Required for BAP points to be awarded.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="only_active_members_can_participate",
            field=models.BooleanField(
                default=True, help_text="Only club members with an active (paid) membership can earn BAP points."
            ),
        ),
        migrations.AlterField(
            model_name="clubhistory",
            name="applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RULES", "Rules"),
                    ("MEMBERS", "Members"),
                    ("MEMBERSHIP", "Membership"),
                    ("SETTINGS", "Settings"),
                    ("BAP", "BAP"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="bap_auto_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_eligible", "Not eligible"),
                    ("not_long_enough", "Not long enough since last submission"),
                    ("category_not_eligible", "Category not eligible (BAP points = 0)"),
                    ("not_club_member", "Not a club member"),
                    ("not_bred", "Didn't breed this fish"),
                    ("not_active_member", "Not an active club member"),
                    ("not_sold", "Not sold"),
                    ("low_quantity", "Quantity below club minimum"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
