# Generated by Django 5.2.13 on 2026-05-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0246_club_enable_breeder_award_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="last_bap_recalculation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="next_bap_recalculation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="bap_points_ytd",
            field=models.PositiveIntegerField(default=0, help_text="BAP points earned this calendar year."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="culture_points",
            field=models.PositiveIntegerField(default=0, help_text="Culture Award Program points."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="culture_points_ytd",
            field=models.PositiveIntegerField(default=0, help_text="Culture points earned this calendar year."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="hap_points_ytd",
            field=models.PositiveIntegerField(default=0, help_text="HAP points earned this calendar year."),
        ),
        migrations.AlterField(
            model_name="club",
            name="enable_breeder_award_program",
            field=models.BooleanField(
                default=False, help_text="Track when users breed fish and show a leaderboard of top breeders."
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="only_active_members_can_participate",
            field=models.BooleanField(
                default=False, help_text="Only club members with an active (paid) membership can earn BAP points."
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="points_per_lot",
            field=models.IntegerField(
                default=0,
                help_text="Fixed BAP points per eligible lot. Leave at 0 to use pre-assigned per-category points based on difficulty.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="separate_cap",
            field=models.BooleanField(
                default=False,
                help_text="Track CAP (Culture Award Program) points separately from BAP.",
                verbose_name="Separate Live Food Culture Award Program (CAP)",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="separate_hap",
            field=models.BooleanField(
                default=False,
                help_text="Track HAP (Horticultural Award Program) points separately from BAP.",
                verbose_name="Separate Horticultural Award Program (HAP)",
            ),
        ),
    ]
