# Generated by Django 5.2.13 on 2026-05-06 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0247_club_last_bap_recalculation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmember",
            name="source",
            field=models.CharField(
                choices=[
                    ("joined", "Joined via website"),
                    ("discord", "Added from Discord"),
                    ("manually_added", "Manually added"),
                    ("api", "Added via API"),
                ],
                default="manually_added",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClubAPIKey",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Label for this integration, e.g. 'WordPress'", max_length=100)),
                ("prefix", models.CharField(db_index=True, max_length=12, unique=True)),
                ("key_hash", models.CharField(db_index=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rate_limit",
                    models.IntegerField(
                        blank=True, help_text="Max requests per hour. Blank = site default.", null=True
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="api_keys", to="auctions.club"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubAPIKeyFieldMap",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_field", models.CharField(max_length=100)),
                ("internal_field", models.CharField(max_length=100)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="auctions.clubapikey",
                    ),
                ),
            ],
            options={
                "unique_together": {("api_key", "external_field")},
            },
        ),
    ]
