# Generated by Django 5.2.13 on 2026-05-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0248_alter_clubmember_source_clubapikey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubapikey",
            name="key_hash",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
