# Generated by Django 5.2.13 on 2026-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0249_alter_clubapikey_key_hash_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmember",
            name="source",
            field=models.CharField(default="manually_added", max_length=200),
        ),
    ]
