# Generated by Django 5.2.13 on 2026-05-07 17:10

from django.db import migrations, models


def migrate_roles_to_fields(apps, schema_editor):
    """Copy role→permission M2M data to bool fields, and migrate club owners to admin members."""
    ClubMember = apps.get_model("auctions", "ClubMember")
    for member in ClubMember.objects.prefetch_related("roles__permissions").all():
        perm_names = {perm.name for role in member.roles.all() for perm in role.permissions.all()}
        if perm_names:
            for pname in perm_names:
                if hasattr(member, pname):
                    setattr(member, pname, True)
            member.save()

    Club = apps.get_model("auctions", "Club")
    for club in Club.objects.filter(owner__isnull=False).select_related("owner"):
        owner = club.owner
        member, _ = ClubMember.objects.get_or_create(
            club=club,
            user=owner,
            defaults={
                "first_name": owner.first_name,
                "last_name": owner.last_name,
                "source": "manually_added",
            },
        )
        if not member.permission_admin:
            member.permission_admin = True
            member.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0250_alter_clubmember_source_free_text"),
    ]

    operations = [
        # Step 1: Add new bool fields first (all default False)
        migrations.AddField(
            model_name="clubmember",
            name="permission_add_edit",
            field=models.BooleanField(default=False, help_text="Add and edit members."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="permission_admin",
            field=models.BooleanField(default=False, help_text="Full admin access — grants all other permissions."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="permission_edit_club",
            field=models.BooleanField(default=False, help_text="Edit club settings."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="permission_export",
            field=models.BooleanField(default=False, help_text="Export member data to CSV."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="permission_manage_auctions",
            field=models.BooleanField(default=False, help_text="Manage auctions for this club."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="permission_manage_bap",
            field=models.BooleanField(default=False, help_text="Manage BAP/HAP points."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="permission_view",
            field=models.BooleanField(default=False, help_text="View the member list."),
        ),
        # Step 2: Migrate existing data before dropping old tables
        migrations.RunPython(migrate_roles_to_fields, noop),
        # Step 3: Remove old M2M relations, owner FK, and drop the tables
        migrations.RemoveField(
            model_name="clubrole",
            name="permissions",
        ),
        migrations.RemoveField(
            model_name="clubmember",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="club",
            name="owner",
        ),
        migrations.DeleteModel(
            name="ClubPermission",
        ),
        migrations.DeleteModel(
            name="ClubRole",
        ),
    ]
