# Generated by Django 5.2.13 on 2026-05-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0251_flatten_club_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="first_discord_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auction",
            name="second_discord_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="club",
            name="auction_channel_id",
            field=models.CharField(
                blank=True,
                help_text="Discord channel ID for auction announcements. Set via /auctions_here.",
                max_length=100,
                null=True,
            ),
        ),
    ]
