# Generated by Django 5.2.13 on 2026-05-08 17:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0252_auction_first_discord_sent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="add_membership_fee_to_invoices_for_expired_members",
            field=models.BooleanField(
                default=False, help_text="Automatically include club membership renewal fees when needed."
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="add_people_from_auction_to_club",
            field=models.BooleanField(default=False, help_text="Add auction participants to the associated club."),
        ),
        migrations.AddField(
            model_name="club",
            name="payment_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Club dues are sent to this user's connected payment account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_payment_destinations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="send_membership_expiration_reminders",
            field=models.BooleanField(default=False, help_text="Send reminder emails before membership expiration."),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="membership_expiration_reminder_due",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="renewal_needed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="renewal_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="club_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="auctions.clubmember",
            ),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="payment_target",
            field=models.CharField(
                choices=[("INVOICE", "Invoice"), ("CLUB_MEMBER", "Club member")], default="INVOICE", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="invoicepayment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="auctions.invoice",
            ),
        ),
    ]
