# Generated by Django 5.2.13 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0254_create_club_membership_expiring_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="contact_email",
            field=models.CharField(
                blank=True,
                help_text="Replies to membership inquires will be sent to this email",
                max_length=255,
                null=True,
                verbose_name="Membership email address",
            ),
        ),
    ]
