# Generated by Django 5.2.13 on 2026-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0255_alter_club_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='enable_membership',
            field=models.BooleanField(default=False, help_text='Enable membership tracking, dues collection, and expiration reminders.', verbose_name='Enable membership'),
        ),
    ]
