# Generated by Django 5.2.13 on 2026-05-16 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0256_club_enable_membership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_invoices",
                to="auctions.club",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="send_membership_expiration_reminders",
            field=models.BooleanField(
                default=False,
                help_text="Reminders include a link to pay directly on this site, users don't need to have an account to renew their membership.",
            ),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="permission_admin",
            field=models.BooleanField(
                default=False,
                help_text="Full admin access — grants all other permissions.  Use only if absolutely necessary.",
            ),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="permission_edit_club",
            field=models.BooleanField(
                default=False, help_text="Change club setup, Discord, and API keys.  Nearly as dangerous as admin."
            ),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="permission_view",
            field=models.BooleanField(
                default=False, help_text="View the member list.  Other permissions implicitly grant this."
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="auctiontos_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auctiontos",
                to="auctions.auctiontos",
            ),
        ),
    ]
