# Generated by Django 5.2.13 on 2026-05-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0257_invoice_buyer_invoice_club_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="last_discord_role_assigned",
            field=models.ForeignKey(
                blank=True,
                help_text="Last role auto-assigned via the Discord API; used to detect when the role needs to change.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="auctions.clubdiscordrole",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="use_categories",
            field=models.BooleanField(
                default=True,
                help_text="Not shown on the bulk add lots form.  Check to use categories like Cichlids, Livebearers, etc.",
                verbose_name="Use category field",
            ),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="permission_edit_club",
            field=models.BooleanField(
                default=False,
                help_text="Change club setup, Discord, API keys, payment settings, and membership settings.  Nearly as dangerous as admin.",
            ),
        ),
    ]
