# Generated by Django 5.2.13 on 2026-05-18 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0258_clubmember_last_discord_role_assigned_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="enable_club_page",
            field=models.BooleanField(
                default=False,
                help_text="Enables the public club detail page and membership self-service features (online renewal, expiration reminders). Required to use membership management.",
                verbose_name="Enable public club page",
            ),
        ),
        migrations.CreateModel(
            name="BapAward",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("points", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who manually awarded these points. Null if auto-awarded.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bap_awards_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bap_awards", to="auctions.clubmember"
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bap_award",
                        to="auctions.lot",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
