# Generated by Django 5.2.13 on 2026-05-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0259_alter_club_enable_club_page_bapaward"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="membership_expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
