# Generated by Django 5.2.13 on 2026-05-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0261_backfill_membership_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bapaward",
            name="cap_points",
            field=models.IntegerField(default=0, help_text="CAP (culture) points awarded."),
        ),
        migrations.AddField(
            model_name="bapaward",
            name="hap_points",
            field=models.IntegerField(default=0, help_text="HAP points awarded."),
        ),
        migrations.AlterField(
            model_name="bapaward",
            name="points",
            field=models.IntegerField(default=0, help_text="BAP points awarded."),
        ),
    ]
