# Generated by Django 5.2.13 on 2026-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0262_bapaward_hap_cap_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubdiscordrole",
            name="bot_can_manage",
            field=models.BooleanField(
                default=True,
                help_text="False when this role is at or above the bot's own role in the Discord hierarchy; the bot cannot assign or remove roles at its own level or higher",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="send_membership_expiration_reminders",
            field=models.BooleanField(
                default=False,
                help_text="Reminders include a link to pay directly on this site, users don't need to have an account to renew their membership.  Reminders are only sent if the user has paid for their membership at least once.  This option is probably not a great idea as users will get an email from this site asking them to pay for their membership, which may cause confusion.",
            ),
        ),
        migrations.AlterField(
            model_name="clubmember",
            name="permission_export",
            field=models.BooleanField(default=False, help_text="Import and export member data as CSV."),
        ),
    ]
