# Generated by Django 5.2.13 on 2026-05-21 19:57

from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0264_clubmember_rename_first_name_drop_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="membership_number",
            field=models.BigIntegerField(
                default=auctions.models._default_membership_number,
                help_text="Unique membership number assigned to this member.",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="add_membership_fee_to_invoices_for_expired_members",
            field=models.BooleanField(
                default=False,
                help_text="And create membership if they don't have one.  you can turn this off on each invoice.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="contact_email",
            field=models.CharField(
                blank=True,
                help_text="Replies to membership inquiries will be sent to this email",
                max_length=255,
                null=True,
                verbose_name="Membership email address",
            ),
        ),
    ]
