# Generated by Django 5.2.13 on 2026-05-22 13:12

from django.db import migrations, models

import auctions.models


def dedupe_membership_numbers(apps, schema_editor):
    """Re-roll any ClubMember.membership_number values that collide with another row.

    The random default has a ~9-billion key space, so collisions in a freshly
    populated column are extremely unlikely — but if any exist this step picks
    a fresh random value (with collision retry) before the unique constraint
    is applied. Without this, applying the constraint on a colliding table
    would fail with an IntegrityError.
    """
    import random

    ClubMember = apps.get_model("auctions", "ClubMember")

    def random_number():
        return random.randint(1_000_000_000, 9_999_999_999)

    used = set()
    # First pass: collect every value and find any duplicates by streaming through.
    duplicates = []
    for pk, num in ClubMember.objects.values_list("pk", "membership_number").iterator():
        if num in used:
            duplicates.append(pk)
        else:
            used.add(num)
    # Second pass: re-roll duplicates until each gets a unique value.
    for pk in duplicates:
        for _ in range(50):
            candidate = random_number()
            if candidate not in used:
                used.add(candidate)
                ClubMember.objects.filter(pk=pk).update(membership_number=candidate)
                break


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0265_add_clubmember_membership_number"),
    ]

    operations = [
        migrations.RunPython(dedupe_membership_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clubmember",
            name="membership_number",
            field=models.BigIntegerField(
                default=auctions.models._default_membership_number,
                help_text="Unique membership number assigned to this member.",
                unique=True,
            ),
        ),
    ]
