# Generated by Django 5.2.13 on 2026-05-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0266_unique_membership_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="google_wallet_class_created",
            field=models.BooleanField(
                default=False, help_text="Set to True once the Wallet GenericClass has been confirmed on Google's side."
            ),
        ),
    ]
