# Generated by Django 5.2.13 on 2026-05-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0267_club_google_wallet_class_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="membership_number_mode",
            field=models.CharField(
                choices=[
                    ("disabled", "No member numbers"),
                    ("paid_only", "Paid members only"),
                    ("all_members", "All members"),
                ],
                default="all_members",
                help_text="10 digit automatically generated number that can be scanned with a barcode reader, QR code, and added to Google Wallet.",
                max_length=20,
                verbose_name="Member number",
            ),
        ),
    ]
