# Generated by Django 5.2.13 on 2026-05-22 15:20

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0268_club_membership_number_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="icon",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                help_text="Square logo shown beside the club name and on Google/Apple Wallet membership cards.",
                null=True,
                upload_to="club_icons/",
            ),
        ),
    ]
