# Generated by Django 5.2.13 on 2026-05-22 18:20

from django.db import migrations


def enable_category_field_for_all_auctions(apps, schema_editor):
    Auction = apps.get_model("auctions", "Auction")
    Auction.objects.filter(use_categories=False).update(use_categories=True)


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0269_club_icon"),
    ]

    operations = [
        migrations.RunPython(enable_category_field_for_all_auctions, migrations.RunPython.noop),
    ]
