# Generated by Django 5.2.13 on 2026-05-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0271_clubapikey_can_add_bap_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="discord_event_created",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="club",
            name="create_events_for_auctions",
            field=models.BooleanField(
                default=False, help_text="Automatically create a Discord scheduled event for each promoted auction."
            ),
        ),
    ]
