# Generated by Django 5.2.13 on 2026-05-23 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0273_backfill_bap_auto_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubmember",
            options={},
        ),
        migrations.AddField(
            model_name="auction",
            name="manage_users_through_club",
            field=models.BooleanField(
                default=False,
                help_text="Manage participants as members of the associated club. Once enabled, this cannot be disabled. Requires an associated club and an empty auction (no lots, no invoices). Enabling this deletes existing per-auction participant records.",
            ),
        ),
        migrations.AddField(
            model_name="auctiontos",
            name="clubmember",
            field=models.ForeignKey(
                blank=True,
                help_text="When the auction is managed through its club, links this record to the ClubMember that owns the bidder_number and permissions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auction_tos_records",
                to="auctions.clubmember",
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="bidder_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Used when the club manages auction participants directly. Must be unique within this club.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="bidding_allowed",
            field=models.BooleanField(
                default=True,
                help_text="When the club manages auction participants, controls whether this member can place bids.",
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="selling_allowed",
            field=models.BooleanField(
                default=True,
                help_text="When the club manages auction participants, controls whether this member can submit lots.",
            ),
        ),
        migrations.AddConstraint(
            model_name="clubmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bidder_number", ""), _negated=True),
                fields=("club", "bidder_number"),
                name="unique_bidder_number_per_club",
            ),
        ),
    ]
