# Generated by Django 5.2.13 on 2026-05-24 17:05

from django.db import migrations, models


def convert_bool_to_choice(apps, schema_editor):
    """Convert legacy BooleanField values to the new CharField choices.

    MariaDB stores BooleanField as tinyint(1) so the raw column values are
    1 (True) and 0 (False).  After the AlterField the column becomes varchar;
    we convert:
      1 / '1' / 'True' → 'all'
      0 / '0' / 'False' / NULL / '' → ''  (off)
    """
    Auction = apps.get_model("auctions", "Auction")
    Auction.objects.filter(manage_users_through_club__in=["1", "True", True]).update(manage_users_through_club="all")
    Auction.objects.exclude(manage_users_through_club="all").update(manage_users_through_club="")


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0274_alter_clubmember_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clubmember",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="auction",
            name="manage_users_through_club",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Off"),
                    ("all", "Automatically add all club members"),
                    ("checkin", "Add on user check-in"),
                ],
                default="",
                help_text=(
                    "Manage participants as members of the associated club. "
                    "Requires an associated club and an empty auction (no lots, no invoices). "
                    "Changing this deletes existing per-auction participant records."
                ),
                max_length=20,
            ),
        ),
        migrations.RunPython(convert_bool_to_choice, migrations.RunPython.noop),
    ]
