# Generated by Django 5.2.14 on 2026-05-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0275_alter_manage_users_through_club_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctiontos",
            name="checked_in",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="auctiontos",
            name="door_prize_called",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
