# Generated by Django 5.2.13 on 2026-05-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0277_backfill_clubmember_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="add_membership_fee_to_invoices_for_expired_members",
            field=models.BooleanField(
                default=False,
                help_text="And create membership if they don't have one.  You can turn this off on each invoice.",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="add_people_from_auction_to_club",
            field=models.BooleanField(
                default=False,
                help_text="Add auction participants to the associated club.  This is a one-way sync to the club and will only create new club members, not update existing ones.  To keep both auction and club records in sync, turn on Manage users through club instead -- there's a 99% chance that's what you want.",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="manage_users_through_club",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Off"),
                    ("all", "Automatically add all club members"),
                    ("checkin", "Automatically add, but require check-in"),
                ],
                default="",
                help_text="Manage participants as members of the associated club. Requires an associated club and an empty auction (no lots, no invoices). Changing this deletes existing per-auction participant records.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_on_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short name printed on lot labels. Leave blank to use the full category name.",
                max_length=255,
            ),
        ),
    ]
