# Generated by Django 5.2.13 on 2026-05-28 17:37

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0283_clubmoney_permission_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmoney",
            name="source_auction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_money",
                to="auctions.auction",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="title", slugify=auctions.models._slugify_auction_title, unique=True
            ),
        ),
    ]
