# Generated by Django 5.2.13 on 2026-05-29 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0287_club_include_next_auction_in_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="club_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="auctions.clubmember",
            ),
        ),
    ]
