# Generated by Django 5.2.13 on 2026-05-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0288_invoice_club_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="expiring_soon_closing",
            field=models.TextField(blank=True, default="", verbose_name="Expiring soon email closing text"),
        ),
        migrations.AddField(
            model_name="club",
            name="expiring_soon_include_auction",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="club",
            name="expiring_soon_opening",
            field=models.TextField(blank=True, default="", verbose_name="Expiring soon email opening text"),
        ),
        migrations.AddField(
            model_name="club",
            name="renewal_closing",
            field=models.TextField(blank=True, default="", verbose_name="Renewal email closing text"),
        ),
        migrations.AddField(
            model_name="club",
            name="renewal_include_auction",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="club",
            name="renewal_opening",
            field=models.TextField(blank=True, default="", verbose_name="Renewal email opening text"),
        ),
        migrations.AddField(
            model_name="club",
            name="welcome_closing",
            field=models.TextField(blank=True, default="", verbose_name="Welcome email closing text"),
        ),
        migrations.AddField(
            model_name="club",
            name="welcome_include_auction",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="club",
            name="welcome_opening",
            field=models.TextField(blank=True, default="", verbose_name="Welcome email opening text"),
        ),
    ]
