# Generated by Django 5.2.13 on 2026-05-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0289_club_expiring_soon_closing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="expiring_soon_closing",
            field=models.TextField(blank=True, default="Best wishes,", verbose_name="Expiring soon email closing text"),
        ),
        migrations.AlterField(
            model_name="club",
            name="expiring_soon_include_auction",
            field=models.BooleanField(default=True, verbose_name="Also include information about the next auction"),
        ),
        migrations.AlterField(
            model_name="club",
            name="expiring_soon_opening",
            field=models.TextField(
                blank=True, default="Your membership expires soon", verbose_name="Expiring soon email opening text"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="renewal_closing",
            field=models.TextField(blank=True, default="Best wishes,", verbose_name="Renewal email closing text"),
        ),
        migrations.AlterField(
            model_name="club",
            name="renewal_include_auction",
            field=models.BooleanField(default=True, verbose_name="Also include information about the next auction"),
        ),
        migrations.AlterField(
            model_name="club",
            name="renewal_opening",
            field=models.TextField(
                blank=True, default="Your membership has been renewed!", verbose_name="Renewal email opening text"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="welcome_closing",
            field=models.TextField(blank=True, default="Best wishes,", verbose_name="Welcome email closing text"),
        ),
        migrations.AlterField(
            model_name="club",
            name="welcome_include_auction",
            field=models.BooleanField(default=True, verbose_name="Also include information about the next auction"),
        ),
        migrations.AlterField(
            model_name="club",
            name="welcome_opening",
            field=models.TextField(
                blank=True, default="Thanks for joining!", verbose_name="Welcome email opening text"
            ),
        ),
    ]
