# Generated by Django 5.2.13 on 2026-05-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0291_remove_auction_add_people_from_auction_to_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="last_club_activity",
            field=models.DateTimeField(blank=True, help_text="Last recorded activity in this club", null=True),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="lat",
            field=models.FloatField(blank=True, help_text="Latitude geocoded from member's address", null=True),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="lng",
            field=models.FloatField(blank=True, help_text="Longitude geocoded from member's address", null=True),
        ),
    ]
