# Generated by Django 5.2.13 on 2026-05-31 13:35

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0292_club_member_lat_lng_last_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="mailchimp_access_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="OAuth access token (does not expire).", null=True
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="mailchimp_audience_id",
            field=models.CharField(
                blank=True,
                help_text="The Mailchimp audience (list) id members are synced into. Safe across renames in Mailchimp.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="mailchimp_audience_name",
            field=models.CharField(
                blank=True, help_text="Display name of the connected audience at connection time.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="mailchimp_connected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The club admin who connected Mailchimp.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="mailchimp_connected_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="mailchimp_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="club",
            name="mailchimp_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="mailchimp_server_prefix",
            field=models.CharField(
                blank=True, help_text="Mailchimp data-center prefix (e.g. us19) from the OAuth metadata.", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="mailchimp_webhook_secret",
            field=models.CharField(
                blank=True, help_text="Secret embedded in the Mailchimp webhook URL to verify callbacks.", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="cached_total_bought",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="cached_total_sold",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="mailchimp_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="mailchimp_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not synced"),
                    ("subscribed", "Subscribed"),
                    ("unsubscribed", "Unsubscribed"),
                    ("cleaned", "Cleaned (bounced)"),
                    ("pending", "Pending"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="",
                help_text="Last known Mailchimp subscription status; set by sync and by the unsubscribe webhook.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="mailchimp_web_id",
            field=models.CharField(
                blank=True,
                help_text="Mailchimp internal web_id, used to build the 'View in Mailchimp' link.",
                max_length=50,
            ),
        ),
    ]
