# Generated by Django 5.2.13 on 2026-06-02 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0294_backfill_club_member_lat_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="only_donation_lots",
            field=models.BooleanField(default=False, help_text="Require all BAP lots to be a donation."),
        ),
        migrations.AddField(
            model_name="club",
            name="points_for_custom_checkbox",
            field=models.IntegerField(
                default=0,
                help_text="Bonus BAP points awarded when the custom checkbox is checked on a lot. Leave at 0 to disable.",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="bap_auto_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_eligible", "Not eligible"),
                    ("not_long_enough", "Not long enough since last submission"),
                    ("category_not_eligible", "Category not eligible (BAP points = 0)"),
                    ("not_club_member", "Not a club member"),
                    ("not_bred", "Didn't breed this fish"),
                    ("not_active_member", "Not an active club member"),
                    ("not_sold", "Not sold"),
                    ("low_quantity", "Quantity below club minimum"),
                    ("not_donation", "Lot is not a donation"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ClubBapCategoryOverride",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("points", models.IntegerField(default=0)),
                ("created_on", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bap_overrides",
                        to="auctions.category",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bap_category_overrides",
                        to="auctions.club",
                    ),
                ),
            ],
            options={
                "unique_together": {("club", "category")},
            },
        ),
    ]
