# Generated by Django 5.2.13 on 2026-06-03 16:04

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0295_bap_custom_checkbox_donation_category_overrides"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="brevo_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="The club's Brevo API v3 key (stored encrypted).", null=True
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="brevo_connected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The club admin who connected Brevo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="brevo_connected_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="brevo_folder_id",
            field=models.CharField(
                blank=True,
                help_text="Brevo folder that holds the club's list (Brevo requires lists to live in a folder).",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="brevo_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="club",
            name="brevo_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="brevo_list_id",
            field=models.CharField(
                blank=True,
                help_text="The Brevo contact list id members are synced into. Safe across renames in Brevo.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="brevo_list_name",
            field=models.CharField(
                blank=True, help_text="Display name of the connected list at connection time.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="brevo_webhook_id",
            field=models.CharField(
                blank=True, help_text="Brevo webhook id, stored so we don't register duplicates.", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="brevo_webhook_secret",
            field=models.CharField(
                blank=True, help_text="Secret embedded in the Brevo webhook URL to verify callbacks.", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="brevo_contact_id",
            field=models.CharField(
                blank=True,
                help_text="Brevo internal contact id, used to build the 'View in Brevo' link.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="brevo_last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="brevo_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not synced"),
                    ("subscribed", "Subscribed"),
                    ("unsubscribed", "Unsubscribed"),
                    ("cleaned", "Cleaned (bounced/spam)"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="",
                help_text="Last known Brevo subscription status; set by sync and by the unsubscribe webhook.",
                max_length=20,
            ),
        ),
    ]
