# Generated by Django 5.2.13 on 2026-06-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0296_club_brevo_api_key_club_brevo_connected_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="points_per_lot",
            field=models.IntegerField(
                default=0, help_text="Default BAP points. Override these with per-category points below"
            ),
        ),
        migrations.CreateModel(
            name="MobileDevice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_uuid", models.UUIDField(db_index=True, unique=True)),
                ("device_name", models.CharField(blank=True, max_length=200)),
                (
                    "platform",
                    models.CharField(blank=True, choices=[("ios", "iOS"), ("android", "Android")], max_length=10),
                ),
                ("app_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
    ]
