# Generated by Django 5.2.14 on 2026-06-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0297_alter_club_points_per_lot_mobiledevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="renewal_manually_set",
            field=models.BooleanField(default=False),
        ),
    ]
