# Generated by Django 5.2.14 on 2026-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0298_add_invoice_renewal_manually_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="only_sold_lots",
            field=models.BooleanField(
                default=False,
                help_text="Require lots to be sold for points to be awarded. Uncheck to give points for submitted and unsold lots. If automatically award points is on, they will only be automatically awarded to sold lots.",
                verbose_name="Only sold lots",
            ),
        ),
    ]
