# Generated by Django 5.2.14 on 2026-06-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0299_add_only_sold_lots_to_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="no_min_bids",
            field=models.BooleanField(
                default=False,
                help_text="Lots with a minimum bid set are disqualified. You can still set an auction-wide minimum bid, but any lots that set their own will not be awarded points.",
                verbose_name="No minimum bids",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="bap_auto_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_eligible", "Not eligible"),
                    ("not_long_enough", "Not long enough since last submission"),
                    ("category_not_eligible", "Category not eligible (BAP points = 0)"),
                    ("not_club_member", "Not a club member"),
                    ("not_bred", "Didn't breed this fish"),
                    ("not_active_member", "Not an active club member"),
                    ("not_sold", "Not sold"),
                    ("low_quantity", "Quantity below club minimum"),
                    ("not_donation", "Lot is not a donation"),
                    ("has_min_bid", "Lot has a minimum bid set"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
