# Generated by Django 5.2.14 on 2026-06-13 17:28

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0301_show_member_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="allow_non_oauth_paypal",
            field=models.BooleanField(
                default=False,
                help_text="When checked, this club skips PayPal OAuth and instead enters its own PayPal REST API client ID and secret on the membership settings page. Those credentials are used for the club's auctions and membership payments exactly the way the site's PAYPAL_CLIENT_ID / PAYPAL_SECRET are: payments go straight to that PayPal account with no platform fee. Set this here in the Django admin only.",
                verbose_name="Allow non-OAuth PayPal (admin only)",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="paypal_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="REST API client ID from this club's own PayPal app. Only used when non-OAuth PayPal is allowed.",
                max_length=255,
                verbose_name="PayPal client ID",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="paypal_secret",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="REST API secret from this club's own PayPal app (stored encrypted). Only used when non-OAuth PayPal is allowed.",
                null=True,
                verbose_name="PayPal secret",
            ),
        ),
    ]
