# Generated by Django 5.2.14 on 2026-06-13 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0302_club_allow_non_oauth_paypal_club_paypal_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="current_auction",
            field=models.ForeignKey(
                blank=True,
                help_text="The auction whose admin links are surfaced in the club sidebar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="auctions.auction",
            ),
        ),
    ]
