# Generated by Django 5.2.14 on 2026-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0303_club_current_auction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmoney",
            name="category",
            field=models.CharField(
                choices=[
                    ("auction_sale", "Auction sale (buyer payment)"),
                    ("auction_seller_payout", "Seller payout"),
                    ("tax", "Sales tax collected"),
                    ("membership", "Membership dues"),
                    ("invoice_adjustment", "Invoice adjustment"),
                    ("first_bid_payout", "First-bid payout"),
                    ("rounding", "Invoice rounding"),
                    ("donation", "Donation"),
                    ("speaker_costs", "Speaker costs"),
                    ("meeting_location_cost", "Meeting location cost"),
                    ("refunds", "Refund"),
                    ("adjustment", "Balance adjustment"),
                ],
                max_length=40,
            ),
        ),
    ]
