# Generated by Django 5.2.14 on 2026-06-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0305_reset_invoice_club_money"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandPalettePage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "search_term",
                    models.CharField(
                        db_index=True,
                        help_text="The phrase people type, e.g. 'sell lots' or 'address'.",
                        max_length=200,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="Dynamic destination key resolved against the user's context, e.g. 'last_auction:set_winners' or 'club:brevo'. Leave blank to use the URL field instead.",
                        max_length=100,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Literal path used when target is blank, e.g. '/selling/'.",
                        max_length=500,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional label override. Leave blank to use a sensible default.",
                        max_length=200,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=400)),
                (
                    "icon",
                    models.CharField(blank=True, help_text="Bootstrap icon class, e.g. 'bi-cash-coin'.", max_length=50),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Optional hint: auction, club, or lot. Not currently required.",
                        max_length=20,
                    ),
                ),
                (
                    "hits",
                    models.PositiveIntegerField(default=0, help_text="Number of times this shortcut has been clicked."),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-hits", "search_term"],
            },
        ),
        migrations.CreateModel(
            name="CommandPaletteSearch",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("search", models.CharField(blank=True, max_length=600)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("updatedon", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "In progress"),
                            ("clicked", "Clicked a result"),
                            ("abandoned", "Cleared or left"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        blank=True, help_text="auction, lot, club, clubmember, page, or default.", max_length=50
                    ),
                ),
                ("result_url", models.CharField(blank=True, max_length=500)),
                ("result_object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-createdon"],
            },
        ),
    ]
