# Generated by Django 5.2.14 on 2026-06-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0307_seed_command_palette_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="commandpalettepage",
            name="synonyms",
            field=models.CharField(
                blank=True,
                help_text="Extra phrases that map here too (comma- or newline-separated). Good for typos and alternate wording.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="commandpalettepage",
            name="target",
            field=models.CharField(
                blank=True,
                help_text="Dynamic destination key resolved against the user's context, e.g. 'last_auction:set_winners' or 'clubs:brevo'. Leave blank to use the URL field instead.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="commandpalettesearch",
            name="result",
            field=models.CharField(
                choices=[
                    ("pending", "In progress"),
                    ("clicked", "Clicked a result"),
                    ("abandoned", "Cleared or left"),
                    ("bounce", "No results found"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
