# Generated by Django 5.2.14 on 2026-06-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0310_seed_command_palette_print_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="last_club_used",
            field=models.ForeignKey(
                blank=True,
                help_text="The most recent club whose page this user viewed while a member. Used to scope command palette shortcuts.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="auctions.club",
            ),
        ),
    ]
