# Generated by Django 5.2.14 on 2026-07-02 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0315_squareseller_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="alternate_split_mode",
            field=models.CharField(
                choices=[("off", "Off"), ("club_member", "Club member discount"), ("custom", "Custom")],
                default="custom",
                help_text="Charge some sellers different fees.  Club member discount automatically applies the alternate fees to paid club members; custom lets you mark users yourself.",
                max_length=20,
                verbose_name="Alternate split",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="club_member_discount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Automatically add a discount in this amount if a paid club member has purchased at least one lot in this auction",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="clubmoney",
            name="category",
            field=models.CharField(
                choices=[
                    ("auction_sale", "Auction sale (buyer payment)"),
                    ("auction_seller_payout", "Seller payout"),
                    ("tax", "Sales tax collected"),
                    ("membership", "Membership dues"),
                    ("invoice_adjustment", "Invoice adjustment"),
                    ("first_bid_payout", "First-bid payout"),
                    ("club_member_discount", "Club member discount"),
                    ("rounding", "Invoice rounding"),
                    ("donation", "Donation"),
                    ("speaker_costs", "Speaker costs"),
                    ("meeting_location_cost", "Meeting location cost"),
                    ("refunds", "Refund"),
                    ("adjustment", "Balance adjustment"),
                ],
                max_length=40,
            ),
        ),
    ]
