# Generated by Django 5.2.14 on 2026-07-07 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0318_seed_command_palette_v3"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThermalPrinterProfile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("ble_name_patterns", models.JSONField(blank=True, default=list)),
                ("service_uuid", models.CharField(blank=True, default="", max_length=40)),
                ("write_characteristic_uuid", models.CharField(blank=True, default="", max_length=40)),
                ("notify_characteristic_uuid", models.CharField(blank=True, default="", max_length=40)),
                ("chunk_size", models.PositiveIntegerField(default=200)),
                ("chunk_delay_ms", models.PositiveIntegerField(default=20)),
                ("prefer_write_with_response", models.BooleanField(default=True)),
                ("print_width_px", models.PositiveIntegerField(default=96)),
                ("dpi", models.PositiveIntegerField(default=203)),
                ("invert_raster", models.BooleanField(default=False)),
                ("max_label_width_mm", models.FloatField(blank=True, null=True)),
                ("max_label_height_mm", models.FloatField(blank=True, null=True)),
                ("print_program", models.JSONField()),
                ("status_program", models.JSONField(blank=True, default=list)),
                ("status_flags", models.JSONField(blank=True, default=dict)),
                ("label_size_program", models.JSONField(blank=True, default=list)),
                ("label_size_parse", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="auction",
            name="promo_push_notifications_sent",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of push notifications sent promoting this auction"
            ),
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="fcm_token",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="fcm_token_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="push_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userdata",
            name="push_notifications_instead_of_email",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Get notifications in the app instead of emails, for everything except account emails like password resets. Requires the app to be installed and signed in. The weekly promo email is replaced by a notification for promoted auctions near you.",
            ),
        ),
        migrations.AddField(
            model_name="userlabelprefs",
            name="print_method",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF download"),
                    ("system", "System printer"),
                    ("bluetooth", "Bluetooth label printer"),
                ],
                default="pdf",
                help_text="PDF downloads a file to print later. System printer sends the PDF straight to a printer configured on your phone. Bluetooth prints directly to a thermal label printer. System printer and Bluetooth only work in the app.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PushNotificationSent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(db_index=True, max_length=40)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auction",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="auctions.auction"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="auctions.mobiledevice"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="auctions.invoice"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "category", "auction"], name="auctions_pu_user_id_2de13c_idx")
                ],
            },
        ),
    ]
