# Generated by Django 5.2.15 on 2026-07-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0320_seed_thermal_printer_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="adcampaign",
            name="cloudflare_image_id",
            field=models.CharField(blank=True, db_index=True, default="", editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="club",
            name="cloudflare_image_id",
            field=models.CharField(blank=True, db_index=True, default="", editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="lotimage",
            name="cloudflare_image_id",
            field=models.CharField(blank=True, db_index=True, default="", editable=False, max_length=100),
        ),
    ]
