# Generated by Django 5.2.15 on 2026-07-10 21:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0323_backfill_blank_club_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="apple_pass_auth_token",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="apple_pass_updated",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name="AppleDeviceRegistration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_library_identifier", models.CharField(db_index=True, max_length=255)),
                ("push_token", models.CharField(max_length=255)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apple_device_registrations",
                        to="auctions.clubmember",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "device_library_identifier"), name="unique_member_device_registration"
                    )
                ],
            },
        ),
    ]
