# Generated by Django 5.2.15 on 2026-07-12 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0324_clubmember_apple_pass_auth_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="tax",
            field=models.PositiveIntegerField(
                default=0,
                help_text="A percent added to the buyer's invoice for all won lots (e.g. enter 7 for 7% sales tax). Leave at 0 for no tax.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Open"), ("UNPAID", "Ready"), ("PAID", "Paid")], default="DRAFT", max_length=20
            ),
        ),
    ]
