# Generated by Django 5.2.15 on 2026-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0326_update_privacy_blog_mobile_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="calculated_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="This field is set automatically, you shouldn't need to manually change it",
                max_digits=10,
                null=True,
            ),
        ),
    ]
