# Generated by Django 5.2.15 on 2026-07-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0327_alter_invoice_calculated_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="date_paid",
            field=models.DateTimeField(
                blank=True,
                help_text="When this invoice first became PAID, i.e. when the cash actually changed hands. Set automatically the first time the invoice is saved as PAID and never overwritten afterwards, so the club ledger (ClubMoney) can book on a cash basis. Left unset until then; recorded online payments (InvoicePayment) take precedence over this as the cash date.",
                null=True,
            ),
        ),
    ]
