# Generated by Django 5.2.15 on 2026-07-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0329_fix_escpos_raster_print_width"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LotPosition",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("confidence", models.FloatField(default=0)),
                ("observation_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ar_positions", to="auctions.auction"
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ar_position", to="auctions.lot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotObservation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.UUIDField()),
                ("frame_id", models.CharField(max_length=32)),
                ("captured_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bearing_deg", models.FloatField()),
                ("depression_deg", models.FloatField()),
                ("quality", models.FloatField(default=1.0)),
                ("fov_calibrated", models.BooleanField(default=False)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ar_observations",
                        to="auctions.auction",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ar_observations", to="auctions.lot"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["auction", "captured_at"], name="auctions_lo_auction_2fd0e5_idx"),
                    models.Index(fields=["session_id", "frame_id"], name="auctions_lo_session_09872f_idx"),
                ],
            },
        ),
    ]
