# Generated by Django 5.2.15 on 2026-07-18 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0330_lotposition_lotobservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="selling_push_notification_sent",
            field=models.BooleanField(
                default=False,
                help_text="Set once this lot has notified its watchers that it's being sold or is coming up in the queue, so watchers only ever get one 'coming up' push per lot.",
            ),
        ),
        migrations.CreateModel(
            name="LotQueueEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField()),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Set once this entry has been processed for a 'coming up soon' push while in the top of the queue, so each queue entry is only ever considered once regardless of dedupe on the lot.",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_queue_entries",
                        to="auctions.auction",
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="queue_entry", to="auctions.lot"
                    ),
                ),
            ],
            options={
                "ordering": ["auction", "order"],
            },
        ),
    ]
