# Generated by Django 5.2.15 on 2026-07-19 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0331_lot_selling_push_notification_sent_lotqueueentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MobileOfflineOp",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("op_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("op_type", models.CharField(max_length=20)),
                ("result_pk", models.IntegerField(blank=True, null=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="offline_ops", to="auctions.auction"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["auction", "op_type"], name="auctions_mo_auction_9a2417_idx")],
            },
        ),
    ]
