# Generated by Django 5.2.15 on 2026-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0332_mobileofflineop"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="added_to_queue",
            field=models.BooleanField(
                default=False,
                help_text="Set once this lot has ever been added to the in-person selling queue. Sticky (never unset when the queue entry is removed or the lot sells) so the auction stats can report how much the queue was used.",
            ),
        ),
    ]
