# Generated by Django 5.2.15 on 2026-07-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0333_lot_added_to_queue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lotqueueentry",
            name="notification_sent",
        ),
        migrations.AddField(
            model_name="lot",
            name="coming_up_push_sent",
            field=models.BooleanField(
                default=False,
                help_text="Set once this lot's watchers got the 'coming up soon -- N lots away' push while it sat in the top 10 of the in-person queue. Deduped so that push fires at most once per lot; the later 'about to be sold' push (selling_push_notification_sent) overwrites it on the device.",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="selling_push_notification_sent",
            field=models.BooleanField(
                default=False,
                help_text="Set once this lot's watchers got the final 'about to be sold' push (it reached the head of the queue or was pulled up on the set-winners screen). Deduped so that push fires at most once per lot; shares a notification tag with the 'coming up soon' push so it overwrites it.",
            ),
        ),
    ]
