# Generated by Django 5.2.15 on 2026-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0334_remove_lotqueueentry_notification_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotobservation",
            name="yaw_deg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lotposition",
            name="component",
            field=models.IntegerField(default=0),
        ),
    ]
