# Generated by Django 5.2.15 on 2026-07-20 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0336_seed_command_palette_print_labels_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="exact_location_set",
            field=models.BooleanField(
                default=False, help_text="The location was pinned from a phone at the venue (or confirmed exact)."
            ),
        ),
        migrations.CreateModel(
            name="CheckinNudge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("auction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auctions.auction")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("user", "auction", "kind"), name="one_nudge_per_kind")],
            },
        ),
    ]
