# Generated by Django 5.2.15 on 2026-07-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0338_volunteerjob_volunteersignup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotobservation",
            name="session_id",
            field=models.CharField(max_length=36),
        ),
    ]
