# Generated by Django 5.2.15 on 2026-07-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0339_alter_lotobservation_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotobservation",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lotobservation",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
