# Generated by Django 5.2.15 on 2026-07-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0340_lotobservation_latitude_lotobservation_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotobservation",
            name="heading_deg",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
