# Generated by Django 5.2.15 on 2026-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0341_lotobservation_heading_deg"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotobservation",
            name="odo_x_m",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lotobservation",
            name="odo_y_m",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
