# Generated by Django 5.2.15 on 2026-07-24 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0342_lotobservation_odo_x_m_lotobservation_odo_y_m"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="registration_fee",
            field=models.PositiveIntegerField(
                default=0, help_text="Added to all invoices", validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="registration_fee_for_club_members",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Used instead of the registration fee, when you mark someone as using alternative fees",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="clubmoney",
            name="category",
            field=models.CharField(
                choices=[
                    ("auction_sale", "Auction sale (buyer payment)"),
                    ("auction_seller_payout", "Seller payout"),
                    ("tax", "Sales tax collected"),
                    ("membership", "Membership dues"),
                    ("invoice_adjustment", "Invoice adjustment"),
                    ("first_bid_payout", "First-bid payout"),
                    ("club_member_discount", "Club member discount"),
                    ("registration_fee", "Registration fee"),
                    ("rounding", "Invoice rounding"),
                    ("donation", "Donation"),
                    ("speaker_costs", "Speaker costs"),
                    ("meeting_location_cost", "Meeting location cost"),
                    ("refunds", "Refund"),
                    ("adjustment", "Balance adjustment"),
                ],
                max_length=40,
            ),
        ),
    ]
