# Generated by Django 5.2.15 on 2026-07-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0343_auction_registration_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="paypal_webhook_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Webhook ID from this club's PayPal dashboard, used to verify incoming membership subscription webhooks. Create a webhook pointing at /clubs/paypal/webhook subscribed to BILLING.SUBSCRIPTION events, then paste its ID here.",
                max_length=100,
                verbose_name="PayPal subscription webhook ID",
            ),
        ),
        migrations.AddField(
            model_name="clubmember",
            name="paypal_subscription_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="PayPal recurring subscription ID (e.g. I-XXXXXXXX). Set/cleared by the PayPal subscription webhook. While set, the member auto-renews via PayPal: expiring-soon reminders are skipped and the invoice membership-renewal box is disabled.",
                max_length=50,
            ),
        ),
    ]
