# Generated by Django 5.2.15 on 2026-07-25 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0345_seed_command_palette_printing_synonyms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="thermalprinterprofile",
            name="manufacturer_patterns",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="thermalprinterprofile",
            name="model_patterns",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="ObservedPrinter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ble_name", models.CharField(blank=True, default="", max_length=100)),
                ("manufacturer", models.CharField(blank=True, default="", max_length=100)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("firmware", models.CharField(blank=True, default="", max_length=100)),
                ("hardware", models.CharField(blank=True, default="", max_length=100)),
                ("service_uuids", models.JSONField(blank=True, default=list)),
                ("profile_slug", models.CharField(blank=True, db_index=True, default="", max_length=50)),
                (
                    "matched_by",
                    models.CharField(
                        choices=[
                            ("bleName", "BLE name pattern"),
                            ("deviceInfo", "Device Information Service (model/manufacturer)"),
                            ("serviceUuid", "Service UUID"),
                            ("manual", "User picked it manually"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("printed_ok", models.BooleanField(default=False)),
                ("times_seen", models.PositiveIntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-last_seen"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "ble_name", "model", "profile_slug"), name="unique_observed_printer_per_user"
                    )
                ],
            },
        ),
    ]
