# Generated by Django 5.2.15 on 2026-07-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0347_seed_printer_device_info_patterns"),
    ]

    operations = [
        migrations.AddField(
            model_name="observedprinter",
            name="characterized",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="observedprinter",
            name="derived_status_values",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="observedprinter",
            name="gatt",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="observedprinter",
            name="probe_replies",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="observedprinter",
            name="probed_language",
            field=models.CharField(blank=True, db_index=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="observedprinter",
            name="status_ambiguities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="observedprinter",
            name="status_captures",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="thermalprinterprofile",
            name="command_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tspl", "TSPL / TSPL2 (TSC-compatible)"),
                    ("escpos", "ESC/POS"),
                    ("zpl", "ZPL"),
                    ("cpcl", "CPCL"),
                    ("d11s", "D11s vendor protocol"),
                    ("other", "Other / vendor-specific"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="observedprinter",
            name="matched_by",
            field=models.CharField(
                choices=[
                    ("bleName", "BLE name pattern"),
                    ("deviceInfo", "Device Information Service (model/manufacturer)"),
                    ("serviceUuid", "Service UUID"),
                    ("probe", "Command-language probe"),
                    ("manual", "User picked it manually"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
