# Generated by Django 5.2.15 on 2026-07-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0349_seed_tspl_printer_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="observedprinter",
            name="support_notified",
            field=models.BooleanField(default=False),
        ),
    ]
