# Generated by Django 5.2.15 on 2026-07-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0350_observedprinter_support_notified"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="allow_self_checkin",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Uncheck if you need to assign bidder numbers",
                verbose_name="Allow users to self-check in with the app",
            ),
        ),
    ]
