# Generated by Django 5.2.15 on 2026-07-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0351_auction_allow_self_checkin"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="admin_edited",
            field=models.BooleanField(
                default=True,
                help_text="A club admin created or has edited this record, so the club owns it: deleting the person's site account only removes the account link and leaves the club's copy of their details alone.  Unchecked only for rows a member made about themselves and no admin has touched since — those are deleted with the account.",
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="account_deletion_requested",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user asked us to delete their account.  The account keeps working until the grace period is up (see auctions.account_deletion); signing in again cancels the request.",
                null=True,
            ),
        ),
    ]
