# Generated by Django 5.2.15 on 2026-07-31 15:19

import uuid

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0355_privacy_deletion_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="add_auctions_to_calendar",
            field=models.BooleanField(
                default=True,
                help_text="Automatically add each promoted auction to this club's events and Google Calendar.",
                verbose_name="Add auctions to the calendar",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="create_discord_events_for_club_events",
            field=models.BooleanField(
                default=True,
                help_text="Create a Discord scheduled event for each club event. Auctions are handled by the Discord auction event setting instead, so they are never doubled up.",
                verbose_name="Create Discord events for calendar events",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_access_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                help_text="Short-lived OAuth access token, cached until google_calendar_token_expires.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_account_email",
            field=models.CharField(
                blank=True,
                help_text="The Google account that authorized us, shown on the settings page.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_connected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The club admin who connected Google Calendar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_connected_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_id",
            field=models.CharField(
                blank=True, help_text="Calendar id of the secondary calendar we created for this club.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_is_public",
            field=models.BooleanField(
                default=True,
                help_text="Let anyone view the calendar and subscribe to it. Turn this off to keep it visible only to people you share it with directly in Google Calendar.",
                verbose_name="Make the Google calendar public",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_refresh_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="OAuth refresh token for the club's Google account (stored encrypted).", null=True
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_sync_token",
            field=models.CharField(
                blank=True,
                help_text="Google's incremental sync token, so each pull only fetches what changed.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="google_calendar_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ClubEvent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where is it? A street address works best — it turns into a map link.",
                        max_length=500,
                    ),
                ),
                ("date_start", models.DateTimeField(verbose_name="Starts")),
                ("date_end", models.DateTimeField(blank=True, null=True, verbose_name="Ends")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Created on this site"),
                            ("auction", "From an auction"),
                            ("google", "From Google Calendar"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "google_event_id",
                    models.CharField(
                        blank=True, help_text="Event id in the club's Google Calendar, once pushed.", max_length=1024
                    ),
                ),
                (
                    "discord_event_id",
                    models.CharField(blank=True, help_text="Discord scheduled event id, once created.", max_length=100),
                ),
                (
                    "discord_event_attempted",
                    models.BooleanField(
                        default=False,
                        help_text="Set once we've tried to create a Discord event, so a failure isn't retried forever.",
                    ),
                ),
                (
                    "needs_google_sync",
                    models.BooleanField(
                        default=True,
                        help_text="Set when the event changes on our side and is waiting to be pushed to Google.",
                    ),
                ),
                ("cancelled", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for events mirrored from an auction.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="auctions.auction",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="auctions.club"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date_start"],
                "indexes": [
                    models.Index(fields=["club", "is_deleted", "date_start"], name="auctions_cl_club_id_102e4c_idx")
                ],
                "constraints": [models.UniqueConstraint(fields=("auction",), name="unique_auction_event")],
            },
        ),
    ]
