# Generated by Django 5.2.15 on 2026-07-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0357_backfill_club_events_from_auctions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="google_calendar_is_public",
            field=models.BooleanField(
                default=False,
                help_text="Whether the admin has made the calendar public in Google Calendar. We can't read or change sharing ourselves — that needs a scope granting access to all of their calendars — so this is their word for it, and only controls whether the club page advertises the Google subscribe links.",
                verbose_name="This calendar is shared publicly",
            ),
        ),
    ]
