# Generated by Django 5.2.15 on 2026-07-31 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0359_reset_google_calendar_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clubevent",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for events mirroring an online auction's pickup times.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="auctions.pickuplocation",
            ),
        ),
        migrations.AddField(
            model_name="clubevent",
            name="pickup_slot",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="1 for the location's pickup time, 2 for its second pickup time.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="clubevent",
            name="auction",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for the event mirroring an auction's bidding window.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to="auctions.auction",
            ),
        ),
        migrations.AlterField(
            model_name="clubevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Created on this site"),
                    ("auction", "From an auction"),
                    ("pickup", "From an auction pickup time"),
                    ("google", "From Google Calendar"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="clubevent",
            constraint=models.UniqueConstraint(fields=("pickup_location", "pickup_slot"), name="unique_pickup_event"),
        ),
    ]
