# Generated by Django 5.2.15 on 2026-07-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0360_clubevent_pickup_location_clubevent_pickup_slot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="expiring_soon_include_auction",
            field=models.BooleanField(
                default=True,
                help_text="Your next auction, meeting, or anything else on the club calendar.",
                verbose_name="Also include information about the next event",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="include_next_auction_in_emails",
            field=models.BooleanField(
                default=True,
                help_text="Default for email types that don't have their own setting.",
                verbose_name="Include the next event in membership emails",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="renewal_include_auction",
            field=models.BooleanField(
                default=True,
                help_text="Your next auction, meeting, or anything else on the club calendar.",
                verbose_name="Also include information about the next event",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="welcome_include_auction",
            field=models.BooleanField(
                default=True,
                help_text="Your next auction, meeting, or anything else on the club calendar.",
                verbose_name="Also include information about the next event",
            ),
        ),
    ]
