# Generated by Django 5.2.15 on 2026-07-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0361_alter_club_expiring_soon_include_auction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubevent",
            name="discord_event_attempted",
        ),
        migrations.AddField(
            model_name="auction",
            name="discord_event_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord scheduled event id for this auction, once auction_emails has created one. Kept so the event can be moved or called off when the auction is.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="discord_event_needs_update",
            field=models.BooleanField(
                default=False,
                help_text="Set when something Discord shows about this auction changed and hasn't been sent yet.",
            ),
        ),
        migrations.AddField(
            model_name="clubevent",
            name="all_day",
            field=models.BooleanField(
                default=False,
                help_text="An all-day event. date_end is then the exclusive end, the way Google and iCal write it.",
            ),
        ),
        migrations.AddField(
            model_name="clubevent",
            name="needs_discord_sync",
            field=models.BooleanField(
                default=True,
                help_text="Set when the event changes and is waiting to reach Discord. Cleared once we've tried, success or not, so a permanent failure isn't retried every run — the next edit re-arms it.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="google_calendar_is_public",
            field=models.BooleanField(
                default=False,
                help_text="Whether the admin has made the calendar public in Google Calendar. We can't change sharing ourselves — that needs a scope granting access to all of their calendars — but ticking this box is checked against the calendar's public feed before it sticks. It only controls whether the club page advertises the Google subscribe links.",
                verbose_name="This calendar is shared publicly",
            ),
        ),
        migrations.AlterField(
            model_name="clubevent",
            name="cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Keeps the event visible, struck through, instead of removing it. Subscribers are told it's off rather than watching it vanish.",
                verbose_name="This event is cancelled",
            ),
        ),
    ]
