# Generated by Django 5.2.15 on 2026-07-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0362_remove_clubevent_discord_event_attempted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubevent",
            name="recurrence",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The repeat rule from Google, one RRULE/EXDATE/RDATE line per row. One event stands for the whole series; date_start holds the occurrence that's on now, or next.",
            ),
        ),
        migrations.AddField(
            model_name="clubevent",
            name="recurrence_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Where the series is anchored — the first occurrence. Only set for repeating events.",
                null=True,
            ),
        ),
    ]
