# Generated by Django 5.2.15 on 2026-08-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0363_clubevent_recurrence_clubevent_recurrence_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubapikey",
            name="can_renew_memberships",
            field=models.BooleanField(
                default=False,
                help_text="Renew a membership from an external system, creating the member if they're new.",
            ),
        ),
    ]
