# Generated by Django 5.2.15 on 2026-08-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import auctions.voice


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0364_clubapikey_can_renew_memberships"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceGrammar",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to turn voice off everywhere; the app hides the microphone button.",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("platform", "Platform recognizer"),
                            ("biased", "Platform recognizer, vocabulary-biased"),
                            ("cloud", "Cloud recognizer"),
                            ("spotter", "Keyword spotter"),
                        ],
                        default="platform",
                        help_text="What the app should listen with, if it can. It reports what it actually managed.",
                        max_length=20,
                    ),
                ),
                ("locale", models.CharField(default="en_US", max_length=20)),
                (
                    "prefer_on_device",
                    models.BooleanField(
                        default=True, help_text="On-device recognition keeps working when the hall's wifi doesn't."
                    ),
                ),
                (
                    "anchors",
                    models.JSONField(
                        blank=True,
                        default=auctions.voice.default_anchors,
                        help_text='Slot name → the words that introduce it, e.g. {"lot": ["lot", "item"]}. Lowercase.',
                    ),
                ),
                (
                    "number_words",
                    models.JSONField(
                        blank=True,
                        default=auctions.voice.default_number_words,
                        help_text='Spoken number → digits, e.g. {"seventeen": 17}.',
                    ),
                ),
                (
                    "homophones",
                    models.JSONField(
                        blank=True,
                        default=auctions.voice.default_homophones,
                        help_text='Pairs that sound alike, e.g. [["15", "50"]]. The app offers both when it cannot tell.',
                    ),
                ),
                (
                    "weights",
                    models.JSONField(
                        blank=True,
                        default=auctions.voice.default_weights,
                        help_text="How much each signal counts toward confidence: asr, keyword, snap, agreement.",
                    ),
                ),
                (
                    "thresholds",
                    models.JSONField(
                        blank=True,
                        default=auctions.voice.default_thresholds,
                        help_text="Score cutoffs: at/above 'confident' fills green, at/above 'unsure' asks, below is ignored.",
                    ),
                ),
                (
                    "auto_submit_on_sold",
                    models.BooleanField(
                        default=True, help_text="Saying 'sold' saves the lot, instead of only filling the fields."
                    ),
                ),
                (
                    "block_auto_submit_when_unsure",
                    models.BooleanField(
                        default=True,
                        help_text="Refuse to save while any field is unsure. Turning this off sells lots to bidders nobody confirmed.",
                    ),
                ),
                ("updatedon", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Voice grammar",
                "verbose_name_plural": "Voice grammar",
            },
        ),
        migrations.CreateModel(
            name="VoiceCommandLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("lot", "Lot number"),
                            ("bidder", "Bidder number"),
                            ("price", "Price"),
                            ("sold", "Sold"),
                            ("unsold", "Unsold"),
                            ("undo", "Undo"),
                            ("clear", "Clear"),
                            ("confirm", "Confirm"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "heard",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The recognizer's transcript of what was said.",
                        max_length=300,
                    ),
                ),
                (
                    "chosen",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The value the app matched it to and put in the field.",
                        max_length=100,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "corrected_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="What the operator changed the field to before saving. Blank means the match stood.",
                        max_length=100,
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("updatedon", models.DateTimeField(auto_now=True)),
                ("auction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auctions.auction")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-createdon"],
            },
        ),
    ]
