# Generated by Django 5.2.15 on 2026-08-02 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0365_voicegrammar_voicecommandlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMUsage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.CharField(blank=True, help_text="Model string reported by the provider.", max_length=100),
                ),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("query", models.CharField(blank=True, help_text="What the user typed or said.", max_length=600)),
                (
                    "response_kind",
                    models.CharField(
                        blank=True,
                        help_text="navigate, countdown, clarify, done, error, or lookup for an intermediate round.",
                        max_length=30,
                    ),
                ),
                (
                    "action",
                    models.CharField(blank=True, help_text="Registry action name, when one was chosen.", max_length=50),
                ),
                ("success", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM usage",
                "verbose_name_plural": "LLM usage",
                "ordering": ["-createdon"],
            },
        ),
    ]
