# Generated by Django 5.2.15 on 2026-08-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0366_llmusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="cached_prompt_tokens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many of the prompt tokens the provider served from its own cache. Billed at a fraction of the normal input rate, so a total that ignores this badly overstates the bill: the system prompt is the same ~3k tokens on every call and 90%+ of it is a cache hit.",
            ),
        ),
    ]
