# Generated by Django 5.2.15 on 2026-08-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0367_llmusage_cached_prompt_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="destination",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="For a navigation, the palette_routes key it landed on. This is what `manage.py mine_palette_shortcuts` reads: a query that resolves to the same destination every time never needs to be asked about again.",
                max_length=100,
            ),
        ),
    ]
