# Generated by Django 5.2.15 on 2026-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0368_llmusage_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="cancelled",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="The user hit Cancel during the confirm countdown instead of letting the action run. This is the only signal we get that we understood the words but picked the wrong thing to do -- the action never ran, so nothing else records it. A query that is repeatedly cancelled is a bad match worth fixing.",
            ),
        ),
    ]
