# Generated by Django 5.2.15 on 2026-08-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0369_llmusage_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="use_llm_search",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Let this user type or speak commands into the command palette and have a language model work out what they meant.  Off for everyone by default: it costs money per use, and with it off the palette is plain search, exactly as it was before the feature existed.  Also needs an LLM to be configured site-wide (see auctions.llm.assist_enabled).",
                verbose_name="Natural-language command palette",
            ),
        ),
    ]
