# Generated by Django 5.2.15 on 2026-08-07 12:27

import autoslug.fields
import django.db.models.deletion
import easy_thumbnails.fields
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0370_userdata_use_llm_search"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeakerTopic",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="name", unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="club",
            name="is_nec_club",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="This club belongs to the Northeast Council of Aquarium Societies.  Anyone with a permission in an NEC club can use the speaker directory.  Set this here in the Django admin only — it is deliberately absent from the club settings page so clubs can't opt themselves in.",
                verbose_name="NEC member club",
            ),
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cloudflare_image_id",
                    models.CharField(blank=True, db_index=True, default="", editable=False, max_length=100),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="The speaker's name, as you'd print it on a meeting flyer.",
                        max_length=200,
                    ),
                ),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="name", unique=True)),
                ("bio", models.TextField(blank=True, default="", help_text="A paragraph or two about the speaker.")),
                (
                    "programs",
                    models.TextField(
                        blank=True, default="", help_text="The talks this speaker offers.", verbose_name="Talks"
                    ),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True, null=True, upload_to="speakers/", verbose_name="Photo"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Only shown to people who can see the speaker directory.",
                        max_length=255,
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("website", models.URLField(blank=True, default="", max_length=500)),
                ("facebook_page", models.URLField(blank=True, default="", max_length=500)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Roughly where the speaker travels from — a town and state is plenty.",
                        max_length=500,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("longitude", models.FloatField(blank=True, db_index=True, null=True)),
                (
                    "location_coordinates",
                    location_field.models.plain.PlainLocationField(
                        blank=True, max_length=63, null=True, verbose_name="Map"
                    ),
                ),
                (
                    "nec_only",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Keeps this speaker out of the directory for clubs that aren't NEC members.  Everything imported from the NEC speaker database is set this way.",
                        verbose_name="Only show to NEC member clubs",
                    ),
                ),
                ("imported_from_nec", models.BooleanField(db_index=True, default=False, editable=False)),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        default="",
                        editable=False,
                        help_text="Where this record came from on the old NEC website.",
                        max_length=500,
                    ),
                ),
                (
                    "wordpress_post_id",
                    models.PositiveIntegerField(
                        blank=True,
                        editable=False,
                        help_text="WordPress post id, so re-running the import updates rows instead of duplicating them.",
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("lastmodified", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        help_text="The club the person adding this speaker was representing, if they picked one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_speakers",
                        to="auctions.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank for the rows imported from the NEC speaker database.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_speakers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("topics", models.ManyToManyField(blank=True, related_name="speakers", to="auctions.speakertopic")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpeakerComment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(max_length=2000)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="speaker_comments",
                        to="auctions.club",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="auctions.speaker"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="speaker_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-createdon"],
            },
        ),
        migrations.CreateModel(
            name="SpeakerTag",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("engaging", "Engaging presenter"),
                            ("visuals", "Great photos / visuals"),
                            ("funny", "Funny"),
                            ("beginners", "Good for beginners"),
                            ("technical", "In-depth / technical"),
                            ("workshop", "Hands-on workshop"),
                            ("big_crowd", "Drew a big crowd"),
                            ("book_again", "Would book again"),
                            ("remote", "Presents remotely"),
                            ("travels", "Willing to travel"),
                            ("brings_items", "Brings items for the auction"),
                            ("donates_fee", "Donates their fee back"),
                            ("no_fee", "No fee (expenses only)"),
                            ("responsive", "Quick to respond"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="auctions.speaker"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["tag"],
                "constraints": [
                    models.UniqueConstraint(fields=("speaker", "user", "tag"), name="unique_speaker_tag_per_user")
                ],
            },
        ),
    ]
