# Generated by Django 5.2.15 on 2026-08-07 15:28

import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0371_speakertopic_club_is_nec_club_speaker_speakercomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Or enter a URL to a photo instead of uploading one",
                max_length=500,
                null=True,
                verbose_name="Photo URL",
            ),
        ),
        migrations.AlterField(
            model_name="speaker",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True, help_text="Select a photo to upload", null=True, upload_to="speakers/", verbose_name="Photo"
            ),
        ),
    ]
