# Generated by Django 5.2.15 on 2026-08-07 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0372_speaker_url_alter_speaker_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The site account this speaker is, when they have one.  Linked by email address on import.  Distinct from `created_by`, which is whoever typed the record in.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="speaker_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="speakertag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("engaging", "Engaging presenter"),
                    ("visuals", "Great photos / visuals"),
                    ("funny", "Funny"),
                    ("beginners", "Good for beginners"),
                    ("technical", "In-depth / technical"),
                    ("workshop", "Hands-on workshop"),
                    ("big_crowd", "Drew a big crowd"),
                    ("book_again", "Would book again"),
                    ("remote", "Presents remotely"),
                    ("travels", "Willing to travel"),
                    ("brings_items", "Brings items for the auction"),
                    ("no_fee", "No fee (expenses only)"),
                    ("responsive", "Quick to respond"),
                    ("no_longer_speaking", "No longer speaking"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
