# Generated by Django 5.2.15 on 2026-08-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0375_merge_rift_lake_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="reported",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="The user pressed 'tell the site owner' after this command failed. Every other failure signal here is inferred; this one is a person deciding it was worth saying so, which makes it the shortest queue on the analytics page and the first one worth reading.",
            ),
        ),
    ]
