# Generated by Django 5.2.15 on 2026-08-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0376_llmusage_reported"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="topic_review_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which retired topic this speaker was on, so the fix doesn't need guesswork.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="speaker",
            name="topics_need_review",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set when this speaker's topics landed on 'Other' because the topic they were filed under has been retired.  Filter on it in the admin to work through them; untick it once the topics are right.",
                verbose_name="Topics need review",
            ),
        ),
        migrations.AlterField(
            model_name="speakertag",
            name="tag",
            field=models.CharField(
                choices=[
                    ("engaging", "Engaging presenter"),
                    ("visuals", "Great photos / visuals"),
                    ("funny", "Funny"),
                    ("beginners", "Good for beginners"),
                    ("technical", "In-depth / technical"),
                    ("workshop", "Hands-on workshop"),
                    ("big_crowd", "Drew a big crowd"),
                    ("book_again", "Would book again"),
                    ("remote", "Presents remotely"),
                    ("travels", "Willing to travel"),
                    ("brings_items", "Brings items for the auction"),
                    ("no_longer_speaking", "No longer speaking"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
