# Generated by Django 5.2.15 on 2026-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0378_retire_generic_cichlid_and_invertebrate_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicecommandlog",
            name="slot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lot", "Lot number"),
                    ("bidder", "Bidder number"),
                    ("price", "Price"),
                    ("sold", "Sold"),
                    ("unsold", "Unsold"),
                    ("undo", "Undo"),
                    ("clear", "Clear"),
                    ("confirm", "Confirm"),
                ],
                default="",
                help_text="Which field was filled. Blank means nothing matched — those are the rows to mine for new words.",
                max_length=20,
            ),
        ),
    ]
