# Generated by Django 5.2.15 on 2026-08-10 21:43

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0379_alter_voicecommandlog_slot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="donation_context",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Passed to the language model with every donation email it writes, so it doesn't have to be retyped for each vendor.",
                verbose_name="Club information for donation emails",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_email_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Incoming mail for club-slug-donations-*@your-domain is forwarded to this member.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_donation_email_destinations",
                to="auctions.clubmember",
                verbose_name="Donation contact",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_email_mode",
            field=models.CharField(
                choices=[("routed", "Send mail from this site"), ("copy", "Copy/paste to my email")],
                default="routed",
                max_length=20,
                verbose_name="How to send donation emails",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_followup_days",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1 day"), (3, "3 days"), (7, "1 week"), (14, "2 weeks"), (30, "1 month")],
                default=7,
                help_text="How long to wait for a reply before a vendor shows up as due for a follow-up.",
                verbose_name="Follow up after",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_mailing_address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Where vendors should send physical donations. Included in donation emails.",
                verbose_name="Donation mailing address",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="enable_donation_tracking",
            field=models.BooleanField(
                default=False,
                help_text="Track which vendors you've asked for donations, and what they said.",
                verbose_name="Enable donation tracking",
            ),
        ),
        migrations.AlterField(
            model_name="clubhistory",
            name="applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RULES", "Rules"),
                    ("MEMBERS", "Members"),
                    ("MEMBERSHIP", "Membership"),
                    ("SETTINGS", "Settings"),
                    ("BAP", "BAP"),
                    ("DONATIONS", "Donations"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DonationUnsubscribe",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(db_index=True, max_length=255, unique=True)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        help_text="The club whose email carried the unsubscribe link that was clicked.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="auctions.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation unsubscribe",
                "verbose_name_plural": "Donation unsubscribes",
            },
        ),
        migrations.CreateModel(
            name="DonationVendor",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Vendor name")),
                ("contact_name", models.CharField(blank=True, default="", max_length=255)),
                ("email", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("sent", "Initial email sent"),
                            ("interested", "Interested"),
                            ("promised", "Donation promised"),
                            ("received", "Donation received"),
                            ("not_interested", "Not interested"),
                            ("do_not_contact", "Do not contact"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "last_contact",
                    models.DateTimeField(
                        blank=True, help_text="When this vendor was last emailed, or last replied.", null=True
                    ),
                ),
                (
                    "followup_due",
                    models.DateTimeField(
                        blank=True, help_text="When to chase this vendor again if they haven't replied.", null=True
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What this vendor does, any history of donations, and anything else worth telling the model.",
                    ),
                ),
                (
                    "routing_key",
                    models.CharField(
                        db_index=True,
                        default=auctions.models._default_donation_routing_key,
                        editable=False,
                        help_text="Identifies this vendor in the reply-to address so their replies land on their row.",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                (
                    "unsubscribed",
                    models.BooleanField(
                        default=False,
                        help_text="The vendor used the unsubscribe link. Permanent, and applies to every club on this site.",
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="donation_vendors", to="auctions.club"
                    ),
                ),
                (
                    "createdby",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DonationEmail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "direction",
                    models.CharField(choices=[("in", "Incoming"), ("out", "Outgoing")], db_index=True, max_length=3),
                ),
                ("sender", models.CharField(blank=True, default="", max_length=255)),
                ("recipients", models.CharField(blank=True, default="", max_length=1000)),
                ("subject", models.CharField(blank=True, default="", max_length=500)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="One-line summary, written by the language model for incoming mail.",
                        max_length=200,
                    ),
                ),
                ("date", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="The Message-ID header, used to drop duplicates when a message is delivered twice.",
                        max_length=500,
                    ),
                ),
                (
                    "bounced",
                    models.BooleanField(
                        default=False, help_text="Set when a bounce notification comes back for this message."
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emails", to="auctions.donationvendor"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="donationvendor",
            index=models.Index(fields=["club", "status"], name="auctions_do_club_id_45dd19_idx"),
        ),
    ]
