# Generated by Django 5.2.15 on 2026-08-11 16:57

from django.db import migrations, models


def grant_to_current_donation_staff(apps, schema_editor):
    """Give the new permission to whoever was already managing donations.

    Until now the donation pages were gated on ``permission_add_edit``, so "manages the member list"
    was the only way a club could express "may write to vendors" -- nobody chose between the two.
    Anyone holding that permission in a club with tracking switched on is doing this job today, and
    a rename of their permission shouldn't lock them out of it mid-campaign.

    Deliberately limited to clubs with ``enable_donation_tracking`` on: everywhere else the grant
    would be inventing an intent no admin ever had, on a permission they've never seen.
    """
    ClubMember = apps.get_model("auctions", "ClubMember")
    ClubMember.objects.filter(
        club__enable_donation_tracking=True,
        permission_add_edit=True,
        is_deleted=False,
    ).update(permission_manage_donations=True)


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0380_club_donation_context_club_donation_email_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="permission_manage_donations",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Add and email donation vendors.  Separate from member management: it sends "
                    "mail in the club's name."
                ),
            ),
        ),
        migrations.RunPython(grant_to_current_donation_staff, migrations.RunPython.noop),
    ]
