"""Turn the never-populated ``Product`` stub into a real ``Species`` table.

Written by hand rather than autogenerated so it is a *rename*: ``Lot.species`` has always been a
foreign key to this table, and the handful of rows anyone did create keep their primary keys
instead of being dropped and rebuilt underneath those lots.

Also switches the scientific name on by default for auctions that already exist -- the field is
new, so no lot has a species yet and no label changes shape until a seller picks one, but a club
that never visits the label settings should still get the behaviour the default promises.
"""

import django.db.models.deletion
from django.db import migrations, models

OLD_LABEL_DEFAULT = (
    "qr_code,lot_name,min_bid_label,buy_now_label,quantity_label,seller_name,donation_label,"
    "custom_field_1,i_bred_this_fish_label,custom_checkbox_label,custom_dropdown_label"
)


def enable_scientific_name_on_labels(apps, schema_editor):
    """Append ``scientific_name`` to every auction's label field list.

    A no-op on the printed page until a lot actually has a species, and an admin who doesn't want
    it can untick it in the auction's label settings like any other field.
    """
    Auction = apps.get_model("auctions", "Auction")
    for auction in Auction.objects.exclude(label_print_fields__contains="scientific_name").iterator():
        fields = [field for field in (auction.label_print_fields or "").split(",") if field]
        if not fields:
            continue
        # Right after the lot name, matching where it prints.
        position = fields.index("lot_name") + 1 if "lot_name" in fields else len(fields)
        fields.insert(position, "scientific_name")
        auction.label_print_fields = ",".join(fields)
        auction.save(update_fields=["label_print_fields"])


def remove_scientific_name_from_labels(apps, schema_editor):
    Auction = apps.get_model("auctions", "Auction")
    for auction in Auction.objects.filter(label_print_fields__contains="scientific_name").iterator():
        fields = [field for field in (auction.label_print_fields or "").split(",") if field != "scientific_name"]
        auction.label_print_fields = ",".join(fields)
        auction.save(update_fields=["label_print_fields"])


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0381_clubmember_permission_manage_donations"),
    ]

    operations = [
        # A plain RenameModel would also drop and re-add auctions_lot's foreign key so its name
        # stops saying "product". Two reasons not to let it: that is a schema rewrite on one of
        # the biggest tables on the site to fix a constraint *name*, and every foreign key in this
        # database is recorded under a mangled `table?constraint` name that MariaDB then refuses
        # to DROP by that name. RENAME TABLE repoints the foreign key on its own -- the constraint
        # keeps its old name, which is cosmetic and costs nothing.
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.RenameModel(old_name="Product", new_name="Species")],
            database_operations=[
                migrations.RunSQL(
                    sql="RENAME TABLE `auctions_product` TO `auctions_species`",
                    reverse_sql="RENAME TABLE `auctions_species` TO `auctions_product`",
                )
            ],
        ),
        migrations.AlterModelOptions(
            name="species",
            options={"ordering": ["scientific_name"], "verbose_name_plural": "Species"},
        ),
        migrations.AlterField(
            model_name="species",
            name="common_name",
            field=models.CharField(
                blank=True, help_text="The name usually used to describe this species", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="scientific_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Genus and species together; filled in automatically, don't edit by hand",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auctions.category",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="genus",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="First half of the scientific name, e.g. Poecilia",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="species",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Second half of the scientific name (the specific epithet), e.g. reticulata",
                max_length=150,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="speccode",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "SpecCode from the source database, used to match rows on re-import.  Blank for hand-added species."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="source",
            field=models.CharField(
                choices=[
                    ("fishbase", "FishBase"),
                    ("sealifebase", "SeaLifeBase"),
                    ("manual", "Added by hand"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="freshwater",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="species",
            name="brackish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="species",
            name="saltwater",
            field=models.BooleanField(default=False),
        ),
        # After the columns exist, not before.
        migrations.AlterUniqueTogether(
            name="species",
            unique_together={("source", "speccode")},
        ),
        # State-only.  RenameModel already repointed this foreign key at the renamed table, and
        # everything left to change here (verbose_name, help_text, the ``to=`` label) lives in
        # Django's model state, not the schema.  Letting Django emit the ALTER anyway would drop
        # and rebuild a foreign key on auctions_lot -- one of the largest tables on the site --
        # for no schema change at all.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="lot",
                    name="species",
                    field=models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Start typing a lot name and pick from the list.  Leave as No species for hardware "
                            "and other non-living lots."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auctions.species",
                        verbose_name="Scientific name",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="auction",
            name="use_scientific_name",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text=(
                    "Suggest a species based on the lot name.  Users pick from a short list, or No species "
                    "for hardware and other non-living lots."
                ),
                verbose_name="Use scientific name field",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="label_print_fields",
            field=models.CharField(
                blank=True,
                default=(
                    "qr_code,lot_name,scientific_name,min_bid_label,buy_now_label,quantity_label,seller_name,"
                    "donation_label,custom_field_1,i_bred_this_fish_label,custom_checkbox_label,"
                    "custom_dropdown_label"
                ),
                max_length=1000,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SpeciesCommonName",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("language", models.CharField(blank=True, default="English", max_length=50)),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="FishBase's primary name for this species in this language.  Ranked first.",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_names",
                        to="auctions.species",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddIndex(
            model_name="speciescommonname",
            index=models.Index(fields=["name", "is_preferred"], name="auctions_sp_name_84cf7b_idx"),
        ),
        migrations.CreateModel(
            name="SpeciesSearchCache",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "search_text",
                    models.CharField(
                        help_text="Normalised lot name: lowercased, punctuation stripped.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("llm", "Language model"), ("user", "Chosen by a user")],
                        default="llm",
                        max_length=20,
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "hits",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many times this cached answer has been served instead of asking again.",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auctions.species",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubBapGenusOverride",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "genus",
                    models.CharField(
                        help_text="The first half of a scientific name, e.g. Tropheus.  Applies to every species in it.",
                        max_length=100,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("created_on", models.DateField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bap_genus_overrides",
                        to="auctions.club",
                    ),
                ),
            ],
            options={"ordering": ["genus"], "unique_together": {("club", "genus")}},
        ),
        migrations.RunPython(enable_scientific_name_on_labels, remove_scientific_name_from_labels),
    ]
