# Generated by Django 5.2.15 on 2026-08-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0382_species_from_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="species",
            name="common_name",
            field=models.CharField(
                blank=True, db_index=True, help_text="The name usually used to describe this species", max_length=255
            ),
        ),
    ]
