# Generated by Django 5.2.16 on 2026-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0386_species_trade_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="common_name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="common_name with the punctuation stripped, so a typed lot name can match it.  Rebuilt on save; don't edit by hand.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="speciescommonname",
            name="name_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="What lookups match on: name with the punctuation stripped, by normalize_species_name.  Rebuilt on save; the importers fill it in on the bulk paths, which skip save().",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="points_per_lot",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Default BAP points for every lot. Override these with per-category points below. Leave blank to use the per-category points instead; set it to 0 to award nothing by default.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="bap_auto_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_eligible", "Not eligible"),
                    ("not_long_enough", "Not long enough since last submission"),
                    ("category_not_eligible", "Category not eligible (BAP points = 0)"),
                    ("species_not_eligible", "Species not eligible for breeder points"),
                    ("not_club_member", "Not a club member"),
                    ("not_bred", "Didn't breed this fish"),
                    ("not_active_member", "Not an active club member"),
                    ("not_sold", "Not sold"),
                    ("low_quantity", "Quantity below club minimum"),
                    ("not_donation", "Lot is not a donation"),
                    ("has_min_bid", "Lot has a minimum bid set"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="breeder_points",
            field=models.BooleanField(
                default=True,
                help_text="Untick to make a lot with this species ineligible for breeder points, whatever its category.  For the things a club won't award points for breeding -- wild-caught only species, or anything that isn't really bred.",
                verbose_name="Eligible for breeder points",
            ),
        ),
        migrations.AlterField(
            model_name="species",
            name="source",
            field=models.CharField(
                choices=[
                    ("fishbase", "FishBase"),
                    ("sealifebase", "SeaLifeBase"),
                    ("aquarium", "Aquarium trade list"),
                    ("admin", "Added on the site"),
                    ("manual", "Added by hand"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="speciescommonname",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="As the source spells it, punctuation and all.  This is what a person reads.",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="speciescommonname",
            index=models.Index(fields=["name_normalized", "is_preferred"], name="auctions_sp_name_no_196d62_idx"),
        ),
    ]
