# Generated by Django 5.2.16 on 2026-08-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0388_normalize_species_names_and_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubapikey",
            name="can_look_up_species",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Turn a typed name ('yellow lab') into a species from this site's list, using "
                    "the same matcher the add-lot form uses.  Read-only, and the species list is "
                    "not club data, but it is off unless a club asks for it like every other "
                    "permission here."
                ),
            ),
        ),
    ]
