# Generated by Django 5.2.16 on 2026-08-17 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

#: Species per statement when stamping the existing common names.
#:
#: Batched on the *species* primary key rather than written as one update per source, which is
#: what this did first and is worth not doing again: ``filter(species__source="fishbase")`` is a
#: subquery over 36,000 species for every one of 49,000 names, and it ran for the better part of
#: an hour on a laptop while holding a metadata lock on the table.  An explicit list of ids hits
#: the foreign key index instead and the whole thing is seconds.
BATCH_SIZE = 2000


def stamp_existing_names(apps, schema_editor):
    """Give every common name already in the table the source of the species it hangs off.

    Which is true by construction: until now the only writers were ``import_fishbase`` (fishbase
    and sealifebase rows), ``aquarium_species.load`` (its own rows) and ``SpeciesAdminForm``
    (``admin`` rows), and each of them only ever wrote names for species it had just written
    itself.  Leaving them all at the ``manual`` default would be wrong in the one way that
    matters: the FishBase importer deletes ``source="fishbase"`` names, so 49,000 real FishBase
    names would survive the next import as duplicates of themselves.
    """
    SpeciesCommonName = apps.get_model("auctions", "SpeciesCommonName")
    Species = apps.get_model("auctions", "Species")
    # order_by() first, and it is load-bearing.  Species.Meta.ordering puts scientific_name and
    # variety into the SELECT DISTINCT, so without clearing it this "list of sources" is one row
    # per species -- 139,000 of them, every one of them the string "fishbase" or "aquarium" -- and
    # the loop below runs 139,000 times instead of twice.
    for source in Species.objects.order_by().values_list("source", flat=True).distinct():
        pks = list(Species.objects.filter(source=source).values_list("pk", flat=True))
        for index in range(0, len(pks), BATCH_SIZE):
            SpeciesCommonName.objects.filter(species_id__in=pks[index : index + BATCH_SIZE]).exclude(
                source=source
            ).update(source=source)


def unstamp(apps, schema_editor):
    """Nothing to undo -- the column goes away with the reverse of AddField."""


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0389_clubapikey_can_look_up_species"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who added this on the site.  Blank for everything the importers loaded.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="approved",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Untick to keep this species out of everyone's suggestions except the person who added it.  That is how an auction admin gets a missing species onto their own lots at the check-in table without adding it to the whole site; ticking it here is the approval.",
            ),
        ),
        migrations.AddField(
            model_name="speciescommonname",
            name="source",
            field=models.CharField(
                choices=[
                    ("fishbase", "FishBase"),
                    ("sealifebase", "SeaLifeBase"),
                    ("aquarium", "Aquarium trade list"),
                    ("admin", "Added on the site"),
                    ("manual", "Added by hand"),
                ],
                db_index=True,
                default="manual",
                help_text="Which list wrote this name.  An importer only ever deletes its own, so a name added here or in aquarium_species.csv survives the next re-import of FishBase.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="speciessearchcache",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who taught the site this answer, when a person did.  Blank for the language model.  Every row here is served to every club, so a wrong one needs to be traceable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_names_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(stamp_existing_names, unstamp),
    ]
