# Generated by Django 5.2.16 on 2026-08-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0390_species_added_by_species_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="The club this was added for, when there was an obvious one.  While the species is unapproved this is the second way it can be seen: the person who added it always can, and so can anyone else at the same club.  Often blank -- plenty of auctions have no club attached at all -- which is why it can never be the *only* way in.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_added",
                to="auctions.club",
            ),
        ),
    ]
