# Generated by Django 5.2.16 on 2026-08-17 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0391_species_club"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="speciescommonname",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who added this on the site.  Blank for everything the importers loaded.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_names_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="speciescommonname",
            name="approved",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Off means only the person or club that added it is offered it.  Everything imported is on.",
            ),
        ),
        migrations.AddField(
            model_name="speciescommonname",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="The club this was added for, when there was an obvious one.  See Species.club.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species_names_added",
                to="auctions.club",
            ),
        ),
        migrations.AlterField(
            model_name="clubapikey",
            name="can_look_up_species",
            field=models.BooleanField(
                default=False,
                help_text='Turns a typed name ("yellow lab") into a species from this site\'s list, add new species or attach common names to existing species.  Newly added species are only visible to your club.',
            ),
        ),
    ]
