# Generated by Django 5.2.16 on 2026-08-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0392_speciescommonname_added_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="days_between_same_species_lots",
            field=models.IntegerField(
                default=0,
                help_text="Minimum days between awarding BAP points for lots with the same scientific name. Leave at 0 to allow points every time. Stricter than the rule above, because it sees through what the lot was called: “Yellow labs” and “Labidochromis caeruleus” are the same fish. A named strain counts as its own species, so blue and red cherry shrimp both earn points.",
                verbose_name="Days between same species lots",
            ),
        ),
    ]
