# Generated by Django 5.2.16 on 2026-08-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0393_club_days_between_same_species_lots"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="possible_duplicate",
            field=models.ForeignKey(
                blank=True,
                help_text="Another row that looks like this one -- same scientific name, or the same common name.  Set automatically on save; the pair is listed on the species gaps page for a site admin to merge or dismiss.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="auctions.species",
            ),
        ),
        migrations.AddField(
            model_name="speciessearchcache",
            name="accepts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lots saved with this answer left alone.  Counted once per lot, on the save that created it -- re-saving a lot without touching the species is not new evidence.",
            ),
        ),
        migrations.AddField(
            model_name="speciessearchcache",
            name="rejects",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Times somebody cleared this answer or picked a different species for a lot with this name.  Enough of them retires the row; see is_discredited.",
            ),
        ),
        migrations.CreateModel(
            name="SpeciesNameRejection",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "search_text",
                    models.CharField(
                        db_index=True,
                        help_text="Normalised lot name, the same key SpeciesSearchCache uses.",
                        max_length=120,
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_rejections",
                        to="auctions.species",
                    ),
                ),
            ],
            options={
                "unique_together": {("search_text", "species")},
            },
        ),
    ]
