# Generated by Django 5.2.16 on 2026-08-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0394_species_possible_duplicate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="is_hybrid",
            field=models.BooleanField(
                default=False,
                help_text="A cross with no accepted scientific name -- a tibee shrimp, a flowerhorn.  Put the name the trade uses in variety; genus, species and parent are left empty.",
            ),
        ),
        migrations.AlterField(
            model_name="speciessearchcache",
            name="rejects",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lots this answer was cleared from or changed on.  Counted once per lot, like accepts.  Enough of them retires the row; see is_discredited.",
            ),
        ),
    ]
