# Generated by Django 5.2.16 on 2026-08-19 19:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0395_species_is_hybrid_alter_speciessearchcache_rejects"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mobiledevice",
            name="ever_print_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="last_heartbeat",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="print_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mobiledevice",
            name="printer_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userlabelprefs",
            name="print_from_computer",
            field=models.BooleanField(
                default=False,
                help_text="When you print labels on a computer, send them to the printer paired with your phone instead of making a PDF. <b>The app has to be open on your phone.</b>",
                verbose_name="Print from my computer to my phone",
            ),
        ),
        migrations.CreateModel(
            name="RemotePrintJob",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("lots", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent to the phone"),
                            ("printing", "Printing"),
                            ("printed", "Printed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("unreachable", "Couldn't reach the phone"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("printed_count", models.IntegerField(default=0)),
                ("total_count", models.IntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to="auctions.mobiledevice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_print_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "-created_at"], name="auctions_re_user_id_4b26c8_idx")],
            },
        ),
    ]
