# Generated by Django 5.2.16 on 2026-08-20 02:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0396_mobiledevice_ever_print_ready_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="announcement_channel_id",
            field=models.CharField(
                blank=True,
                help_text="Discord channel ID for club announcements. Set via /announcements_here.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ClubAnnouncement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "text",
                    models.TextField(
                        help_text="A sentence or two. This is read on a phone lock screen, not on a page.",
                        verbose_name="Announcement",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("send_to_discord", models.BooleanField(default=False)),
                ("send_to_push", models.BooleanField(default=False)),
                ("show_on_website", models.BooleanField(default=True)),
                (
                    "discord_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Discord accepted the message. False with send_to_discord set means it failed.",
                    ),
                ),
                ("discord_message_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "push_recipients",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many members the push was handed to. Delivery, not readership — see the view table.",
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="announcements", to="auctions.club"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClubAnnouncementView",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_key", models.CharField(blank=True, default=None, max_length=40, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="auctions.clubannouncement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="clubannouncement",
            index=models.Index(fields=["club", "is_deleted", "-created_at"], name="auctions_cl_club_id_1e7e4f_idx"),
        ),
        migrations.AddConstraint(
            model_name="clubannouncementview",
            constraint=models.UniqueConstraint(fields=("announcement", "user"), name="unique_announcement_view_user"),
        ),
        migrations.AddConstraint(
            model_name="clubannouncementview",
            constraint=models.UniqueConstraint(
                fields=("announcement", "session_key"), name="unique_announcement_view_session"
            ),
        ),
    ]
