# Generated by Django 5.2.16 on 2026-08-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0397_club_announcement_channel_id_clubannouncement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="brevo_sender_id",
            field=models.CharField(
                blank=True,
                help_text="Which of the account's verified senders announcement emails go out as. Blank means the first active one, which is the only one most accounts have.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="clubannouncement",
            name="brevo_campaign_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="clubannouncement",
            name="email_error",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why the email didn't go out. Set means the campaign failed; the club needs to see it.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="clubannouncement",
            name="email_opens",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Unique opens reported by the email provider. The only real read receipt any channel has.",
            ),
        ),
        migrations.AddField(
            model_name="clubannouncement",
            name="mailchimp_campaign_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="clubannouncement",
            name="send_to_brevo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clubannouncement",
            name="send_to_mailchimp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clubannouncement",
            name="subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subject line for the emailed version. Blank uses the first line of the announcement.",
                max_length=150,
                verbose_name="Email subject",
            ),
        ),
    ]
