# Generated by Django 5.2.16 on 2026-08-20 15:01

from django.db import migrations, models


def grant_to_whoever_is_already_posting(apps, schema_editor):
    """Give the new permission to everyone who could write an announcement yesterday.

    Announcements shipped gated on ``permission_manage_auctions`` -- "the person who tells members
    when the meeting is". Splitting it out is about the blast radius (Discord, every member's phone
    and the club's mailing list, in one press), not about deciding those people were wrong, so
    nobody should lose the page underneath them mid-week. Club admins already hold everything.
    """
    ClubMember = apps.get_model("auctions", "ClubMember")
    ClubMember.objects.filter(permission_manage_auctions=True, is_deleted=False).update(
        permission_send_announcements=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0398_club_brevo_sender_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="permission_send_announcements",
            field=models.BooleanField(
                default=False,
                help_text="Write club announcements.  Its own permission because an announcement goes straight to Discord, members' phones and the club's mailing list with nobody in between.",
            ),
        ),
        migrations.RunPython(grant_to_whoever_is_already_posting, migrations.RunPython.noop),
    ]
