# Generated by Django 5.2.16 on 2026-08-20 15:30

from django.conf import settings
from django.db import migrations, models


def everything_already_here_was_sent(apps, schema_editor):
    """Backfill sent_at from created_at.

    Until now an announcement was written and delivered in the same request, so created_at *was*
    the send time. sent_at is null for "scheduled and not sent yet", and everything public filters
    on it -- leaving the existing rows null would hide every announcement a club has ever sent from
    its own website the moment this deploys.
    """
    ClubAnnouncement = apps.get_model("auctions", "ClubAnnouncement")
    ClubAnnouncement.objects.filter(sent_at__isnull=True).update(sent_at=models.F("created_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0399_clubmember_permission_send_announcements"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clubannouncement",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Leave blank to send now. A club writes the reminder when it thinks of it, not at 9am Friday.",
                null=True,
                verbose_name="Send later",
            ),
        ),
        migrations.AddField(
            model_name="clubannouncement",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When it actually went out. Null means scheduled and not sent yet -- nothing may show it.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="clubannouncement",
            index=models.Index(fields=["sent_at", "scheduled_for"], name="auctions_cl_sent_at_9093af_idx"),
        ),
        migrations.RunPython(everything_already_here_was_sent, migrations.RunPython.noop),
    ]
