# Generated by Django 5.2.16 on 2026-08-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """Announcements lose their own page, and gain their own club-history category.

    ``ClubAnnouncementView`` counted people opening an announcement's page.  Nothing links to that
    page any more -- every channel carries the whole announcement, so there was never anything
    behind the link -- which leaves the table counting an event that can no longer happen.  It has
    only ever existed on this branch, so there is nothing here worth keeping.

    ``ANNOUNCEMENTS`` is a choices-only change (no DB change on MariaDB): announcement rows were
    filed under ``SETTINGS``, alongside "connected PayPal" and "updated club settings", which is
    not what sending a message to every member is.
    """

    dependencies = [
        ("auctions", "0400_clubannouncement_scheduling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubhistory",
            name="applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RULES", "Rules"),
                    ("MEMBERS", "Members"),
                    ("MEMBERSHIP", "Membership"),
                    ("SETTINGS", "Settings"),
                    ("BAP", "BAP"),
                    ("DONATIONS", "Donations"),
                    ("ANNOUNCEMENTS", "Announcements"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ClubAnnouncementView",
        ),
    ]
