# Generated by Django 5.2.16 on 2026-08-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0401_alter_clubhistory_applies_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubannouncement",
            name="website_views",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many times this was rendered on a website -- the club's own page here, or one of its embeds. An impression, not a read: it says the announcement was put in front of somebody, which is a weaker claim than the email provider's open count.",
            ),
        ),
        migrations.AlterField(
            model_name="clubannouncement",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When it goes out. Blank on the form means a few seconds from now.",
                null=True,
                verbose_name="Send later",
            ),
        ),
        migrations.AlterField(
            model_name="clubannouncement",
            name="subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Blank uses the first line of the announcement.",
                max_length=150,
                verbose_name="Email subject",
            ),
        ),
        migrations.AlterField(
            model_name="clubannouncement",
            name="text",
            field=models.TextField(
                help_text="A sentence or two — this is read on a lock screen.", verbose_name="Announcement"
            ),
        ),
    ]
