# Generated by Django 5.2.16 on 2026-08-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0402_clubannouncement_website_views_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubannouncement",
            name="subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Legacy. Subjects are now always '<Club> announcement' -- see email_subject.",
                max_length=150,
                verbose_name="Email subject",
            ),
        ),
    ]
