# Generated by Django 5.2.16 on 2026-08-21 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0403_alter_clubannouncement_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAPIKey",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="What this key is for, e.g. 'Claude on my laptop'", max_length=100),
                ),
                ("prefix", models.CharField(db_index=True, max_length=12, unique=True)),
                ("key_hash", models.CharField(db_index=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allow_writes",
                    models.BooleanField(
                        default=False,
                        help_text="Let this key add and change things — lots, check-ins, invoices, members. Off by default: a key that can only read is a much smaller thing to lose. Either way it can never do anything you couldn't do yourself.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stop accepting this key after this date. Blank means it never expires on its own.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rate_limit",
                    models.IntegerField(
                        blank=True, help_text="Max requests per hour. Blank = site default.", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
