# Generated by Django 5.2.17 on 2026-08-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0404_mcp_user_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="google_calendar_public_checked",
            field=models.DateTimeField(
                blank=True,
                help_text="When we last asked Google whether this calendar is shared. See google_calendar.refresh_public_flag.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="google_calendar_is_public",
            field=models.BooleanField(
                default=False,
                help_text="Whether the calendar is shared publicly in Google Calendar. Derived, not typed: we can't change sharing ourselves — that needs a scope granting access to all of their calendars — but a shared calendar has a public iCal feed, so every sync asks for it the way a member would. It only controls whether we advertise the Google links.",
                verbose_name="This calendar is shared publicly",
            ),
        ),
    ]
