# Generated by Django 5.2.17 on 2026-08-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0405_club_google_calendar_public_checked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubevent",
            name="description_is_custom",
            field=models.BooleanField(
                default=False, help_text="The same, for the description. Cleared, the auction's own blurb comes back."
            ),
        ),
        migrations.AddField(
            model_name="clubevent",
            name="title_is_custom",
            field=models.BooleanField(
                default=False,
                help_text="Set when a club admin typed this event's title by hand. Only means anything on a generated event, where it stops sync_one_auction_event overwriting it again.",
            ),
        ),
    ]
