# Generated by Django 5.2.17 on 2026-08-22 01:43

from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0406_clubevent_description_is_custom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="use_llm_search",
            field=models.BooleanField(
                blank=True,
                default=auctions.models.get_default_use_llm_search,
                help_text="Let this user talk to the site in plain English -- typing or speaking into the command palette, and connecting Claude or another assistant to their account (see /account/api-keys/).  Off for everyone by default; turn it on site-wide with `manage.py change_assistant on`.  The command palette half also needs an LLM configured site-wide (auctions.llm.assist_enabled); the connected-app half does not, because the assistant brings its own.",
                verbose_name="AI assistant and connected apps",
            ),
        ),
    ]
