# Generated by Django 5.2.17 on 2026-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0407_assistant_flag_rename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="promote_this_auction",
            field=models.BooleanField(default=False, help_text="Show this to everyone in the list of auctions"),
        ),
    ]
