# Generated by Django 5.2.17 on 2026-08-22 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0408_alter_auction_promote_this_auction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantSkillRequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "skill",
                    models.CharField(
                        db_index=True, help_text="What the tool would be called, in the caller's words.", max_length=100
                    ),
                ),
                ("params", models.TextField(blank=True, default="", help_text="What it would need to be told.")),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What the user was actually trying to do, and what happened instead.",
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which assistant asked: the OAuth application's name, the API key's, or the command palette.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("planned", "Planned"), ("done", "Built"), ("declined", "Not doing")],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Site admin's note. Not shown to the person who asked."
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedon", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant skill request",
                "ordering": ["-createdon"],
            },
        ),
    ]
