# Generated by Django 5.2.17 on 2026-08-22 23:02

from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0409_assistantskillrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="use_llm_search",
            field=models.BooleanField(
                blank=True,
                default=auctions.models.get_default_use_llm_search,
                help_text="Let this user talk to the site in plain English by typing or speaking into the command palette.  Off for everyone by default; turn it on site-wide with `manage.py change_assistant on`.  Also needs an LLM configured site-wide (auctions.llm.assist_enabled), because every command spends this site's own budget.  This does NOT gate connecting Claude or another assistant over MCP (/ai/), which is open to everyone: an agent brings its own model and costs this site nothing.",
                verbose_name="AI command palette",
            ),
        ),
    ]
