# Generated by Django 5.2.17 on 2026-08-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0410_alter_userdata_use_llm_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="dismissed_customize_event_banner",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Set when an admin dismissed the prompt to write this auction's own calendar wording. Deliberately not in AUCTION_FIELDS_TO_CLONE: next year's auction gets a new event and the same generated sentence, which is the thing worth asking about again.",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="events_website_last_view",
            field=models.DateTimeField(
                blank=True,
                help_text="When the events embed was last asked for. A club that took the snippet down stops counting, so this is what separates 'embeds our events' from 'tried it once in 2024'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="events_website_views",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many times this club's events embed has been rendered on a website. An impression, not a read, and evidence the snippet is installed somewhere.",
            ),
        ),
    ]
