# Generated by Django 5.2.17 on 2026-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0411_auction_dismissed_customize_event_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="agent_only",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Keep this off the FAQ page, but let the site's assistant answer out of it. For answers worth having written down that are not worth a heading on a public page: an edge case, something only an auction admin ever hits, or a question people ask an assistant and never a page. It is not private -- anyone can reach it by asking.",
            ),
        ),
    ]
