# Generated by Django 5.2.17 on 2026-08-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0412_faq_agent_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionhistory",
            name="applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RULES", "Rules"),
                    ("USERS", "Users"),
                    ("INVOICES", "Invoices"),
                    ("LOTS", "Lots"),
                    ("STATS", "Stats"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
