# Generated by Django 5.2.17 on 2026-08-28 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0413_alter_auctionhistory_applies_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="enable_club_page",
        ),
    ]
