# Generated by Django 5.2.17 on 2026-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0415_assistant_on_by_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubapikey",
            name="can_read_auction_info",
            field=models.BooleanField(
                default=False, help_text="Read this club's auctions: dates, rules, fees, pickup locations and settings."
            ),
        ),
        migrations.AddField(
            model_name="clubapikey",
            name="can_read_private_lots",
            field=models.BooleanField(
                default=False,
                help_text="Include the buyer and seller of each lot.  Don't use a key with this on a public page.",
            ),
        ),
        migrations.AddField(
            model_name="clubapikey",
            name="can_read_public_lots",
            field=models.BooleanField(
                default=False, help_text="Read the lots in this club's auctions, without anything that names a person."
            ),
        ),
    ]
