# Generated by Django 5.2.17 on 2026-08-29 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0416_clubapikey_can_read_auction_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="code_to_add_lots",
        ),
    ]
