# Generated by Django 5.2.17 on 2026-09-01 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0418_drop_orphan_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TapToPayAttempt",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_id", models.CharField(max_length=45, unique=True)),
                ("createdon", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("captured", "Captured"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("payment_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tap_to_pay_attempts",
                        to="auctions.invoice",
                    ),
                ),
            ],
        ),
    ]
