# Generated by Django 5.2.17 on 2026-09-03 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0420_account_menu_copy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdata",
            name="username_is_email_warning_sent",
        ),
    ]
