# Generated by Django 5.2.17 on 2026-09-03 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0421_remove_userdata_username_is_email_warning_sent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="bap_ytd_reset_year",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                help_text="The last year this club's year-to-date award counters were zeroed.  Written by tasks.reset_yearly_bap_counters, which is what makes the reset a fact about the club rather than something that only happens if a nightly task lands on January 1.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(fields=["ip_address", "-date_start"], name="pageview_ip_recent_idx"),
        ),
    ]
