# Generated by Django 5.2.17 on 2026-09-07 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0423_query_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="image_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTUAL", "My photo of this exact item"),
                    ("REPRESENTATIVE", "My photo, but not of this exact item.  e.x. This is the parents of these fry"),
                    ("RANDOM", "Not my photo - I have permission to use it"),
                ],
                help_text="Where did you get this image?",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lotimage",
            name="image_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACTUAL", "My photo of this exact item"),
                    ("REPRESENTATIVE", "My photo, but not of this exact item.  e.x. This is the parents of these fry"),
                    ("RANDOM", "Not my photo - I have permission to use it"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="Where the reported content was, recorded when the report came in",
                        max_length=500,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("OFFENSIVE", "Offensive, abusive, or harassing"),
                            ("PROHIBITED", "An animal or item that shouldn't be sold here"),
                            ("MISLEADING", "Misleading or dishonest listing"),
                            ("SPAM", "Spam or a scam"),
                            ("OTHER", "Something else"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=5000)),
                (
                    "reporter_email",
                    models.EmailField(
                        blank=True,
                        help_text="Filled in when the report came from somebody who wasn't signed in",
                        max_length=254,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("ACTIONED", "Actioned"), ("DISMISSED", "Dismissed")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("resolved_on", models.DateTimeField(blank=True, null=True)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="auctions.lot"
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-createdon"],
            },
        ),
        migrations.CreateModel(
            name="CopyrightNotice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(max_length=500)),
                (
                    "on_behalf_of",
                    models.CharField(
                        blank=True,
                        help_text="The copyright owner, if the sender is an agent acting for them",
                        max_length=200,
                    ),
                ),
                ("work", models.TextField(max_length=5000)),
                ("material", models.TextField(max_length=5000)),
                ("good_faith", models.BooleanField(default=False)),
                ("accurate", models.BooleanField(default=False)),
                ("signature", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received - not yet acted on"),
                            ("REMOVED", "Material removed"),
                            ("INVALID", "Rejected - not a valid notice"),
                            ("COUNTERED", "Counter-notice received"),
                            ("RESTORED", "Material restored after counter-notice"),
                            ("WITHDRAWN", "Withdrawn by the sender"),
                        ],
                        default="RECEIVED",
                        max_length=10,
                    ),
                ),
                (
                    "received_on",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the designated agent received it. Leave blank for notices sent through the form.",
                        null=True,
                    ),
                ),
                ("actioned_on", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("counter_notice_on", models.DateTimeField(blank=True, null=True)),
                ("counter_notice_signature", models.CharField(blank=True, max_length=100)),
                ("counter_notice_contact", models.TextField(blank=True, max_length=500)),
                ("counter_notice_text", models.TextField(blank=True, max_length=5000)),
                ("counter_notice_consents_to_jurisdiction", models.BooleanField(default=False)),
                ("restore_no_earlier_than", models.DateTimeField(blank=True, null=True)),
                ("restore_no_later_than", models.DateTimeField(blank=True, null=True)),
                ("restored_on", models.DateTimeField(blank=True, null=True)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="The lot the material was on, when it could be worked out from the URLs given",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auctions.lot",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copyright_notices_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-createdon"],
            },
        ),
        migrations.CreateModel(
            name="CopyrightStrike",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.TextField(blank=True, max_length=2000)),
                (
                    "withdrawn",
                    models.BooleanField(
                        default=False,
                        help_text="A withdrawn strike stays on the record but stops counting towards termination",
                    ),
                ),
                ("withdrawn_reason", models.TextField(blank=True, max_length=2000)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copyright_strikes_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auctions.copyrightnotice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copyright_strikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-createdon"],
            },
        ),
    ]
