# Generated by Django 5.2.17 on 2026-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0425_page_view_url_to_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionhistory",
            name="changed_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="clubhistory",
            name="changed_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
