# Generated by Django 5.2.17 on 2026-09-08 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0426_history_changed_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormFailure",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "form_name",
                    models.CharField(
                        db_index=True, help_text="The form class that rejected the submission", max_length=100
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Site-relative path, the same shape as PageView.url",
                        max_length=600,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Who to join attempts up by when there is no user, as in PageView",
                        max_length=100,
                    ),
                ),
                (
                    "field_errors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{field name: [error code, ...]} -- codes only, never messages or values",
                    ),
                ),
                (
                    "attempt",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="How many consecutive rejections this person has had on this form"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Set when the same person later submits the same form successfully"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [models.Index(fields=["form_name", "resolved"], name="auctions_fo_form_na_27becd_idx")],
            },
        ),
    ]
