# Generated by Django 5.2.17 on 2026-09-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0427_form_failure"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubHealth",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("empty", "No auctions"),
                            ("trial", "Test auctions only"),
                            ("new", "First real auction"),
                            ("active", "Running to its own schedule"),
                            ("slipping", "Late against its own schedule"),
                            ("dormant", "Stopped"),
                        ],
                        db_index=True,
                        default="empty",
                        max_length=20,
                    ),
                ),
                (
                    "real_auctions",
                    models.PositiveIntegerField(default=0, help_text="Auctions that are not named like a test"),
                ),
                ("test_auctions", models.PositiveIntegerField(default=0)),
                ("first_auction", models.DateTimeField(blank=True, null=True)),
                ("last_auction", models.DateTimeField(blank=True, null=True)),
                ("days_since_last_auction", models.IntegerField(blank=True, null=True)),
                (
                    "median_gap_days",
                    models.FloatField(
                        blank=True,
                        help_text="This club's own cadence: the median gap between its real auctions",
                        null=True,
                    ),
                ),
                (
                    "overdue_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="Gaps elapsed since the last auction. 1.0 is due, 2.0 has missed one",
                        null=True,
                    ),
                ),
                ("members", models.PositiveIntegerField(default=0)),
                (
                    "tools_used",
                    models.JSONField(
                        blank=True, default=list, help_text="Which club management features this club has actually used"
                    ),
                ),
                ("due_for_checkin", models.BooleanField(db_index=True, default=False)),
                ("checkin_reason", models.CharField(blank=True, default="", max_length=200)),
                ("computed_on", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="health", to="auctions.club"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Club health",
                "ordering": ["-overdue_ratio"],
            },
        ),
    ]
