# Generated by Django 5.2.17 on 2026-09-08 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0428_club_health"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="formfailure",
            name="kind",
            field=models.CharField(
                choices=[("rejected", "Submitted and rejected"), ("abandoned", "Edited and left without saving")],
                db_index=True,
                default="rejected",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="formfailure",
            name="seconds_on_page",
            field=models.PositiveIntegerField(
                blank=True, help_text="Abandonments only: how long they spent before leaving", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="formfailure",
            index=models.Index(fields=["kind", "timestamp"], name="auctions_fo_kind_479dff_idx"),
        ),
    ]
