# Generated by Django 5.2.17 on 2026-09-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0430_club_outreach_stage_club_stall_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubhealth",
            name="people_here",
            field=models.PositiveIntegerField(
                default=0, help_text="People on this site who say they are in this club, by either link"
            ),
        ),
        migrations.AlterField(
            model_name="clubhealth",
            name="stage",
            field=models.CharField(
                choices=[
                    ("empty", "No auctions"),
                    ("aware", "Members here, no auctions"),
                    ("trial", "Test auctions only"),
                    ("new", "First real auction"),
                    ("active", "Running to its own schedule"),
                    ("slipping", "Late against its own schedule"),
                    ("dormant", "Stopped"),
                ],
                db_index=True,
                default="empty",
                max_length=20,
            ),
        ),
    ]
