# Generated by Django 5.2.17 on 2026-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0432_alter_pageview_auction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkedJobState",
            fields=[
                ("name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                (
                    "cursor",
                    models.BigIntegerField(
                        default=0, help_text="The next primary key to look at. Everything below this has been handled."
                    ),
                ),
                (
                    "ceiling",
                    models.BigIntegerField(
                        default=0,
                        help_text="The primary key the job stops at, captured on its first run. Rows written after that were written by code that already does the right thing, so chasing them would never finish.",
                    ),
                ),
                ("finished", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
