# Generated by Django 5.2.17 on 2026-09-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0433_chunkedjobstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="date_links_checked",
            field=models.DateTimeField(
                blank=True, help_text="When club_verification last fetched this club's links", null=True
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="facebook_reachable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="homepage_reachable",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="link_check_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="What happened the last time this club's links were fetched",
                max_length=200,
            ),
        ),
    ]
