"""Drop the four link-check columns 0434 added, and add ``Club.contact_method``.

0434 shipped the columns for a club link verifier that fetched every club's homepage once a year.
That verifier was scrapped a day later along with the rest of phase 8's outbound HTTP, so the
columns never held anything anywhere.  They are dropped here rather than by editing 0434, because
0434 was pushed -- an applied migration is somebody else's history and does not get rewritten.

The drops are conditional on the column actually being there.  Staging stopped dead on this
migration with ``OperationalError (1091, "Can't DROP COLUMN `date_links_checked`")``: 0434 was
recorded applied against a database whose ``auctions_club`` did not end up with the columns, and
``RemoveField`` states that a column exists rather than that it should not.  There is no way past
a failing migration from application code -- entrypoint.sh refuses to start on a half-migrated
database, so the container crash-loops and the site stays down until a human intervenes.  Columns
that never held a value anywhere are not worth that: what this migration means is that the four
are gone afterwards, and a database that is already there is already correct.  The model state is
unchanged either way, so a database that applied this before the guard existed re-runs nothing.
"""

# Generated by Django 5.2.17 on 2026-09-10 01:44

from django.db import migrations, models

LINK_CHECK_COLUMNS = ("date_links_checked", "facebook_reachable", "homepage_reachable", "link_check_note")

# What 0434 created, for the reverse: a reverse that put the state back without the columns would
# leave every ``Club`` query naming four columns the table does not have.
LINK_CHECK_DEFINITIONS = {
    "date_links_checked": "datetime(6) NULL",
    "facebook_reachable": "tinyint(1) NULL",
    "homepage_reachable": "tinyint(1) NULL",
    "link_check_note": "varchar(200) NOT NULL",
}


def _present_columns(connection, table):
    with connection.cursor() as cursor:
        return {column.name for column in connection.introspection.get_table_description(cursor, table)}


def drop_link_check_columns(apps, schema_editor):
    """Drop each of the four columns, skipping any the database does not have."""
    connection = schema_editor.connection
    table = apps.get_model("auctions", "Club")._meta.db_table
    present = _present_columns(connection, table)
    for column in LINK_CHECK_COLUMNS:
        if column not in present:
            continue
        schema_editor.execute(
            schema_editor.sql_delete_column
            % {"table": schema_editor.quote_name(table), "column": schema_editor.quote_name(column)}
        )


def add_link_check_columns(apps, schema_editor):
    """Put back any of the four the database is missing, so a reverse lands on 0434's schema."""
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return
    table = apps.get_model("auctions", "Club")._meta.db_table
    present = _present_columns(connection, table)
    for column, definition in LINK_CHECK_DEFINITIONS.items():
        if column in present:
            continue
        with connection.cursor() as cursor:
            cursor.execute(f"ALTER TABLE `{table}` ADD COLUMN `{column}` {definition}")


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0434_club_date_links_checked_club_facebook_reachable_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="club",
                    name="date_links_checked",
                ),
                migrations.RemoveField(
                    model_name="club",
                    name="facebook_reachable",
                ),
                migrations.RemoveField(
                    model_name="club",
                    name="homepage_reachable",
                ),
                migrations.RemoveField(
                    model_name="club",
                    name="link_check_note",
                ),
            ],
            database_operations=[migrations.RunPython(drop_link_check_columns, add_link_check_columns)],
        ),
        migrations.AddField(
            model_name="club",
            name="contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not known"),
                    ("email", "Email"),
                    ("webform", "Form on their website"),
                    ("facebook", "Facebook only"),
                ],
                default="",
                help_text="Which door to knock on. Outreach is a person working a queue one club at a time, and a club reachable only through Facebook takes a different afternoon from one with an address.",
                max_length=20,
            ),
        ),
    ]
