"""Drop the four link-check columns 0434 added, and add ``Club.contact_method``.

0434 shipped the columns for a club link verifier that fetched every club's homepage once a year.
That verifier was scrapped a day later along with the rest of phase 8's outbound HTTP, so the
columns never held anything anywhere.  They are dropped here rather than by editing 0434, because
0434 was pushed -- an applied migration is somebody else's history and does not get rewritten.

Every operation here is conditional on the schema it finds, because **MariaDB cannot roll back
DDL**.  Django runs a migration inside a transaction, but each ``ALTER TABLE`` commits as it
executes and MariaDB throws the surrounding transaction away; a migration interrupted partway --
a killed deploy, a container restart, an OOM -- leaves its finished operations in the schema with
no row in ``django_migrations``.  The retry then replays the whole migration against a database
that has already had half of it.  Staging landed exactly there, and produced the two failures in
order as each guard was added: ``1091 Can't DROP COLUMN `date_links_checked``` from the drops that
had already happened, then ``1060 Duplicate column name 'contact_method'`` from the add that had.
Neither is recoverable from application code -- entrypoint.sh refuses to start on a half-migrated
database, so the container crash-loops and the site stays down until somebody edits the schema by
hand.

So this migration describes the schema it wants rather than the change it makes: afterwards the
four columns are gone and ``contact_method`` is there, and a database already in that state is
already correct.  The model state is untouched, so a database that applied this before the guards
existed re-runs nothing.
"""

# Generated by Django 5.2.17 on 2026-09-10 01:44

from django.db import migrations, models

LINK_CHECK_COLUMNS = ("date_links_checked", "facebook_reachable", "homepage_reachable", "link_check_note")

# What 0434 created, for the reverse: a reverse that restored the state without the columns would
# leave every ``Club`` query naming four columns the table does not have.
LINK_CHECK_DEFINITIONS = {
    "date_links_checked": "datetime(6) NULL",
    "facebook_reachable": "tinyint(1) NULL",
    "homepage_reachable": "tinyint(1) NULL",
    "link_check_note": "varchar(200) NOT NULL",
}

CONTACT_METHOD = "contact_method"


def _contact_method_field():
    """A fresh instance each time: the state operation keeps one, the schema editor names another."""
    return models.CharField(
        blank=True,
        choices=[
            ("", "Not known"),
            ("email", "Email"),
            ("webform", "Form on their website"),
            ("facebook", "Facebook only"),
        ],
        default="",
        help_text="Which door to knock on. Outreach is a person working a queue one club at a time, and a club reachable only through Facebook takes a different afternoon from one with an address.",
        max_length=20,
    )


def _present_columns(connection, table):
    with connection.cursor() as cursor:
        return {column.name for column in connection.introspection.get_table_description(cursor, table)}


def _drop_column(schema_editor, table, column):
    schema_editor.execute(
        schema_editor.sql_delete_column
        % {"table": schema_editor.quote_name(table), "column": schema_editor.quote_name(column)}
    )


def apply_club_columns(apps, schema_editor):
    """Drop the four link-check columns and add ``contact_method``, skipping whatever is already so."""
    Club = apps.get_model("auctions", "Club")
    table = Club._meta.db_table
    present = _present_columns(schema_editor.connection, table)
    for column in LINK_CHECK_COLUMNS:
        if column in present:
            _drop_column(schema_editor, table, column)
    if CONTACT_METHOD not in present:
        field = _contact_method_field()
        field.set_attributes_from_name(CONTACT_METHOD)
        schema_editor.add_field(Club, field)


def unapply_club_columns(apps, schema_editor):
    """Put 0434's schema back, so a reverse lands on something the restored state describes.

    MariaDB only: raw column definitions, and every database this runs against is MariaDB.
    """
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return
    table = apps.get_model("auctions", "Club")._meta.db_table
    present = _present_columns(connection, table)
    if CONTACT_METHOD in present:
        _drop_column(schema_editor, table, CONTACT_METHOD)
    for column, definition in LINK_CHECK_DEFINITIONS.items():
        if column in present:
            continue
        with connection.cursor() as cursor:
            cursor.execute(f"ALTER TABLE `{table}` ADD COLUMN `{column}` {definition}")


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0434_club_date_links_checked_club_facebook_reachable_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="club",
                    name="date_links_checked",
                ),
                migrations.RemoveField(
                    model_name="club",
                    name="facebook_reachable",
                ),
                migrations.RemoveField(
                    model_name="club",
                    name="homepage_reachable",
                ),
                migrations.RemoveField(
                    model_name="club",
                    name="link_check_note",
                ),
                migrations.AddField(
                    model_name="club",
                    name=CONTACT_METHOD,
                    field=_contact_method_field(),
                ),
            ],
            database_operations=[migrations.RunPython(apply_club_columns, unapply_club_columns)],
        ),
    ]
