"""Drop the four link-check columns 0434 added, and add ``Club.contact_method``.

0434 shipped the columns for a club link verifier that fetched every club's homepage once a year.
That verifier was scrapped a day later along with the rest of phase 8's outbound HTTP, so the
columns never held anything anywhere.  They are dropped here rather than by editing 0434, because
0434 was pushed -- an applied migration is somebody else's history and does not get rewritten.
"""

# Generated by Django 5.2.17 on 2026-09-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0434_club_date_links_checked_club_facebook_reachable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="date_links_checked",
        ),
        migrations.RemoveField(
            model_name="club",
            name="facebook_reachable",
        ),
        migrations.RemoveField(
            model_name="club",
            name="homepage_reachable",
        ),
        migrations.RemoveField(
            model_name="club",
            name="link_check_note",
        ),
        migrations.AddField(
            model_name="club",
            name="contact_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not known"),
                    ("email", "Email"),
                    ("webform", "Form on their website"),
                    ("facebook", "Facebook only"),
                ],
                default="",
                help_text="Which door to knock on. Outreach is a person working a queue one club at a time, and a club reachable only through Facebook takes a different afternoon from one with an address.",
                max_length=20,
            ),
        ),
    ]
