# Generated by Django 5.2.17 on 2026-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0435_remove_club_date_links_checked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciessearchcache",
            name="scientific_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="What this lot name was identified as, whether or not the species list holds it.  A row with no species and a name filled in here is a gap in the list rather than a verdict about the name -- see SpeciesSearchCache.is_a_gap.",
                max_length=120,
            ),
        ),
    ]
