# Generated by Django 5.2.17 on 2026-09-10 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0437_fix_integer_money_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignInStitch",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="The session key the browser was holding before this sign-in.",
                        max_length=600,
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sign_in_stitches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sign-in stitch",
                "verbose_name_plural": "Sign-in stitches",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "session_id"), name="one_stitch_per_user_session")
                ],
            },
        ),
    ]
