# Generated by Django 5.2.17 on 2026-09-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0438_signinstitch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubLadderSnapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField(db_index=True)),
                ("stage", models.CharField(db_index=True, max_length=20)),
                ("clubs", models.PositiveIntegerField(default=0)),
                ("computed_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Club ladder snapshot",
                "ordering": ["-month", "stage"],
                "constraints": [
                    models.UniqueConstraint(fields=("month", "stage"), name="one_ladder_snapshot_per_month_stage")
                ],
            },
        ),
    ]
