# Generated by Django 5.2.17 on 2026-09-12 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0439_clubladdersnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicegrammar",
            name="commit_after_ms",
            field=models.PositiveIntegerField(
                default=700,
                help_text="Milliseconds a heard lot, bidder or price must stop changing before the app fills the field. 0 waits for the recognizer's final result instead -- slower by seconds, and the kill switch if early values misbehave. Under 200 the app raises it to 200.",
                validators=[django.core.validators.MaxValueValidator(2500)],
            ),
        ),
    ]
