# Generated by Django 5.2.17 on 2026-09-12, then given its data repair by hand.

from django.db import migrations, models

from auctions import voice

# What a row created before 2026-09-12 holds. A row still carrying exactly these values was never
# tuned by anybody -- it is the defaults of the day, stored by opening the admin page and pressing
# save -- so it is safe to move onto the new ones. A row holding anything else is somebody's
# deliberate tuning and is left alone, except for the key rename, which changes no value.
OLD_WEIGHTS_RENAMED = {"asr": 0.5, "keyword": 1.0, "match": 1.0, "agreement": 0.4}
OLD_THRESHOLDS = {"confident": 0.85, "unsure": 0.5}
OLD_ANCHORS = {
    "lot": ["lot", "lot number", "item"],
    "bidder": ["bidder", "buyer", "bidder number"],
    "price": ["dollars", "dollar", "bucks"],
    "sold": ["sold", "hammer"],
    "unsold": ["no sale", "unsold", "pass"],
    "undo": ["undo", "scratch that"],
    "clear": ["clear", "cancel that"],
    "confirm": ["confirm", "yes", "correct"],
}


def retune_voice_grammar(apps, schema_editor):
    """Bring the configured grammar row, if a deployment has one, onto the new defaults.

    Three repairs, and only the first happens unconditionally:

    * ``weights`` said ``snap`` where the app reads ``match``, so the one weight describing the
      vocabulary match was unreachable from the admin and every edit to it did nothing. Renaming the
      key keeps whatever value was in it: it is the same signal under the name that is read.
    * ``weights`` and ``thresholds`` still equal to the old defaults move to the new ones. That is
      what stops a configured synonym ("buyer") and an honestly-reported recognizer confidence from
      filling every field amber -- and an amber field blocks the save, so on those numbers no
      ``sold`` ever saved.
    * ``anchors`` still equal to the old defaults gain the two words the app already accepted
      ("paddle", "start over") and "bitter", which is not a mishearing to forgive but the same sound.

    ``backend`` is deliberately not touched. An existing row holds "platform" because that was the
    only choice when it was written, and "platform" is also the documented kill switch for the
    vocabulary-biased recognizer -- so flipping it would be indistinguishable from overriding
    somebody's decision. New rows get "biased" from the field default; an existing one is one click
    in the admin.
    """
    VoiceGrammar = apps.get_model("auctions", "VoiceGrammar")
    for grammar in VoiceGrammar.objects.all():
        fields = []
        weights = dict(grammar.weights or {})
        if "snap" in weights:
            weights["match"] = weights.pop("snap")
        if weights == OLD_WEIGHTS_RENAMED:
            weights = voice.default_weights()
        if weights != (grammar.weights or {}):
            grammar.weights = weights
            fields.append("weights")
        if (grammar.thresholds or {}) == OLD_THRESHOLDS:
            grammar.thresholds = voice.default_thresholds()
            fields.append("thresholds")
        if (grammar.anchors or {}) == OLD_ANCHORS:
            grammar.anchors = voice.default_anchors()
            fields.append("anchors")
        if fields:
            grammar.save(update_fields=fields)


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0440_voicegrammar_commit_after_ms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicegrammar",
            name="backend",
            field=models.CharField(
                choices=[
                    ("platform", "Platform recognizer"),
                    ("biased", "Platform recognizer, vocabulary-biased"),
                    ("cloud", "Cloud recognizer"),
                    ("spotter", "Keyword spotter"),
                ],
                default="biased",
                help_text="What the app should listen with, if it can. It reports what it actually managed.",
                max_length=20,
            ),
        ),
        # Not reversible in any useful sense: the old and new values are both legal states of the
        # row, so there is nothing here that could tell a rollback which of them somebody meant.
        migrations.RunPython(retune_voice_grammar, migrations.RunPython.noop, elidable=False),
    ]
