# Generated by Django 5.2.17 on 2026-09-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0441_alter_voicegrammar_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="running_total_tip_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether this user has been told, once, where to turn the running total notification off",
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="show_running_total_notification",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Show your total amount purchased in real time in the app.  In person auctions only.",
                verbose_name="Show running total notification",
            ),
        ),
    ]
