# Generated by Django 5.2.17 on 2026-09-18 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0442_userdata_running_total_tip_sent_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clubmember",
            name="unique_bidder_number_per_club",
        ),
    ]
