# Generated by Django 5.2.17 on 2026-09-18 10:53

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0443_remove_clubmember_unique_bidder_number_per_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("999999.99")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="winning_price",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MaxValueValidator(Decimal("999999.99"))],
            ),
        ),
    ]
