# Generated by Django 5.2.17 on 2026-09-18 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0443_privacy_blog_browsing_info"),
        ("auctions", "0444_alter_bid_amount_alter_lot_winning_price"),
    ]

    operations = []
