# Generated by Django 5.2.17 on 2026-09-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0445_merge_20260918_1125"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="elapsed_ms",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Milliseconds from the query arriving to this round finishing. What the person actually waited.",
            ),
        ),
        migrations.AddField(
            model_name="llmusage",
            name="request_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="One id shared by every round of one thing somebody typed, so a lookup and the answer it fed are one story and not two. Without it the only way to group rounds was by the text of the query, which counted two people asking the same thing as one.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="llmusage",
            name="variant",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="A fingerprint of the assistant that answered: its prompt, the skills it was offered and the model. It changes on its own when any of those do, so a before and an after can be put either side of a deploy without anybody remembering the date.",
                max_length=16,
            ),
        ),
    ]
