# Generated by Django 5.2.17 on 2026-09-19 17:56

from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0446_llmusage_elapsed_ms_llmusage_request_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="palette_navigate_only",
            field=models.BooleanField(
                blank=True,
                default=auctions.models.get_default_palette_navigate_only,
                help_text="Tick this and the command palette will take you to the right page and stop there, instead of doing things for you.  It can still find a lot, a person or an auction and answer a question about one; it just won't record a sale or check anybody in.",
                verbose_name="Only let the command palette open pages",
            ),
        ),
    ]
