# Generated by Django 5.2.17 on 2026-09-20 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0447_userdata_palette_navigate_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llmusage",
            name="read_the_query",
            field=models.BooleanField(
                default=False,
                help_text="The auction was read out of the sentence because the model left the parameter out. Worth counting on its own: it is a guess made on the user's behalf, and the card it produces looks exactly as confident as one the model named.",
            ),
        ),
        migrations.AddField(
            model_name="llmusage",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="The auction, club or lot this round was about -- the same line the confirmation card shows. Without it a repeatedly cancelled phrase says only that we picked the wrong thing, never which thing, and 'it answered about the wrong auction' cannot be checked at all.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="llmusage",
            name="tools_offered",
            field=models.CharField(
                blank=True,
                help_text="Which slice of the catalogue this round was handed: all, reads (a question), pages (a skill the palette gave up, so nothing that writes) or locked (navigate-only). A turn that quietly lost its write tools is otherwise an ordinary navigation on this page.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="llmusage",
            name="query",
            field=models.CharField(blank=True, db_index=True, help_text="What the user typed or said.", max_length=600),
        ),
        migrations.AddIndex(
            model_name="llmusage",
            index=models.Index(fields=["-createdon"], name="llmusage_createdon_desc"),
        ),
    ]
