# Generated by Django 5.2.17 on 2026-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0448_llmusage_read_the_query_llmusage_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="donation_contact_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Whose name goes on the request.",
                max_length=255,
                verbose_name="Contact name",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_expected_attendance",
            field=models.CharField(
                blank=True,
                default="",
                help_text="How many people come, as you would answer it: 80, or 60-100.",
                max_length=120,
                verbose_name="Expected attendance",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_legal_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Only if it differs from the club name a form would otherwise get.",
                max_length=255,
                verbose_name="Legal name",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A number a vendor can call back. Forms often make this required.",
                max_length=50,
                verbose_name="Phone",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_tax_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="EIN or TIN. Nearly every donation form asks for one.",
                max_length=50,
                verbose_name="Tax ID",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_tax_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="As you would write it on a form, e.g. 501(c)(3) public charity, or 501(c)(7) social club.",
                max_length=120,
                verbose_name="Tax status",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="donation_website",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Website"),
        ),
        migrations.AddField(
            model_name="donationemail",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("webform", "Their donation request form"),
                    ("phone", "Phone"),
                    ("in_person", "In person"),
                ],
                db_index=True,
                default="email",
                help_text="How this contact happened. Only email rows count against the daily email allowance.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="donationvendor",
            name="contact_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("webform", "Their donation request form"),
                    ("phone", "Phone"),
                    ("in_person", "In person"),
                ],
                default="email",
                help_text="Large businesses usually take donation requests only through a form on their own site.",
                max_length=20,
                verbose_name="Contact them by",
            ),
        ),
        migrations.AddField(
            model_name="donationvendor",
            name="contact_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If this vendor uses a webform for initial contacts instead of an email.  Leave this blank if you have their email address.",
                max_length=500,
                verbose_name="Their request form",
            ),
        ),
    ]
