# Generated by Django 5.2.17 on 2026-09-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0449_club_donation_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationvendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("sent", "Initial request sent"),
                    ("interested", "Interested"),
                    ("promised", "Donation promised"),
                    ("received", "Donation received"),
                    ("not_interested", "Not interested"),
                    ("do_not_contact", "Do not contact"),
                ],
                db_index=True,
                default="new",
                max_length=20,
            ),
        ),
    ]
