# Generated by Django 5.2.17 on 2026-09-21 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0452_privacy_third_parties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="tax",
            field=models.PositiveIntegerField(
                default=0,
                help_text="A percent added to the buyer's invoice for all won lots (e.g. enter 7 for 7% sales tax). Leave at 0 for no tax. One rate for the whole auction: whether your club has to charge tax, at what rate, what it shows on an invoice (Canadian clubs have to name GST/HST separately, with their registration number) and what it does with the money afterwards are your club's to get right.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
