# Generated by Django 5.2.17 on 2026-09-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0453_alter_auction_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="donation_forced",
            field=models.BooleanField(
                default=False,
                help_text="Set when donation was only set because the price was at or under the auction's force donation threshold, so correcting the price above it makes the lot the seller's again.",
            ),
        ),
    ]
