# Generated by Django 5.2.17 on 2026-09-25 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0455_merge_duplicate_invoices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("auctiontos_user", "auction"), name="invoice_one_per_participant"
            ),
        ),
    ]
