# Generated by Django 5.2.17 on 2026-09-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0457_drop_duplicate_invoice_payments"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoicepayment",
            constraint=models.UniqueConstraint(fields=("invoice", "external_id"), name="invoicepayment_one_per_charge"),
        ),
    ]
