# Generated by Django 5.2.17 on 2026-09-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0458_invoicepayment_one_per_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="number",
            field=models.PositiveBigIntegerField(
                blank=True,
                editable=False,
                help_text="A random 10-digit id for the URLs other systems keep: the API, webhooks, embeds, the calendar feed and emailed links. The slug follows the name, so a rename used to break them all. Old slug URLs still work.",
                null=True,
                unique=True,
            ),
        ),
    ]
