# Generated by Django 5.2.17 on 2026-09-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0460_fill_club_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="ended_unsold",
            field=models.BooleanField(default=False),
        ),
    ]
