# Generated by Django 5.2.17 on 2026-09-25 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0462_fill_lot_ended_unsold"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="custom_random_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Shown on lot pages, e.g. Table",
                max_length=50,
                null=True,
                verbose_name="Custom random field name",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="use_custom_random_field",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Each lot gets one of your options at random, for A/B tests or table assignments; nobody can pick or change it.",
                verbose_name="Use custom random field",
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="custom_random",
            field=models.CharField(blank=True, default="", editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name="auction",
            name="label_print_fields",
            field=models.CharField(
                blank=True,
                default="qr_code,lot_name,scientific_name,min_bid_label,buy_now_label,quantity_label,seller_name,donation_label,custom_field_1,i_bred_this_fish_label,custom_checkbox_label,custom_dropdown_label,custom_random_label",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AuctionRandomOption",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("value", models.CharField(max_length=15)),
                ("auction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auctions.auction")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
