# Generated by Django 5.2.17 on 2026-09-29 21:58
"""Set lot winners had three modes; only the standard one was reachable, and the autocomplete mode was removed."""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0472_invoice_paid_email_reads_as_a_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="set_lot_winners_url",
        ),
    ]
