# Generated by Django 5.2.17 on 2026-09-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0473_remove_set_lot_winners_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="sales_recorded",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="How many times a winner or sell price was recorded for this lot"
            ),
        ),
    ]
