"""Set every seeded email template to exactly what the migrations before this one produce.

0451, 0466, 0467 and 0472 changed templates by find-and-replace, and left any passage alone that had
been edited in the admin, so a hand-edited site could be missing some or all of them. This writes the
full subject, text and HTML of each template, taken from a database built from migrations alone, and
creates any template that is missing. Edits made in the admin are overwritten, on purpose.

Nothing is restored on the way back: the text it replaced was never recorded.
"""

from django.db import migrations

#: ``name: (subject, content, html_content)``, dumped from a fresh database migrated to 0474.
TEMPLATES = {
    "auction_first": (
        "Thanks for creating an auction!",
        "Hey {{ auction.created_by.first_name|default:\"there\" }},\n\nThanks for creating {{ auction }} on {{domain}}!\n\nYour next steps:\n{% if auction.no_location %}*You haven't yet added a pickup location to your auction.  You should add one here: https://{{ domain }}/locations/new/?next=/auctions/{{auction.slug}}{% else %}{% if not auction.multi_location %}If you want, you can add an additional pickup location (or two) here: https://{{ domain }}/auctions/{{auction.slug}}/locations/new/\n\nHere's some more information about how multi-locations auctions work:\nhttps://{{domain}}/blog/multiple-location-auctions/{% endif %}\n\n{% endif %}* Users won't be able to add or bid on lots until they've read your auction rules and confirmed their pickup location.  You should confirm your own pickup location and add a few lots to your auction so there's something there for other users to see and bid on.\n\n* {% if not auction.promote_this_auction %}Your auction isn't visible to users unless they have a link to it.  {%endif%}Use this link to share your auction: https://{{ domain }}/?{{auction.slug}}{% if auction.multi_location %}\n\n* It looks like you've added more than one pickup location to your auction.  Here's some more information about how multi-locations auctions work:\nhttps://{{domain}}/blog/multiple-location-auctions/{% endif %}\n\n* If you need to make changes to the rules, sooner is better than later.  You can edit your auction here: https://{{domain}}/auctions/{{auction.slug}}/edit/\n\n* Read about encouraging participation: https://{{domain}}/blog/encouraging-participation/\n\nYou'll get a few more emails like this over the course of your auction, unless you unsubscribe: https://{{ domain }}/unsubscribe/{{unsubscribe}}/\n\nJust reply to this email if you have questions!\n{% load email_tags %}{% email_footer_text %}\n",
        "{% extends \"email/base.html\" %}{% load email_tags %}\n{% block content %}\nHey {{ auction.created_by.first_name|default:\"there\" }},<br><br>\n\nThanks for creating {{ auction }} on {{domain}}!<br><br>\n\nYour next steps:<br>\n<ol>\n{% if auction.no_location %}<li> You haven't yet added a pickup location to your auction.  You should <a href=\"https://{{ domain }}/locations/new/?next=/auctions/{{auction.slug}}\">add one here</a>.</li>{% else %}{% if not auction.multi_location %}<li>If you want, you can <a href=\"https://{{ domain }}/auctions/{{auction.slug}}/locations/new/\">add an additional pickup location (or two) here</a>. Here's <a href=\"https://{{domain}}/blog/multiple-location-auctions/\">more information about how multi-locations auctions work</a>.</li>{% endif %}{% endif %}<li> Users won't be able to add or bid on lots until they've read your auction rules and confirmed their pickup location.  You should confirm your own pickup location and add a few lots to your auction so there's something there for other users to see and bid on.</li>\n\n<li> {% if not auction.promote_this_auction %}Your auction isn't visible to users unless they have a link to it.  {% endif %}Use this link to share your auction: https://{{ domain }}/?{{auction.slug}}</li>\n\n{% if auction.multi_location %}<li> It looks like you've added more than one pickup location to your auction.  Here's some <a href='https://{{domain}}/blog/multiple-location-auctions/'>more information about how multi-locations auctions work</a>.</li>{% endif %}\n\n<li> If you need to make changes to the rules, sooner is better than later.  You can <a href='https://{{domain}}/auctions/{{auction.slug}}/edit/'>edit your auction here</a>.</li>\n\n<li> Read about <a href='https://{{domain}}/blog/encouraging-participation/'>encouraging participation</a>.\n</li></ol>\nYou'll get a few more emails like this over the course of your auction, unless you <a href='https://{{ domain }}/unsubscribe/{{unsubscribe}}/'>unsubscribe</a>\n<br><br>\nJust reply to this email if you have questions!\n{% endblock %}\n",
    ),
    "auction_invoices": (
        "Invoices for {{auction}} are ready!",
        "Hey {{ auction.created_by.first_name|default:\"there\" }},\n\nYour auction has ended and invoices are ready!\n\nPlease review the invoices for {{auction}} and mark them ready for payment: https://{{domain}}/auctions/{{auction.slug}}/users/\n\n* Users will get an email notification ONLY AFTER you mark these invoice ready for payment, so mark them ready as soon as possible to give users time to pay before they need to pickup and exchange lots.  You can change this behavior with the Invoice Notifications setting in your auction's rules.\n\n* We make it easy for you to import the automatically generated invoices into PayPal: https://{{ domain }}/blog/online-payments-suck/.\n\n* If you want to make changes or adjustments to these invoices, make those before marking them ready.  You'll see editing tools on each invoice to manually adjust it.\n\n* Remember to print out a copy of each invoice and bring it to the pickup location.  Having these on hand will make the lot exchange easier: users get their invoice showing payment, and can show it to the sellers before picking up their lots.\n{% load email_tags %}{% email_footer_text %}\n",
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ auction.created_by.first_name|default:"there" }},<br><br>\n\nYour auction has ended and invoices are ready!<br><br>\n\nPlease review the invoices for {{auction}} and mark them ready for payment.\n{% email_button %}<a href="https://{{domain}}/auctions/{{auction.slug}}/users/">Review invoices</a>{% endemail_button %}\n\n<ul><li> Users will get an email notification <em>only after</em> you mark these invoice ready for payment, so mark them ready as soon as possible to give users time to pay before they need to pickup and exchange lots.  You can change this behavior with the Invoices Notification setting in your auction\'s rules</li>\n\n<li> We make it easy for you to <a href="https://{{ domain }}/blog/online-payments-suck/">import the automatically generated invoices into PayPal</a>.</li>\n\n<li> If you want to make changes or adjustments to these invoices, make those before marking them ready.  You\'ll see editing tools on each invoice to manually adjust it.</li>\n\n<li> Remember to print out a copy of each invoice and bring it to the pickup location.  Having these on hand will make the lot exchange easier: users get their invoice showing payment, and can show it to the sellers before picking up their lots.</li>\n</ul>\n{% endblock %}\n',
    ),
    "auction_print_reminder": (
        "Remember to print your labels for {{ tos.auction }}",
        "{% load email_tags %}Hey {{ tos.name|first_name|default:\"there\" }},\n\nThanks for adding lots to {{ tos.auction }}!  {% if tos.auction.is_online%}Now that the auction has ended,{% else %}Before you bring your lots to the auction,{%endif%} please print your labels: https://{{domain}}{{tos.auction.label_print_link}}\n\n{% if not tos.auction.is_online%}If you want to add more lots, add them before printing your labels.{%endif%}You can print these on regular paper, cut them out, and use packing tape to attach them to your lots.  Make sure the bags are dry before attaching the labels!\n\n{% if tos.auction.is_online%}If you don't own a printer, write the lot number{% if tos.auction.multi_location %}, winner's location {% endif %} and winner's name clearly on each lot.\n{% else %}\nMake sure to arrive well before the auction begins so you have time to organize your lots.\n{% endif %}\n\n{% if website_focus == \"fish\" %}If you haven't packed fish before, take a look at these tips: https://{{ domain }}/blog/transporting-fish/{% endif %}\n\nQuestions?  Just reply and we'll help!\n{% load email_tags %}{% email_footer_text %}\n",
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block header %}{% email_club_header %}{% endblock %}\n{% block content %}\nHey {{ tos.name|first_name|default:"there" }},<br>\n<br>\nThanks for adding lots to {{ tos.auction }}!  {% if tos.auction.is_online%}Now that the auction has ended,{% else %}Before you bring your lots to the auction,{%endif%} please print your labels.{% if not tos.auction.is_online%}  If you want to add more lots, add them before printing your labels.{%endif%}\n{% email_button %}<a href="https://{{domain}}{{tos.auction.label_print_link}}">Print your labels</a>{% endemail_button %}\n<ol>\n<li>Print labels on regular paper</li>\n<li>Cut them out</li>\n<li>Use packing tape to attach them to your lots</li>\n</ol>Make sure the bags are dry before attaching the labels!<br>\n<br>\n{% if tos.auction.is_online%}If you don\'t own a printer, <b>write the lot number{% if tos.auction.multi_location %}, winner\'s location {% endif %} and winner\'s name clearly on each lot</b>.<br><br>\nRemember to bring your lots to {{ tos.pickup_location }}, on {{ tos.pickup_time_as_localized_string }}.{% else %}\nMake sure to arrive well before the auction begins, so you have time to organize your lots.  Remember that bidding starts promptly on {{ tos.auction_date_as_localized_string }}.<br>\n{% endif %}<a href="{{tos.pickup_location.directions_link}}">Get directions</a>.\n<br><br>\n{% if website_focus == "fish" %}If you haven\'t packed fish before, take a look at <a href="https://{{ domain }}/blog/transporting-fish/">these tips</a>.<br><br>{% endif %}\nQuestions?  Just reply and we\'ll help!\n{% endblock %}\n',
    ),
    "auction_promo_email": (
        "{{ auction.title }}: an {{ kind }} near you",
        "Hey {{ name|default:\"there\" }},\n\n{{ auction.title }} is an {{ kind }}{% if distance %} {{ distance }} from you{% endif %}{% if when %}, and {{ when }}{% endif %}.\n{% if multiple_locations %}Your nearest pickup location is {{ location.name }}.\n{% elif location.name %}It's at {{ location.name }}.\n{% endif %}\nRead the rules and join: {{ auction_url }}&uid={{ unsubscribe }}\n{% if lots %}\nSome lots you might like:\n{% for lot in lots %}\n* {{ lot.lot_name }}: https://{{ lot.full_lot_link }}?src={{ uuid }}\n{% endfor %}{% endif %}\nYou're getting this because you asked to hear about auctions near you. Change that, or how far away counts as near: https://{{ domain }}/notifications/\n{% load email_tags %}{% email_footer_text %}\n",
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block header %}{% email_club_header %}{% endblock %}\n{% block content %}\nHey {{ name|default:"there" }},<br><br>\n\n<a href="{{ auction_url }}&uid={{ unsubscribe }}"><b>{{ auction.title }}</b></a> is an {{ kind }}{% if distance %} {{ distance }} from you{% endif %}{% if when %}, and {{ when }}{% endif %}.\n{% if multiple_locations %}Your nearest pickup location is {{ location.name }}.{% elif location.name %}It\'s at {{ location.name }}.{% endif %}<br><br>\n\n{% email_button %}<a href="{{ auction_url }}&uid={{ unsubscribe }}">Read the rules and join</a>{% endemail_button %}\n\n{% if lots %}<h3>Some lots you might like</h3>\n{% for lot in lots %}\n<b>{{ lot.lot_name }}</b><br>\n<a href="https://{{ lot.full_lot_link }}?src={{ uuid }}">{% if lot.thumbnail %}{% if lot.thumbnail.image %}<img src=\'https://{{ domain }}{{ lot.thumbnail.image.lot_list.url }}\'></img>{% else %}<img src=\'{{ lot.thumbnail.url }}\' style=\'max-width:250px; max-height:150px; object-fit:cover;\'></img>{% endif %}<br>{% endif %}View this lot</a><br><br>\n{% endfor %}{% endif %}\n\n<small>You\'re getting this because you asked to hear about auctions near you. <a href="https://{{ domain }}/notifications/">Change that</a>, or how far away counts as near.</small>\n{% endblock %}\n',
    ),
    "auction_second": (
        "See a list of users in your auction",
        "Hey {{ auction.created_by.first_name|default:\"there\" }},\n\n{{ auction.number_of_confirmed_tos }} people have joined {{auction}}!\n\nNow is a good time to download a spreadsheet of user information.  You can download the latest copy of this file here: https://{{domain}}/auctions/{{auction.slug}}/report/\n\nTry importing this to Google drive:\nGo to https://drive.google.com\nSelect New>File Upload, then select the CSV file you just downloaded\nOpen the uploaded file with Sheets\nClick Data>Create a Filter\nUse the filter you created to sort your CSV file and get information.\n\nYou may want to email some of these groups of people:\nPeople who viewed lots but did not bid -- encourage them to bid\nPeople who sold or bid on lots -- confirm that they'll be at the pickup location\nPeople who didn't fill out an address or phone number -- to make sure you have their contact info\nPeople who aren't part of your club -- ask them to join!\n{% if auction.use_categories %}People who sold lots -- remind them to stop feeding their fish a couple days before they bag them up{% endif %}\n{% load email_tags %}{% email_footer_text %}\n",
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ auction.created_by.first_name|default:"there" }},<br><br>\n\n{{ auction.number_of_confirmed_tos }} people have joined {{auction}}!<br><br>\n\nNow is a good time to download a spreadsheet of user information.  You can <a href="https://{{domain}}/auctions/{{auction.slug}}/report/">download the latest copy of this file here</a>. <br><br>\n\nTry importing this to Google drive:<br>\n<ol>\n<li>Go to <a href="https://drive.google.com">Google Drive</a></li>\n<li>Select <b>New>File Upload</b>, then select the CSV file you just downloaded</li>\n<li>Open the uploaded file with Sheets</li>\n<li>Click <b>Data>Create a Filter</b></li>\n<li>Use the filter you created to sort your CSV file and get information.</li>\n</ol>\n<br>\n\nYou may want to email some of these groups of people:<br>\n<ul>\n<li>People who viewed lots but did not bid -- encourage them to bid</li>\n<li>People who sold or bid on lots -- confirm that they\'ll be at the pickup location</li>\n<li>People who didn\'t fill out an address or phone number -- to make sure you have their contact info</li>\n{% if auction.use_categories %}<li>People who sold lots -- remind them to stop feeding their fish a couple days before they bag them up</li>{% endif %}\n<li>People who aren\'t part of your club -- ask them to join!</li>\n</ul>\n{% endblock %}\n',
    ),
    "auction_thanks": (
        "Thanks for running an auction",
        "Hey {{ auction.created_by.first_name|default:\"there\" }},\n\nThanks for choosing {{ domain }} to run your auction!\n\n* Take a look at the stats for {{ auction }}: https://{{ domain }}/auctions/{{ auction.slug }}/stats/\n\n* Remind your users to leave feedback on lots they've bought and sold: https://{{ domain }}/feedback/  It's probably a good idea to thank them for participating in {{ auction }}, and to encourage them to join your club.\n\n* If you haven't already done so, you should mark your invoices paid: https://{{ domain }}/auctions/{{ auction.slug }}/users/\n\n* Make sure to create your next auction by copying the rules used here: https://{{ domain }}/auctions/new/?copy={{ auction.slug }}  Try to always have one upcoming auction promoted for people to join (but not more than one or users can get confused about which one to join).\n\nOnce again, thank you very much for using {{ domain }}.  If you have suggestions to help improve the site, just reply to this email!\n{% load email_tags %}{% email_footer_text %}\n",
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ auction.created_by.first_name|default:"there" }},<br><br>\n\nThanks for choosing {{ domain }} to run your auction!<br><br>\n\n<ul>\n<li>Take a look at the <a href="https://{{ domain }}/auctions/{{ auction.slug }}/stats/">stats for {{ auction }}</a>.</li>\n\n<li>Remind your users to <a href="https://{{ domain }}/feedback/">leave feedback</a> on lots they\'ve bought and sold.  It\'s probably a good idea to thank them for participating in the {{ auction }}, and to encourage them to join your club.</li>\n\n<li>If you haven\'t already done so, you should <a href="https://{{ domain }}/auctions/{{ auction.slug }}/users/">mark your invoices paid</a>.</li>\n\n<li>Make sure to create your next auction by <a href="https://{{ domain }}/auctions/new/?copy={{ auction.slug }}">copying the rules used here</a>.  Try to always have one upcoming auction promoted for people to join (but not more than one or users can get confused about which one to join).</li>\n</ul><br>\n\nOnce again, thank you very much for using {{ domain }}.  If you have suggestions to help improve the site, just reply to this email!\n{% endblock %}\n',
    ),
    "auction_welcome": (
        "{{ subject }}",
        "Hey {{ auction.created_by.first_name|default:\"there\" }},\n\n{{ subject }}\n\nYou can view your auction here: https://{{ domain }}/auctions/{{ auction.slug }}/\n\n{% if enable_help %}* You can find help here: https://{{ domain }}/auctions/{{ auction.slug }}/help/\n\n{% endif %}* {% if not auction.promote_this_auction %}Your auction isn't visible to users unless they have a link to it.  {% endif %}Use this link to share your auction: https://{{ domain }}/?{{ auction.slug }}{% if auction.multi_location %}\n\n* It looks like you've added more than one pickup location to your auction.  Here's some more information about how multi-locations auctions work:\nhttps://{{ domain }}/blog/multiple-location-auctions/{% endif %}\n\nJust reply to this email if you have questions!\n{% load email_tags %}{% email_footer_text %}\n",
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ auction.created_by.first_name|default:"there" }},<br><br>\n\n{{ subject }}<br><br>\n\n{% email_button %}<a href="https://{{ domain }}/auctions/{{ auction.slug }}/">View your auction</a>{% endemail_button %}\n\n<ul>\n{% if enable_help %}<li><a href="https://{{ domain }}/auctions/{{ auction.slug }}/help/">Get help with your auction</a></li>{% endif %}\n<li>{% if not auction.promote_this_auction %}Your auction isn\'t visible to users unless they have a link to it.  {% endif %}Use this link to share your auction: <a href="https://{{ domain }}/?{{ auction.slug }}">https://{{ domain }}/?{{ auction.slug }}</a></li>\n{% if auction.multi_location %}<li>It looks like you\'ve added more than one pickup location to your auction.  Here\'s some <a href="https://{{ domain }}/blog/multiple-location-auctions/">more information about how multi-locations auctions work</a>.</li>{% endif %}\n</ul>\n\nJust reply to this email if you have questions!\n{% endblock %}\n',
    ),
    "club_membership_expiring": (
        "Your membership with {{ club.name }} is expiring soon",
        'Hey {{ name|default:"there" }},\n\nYour membership with {{ club.name }} is expiring soon.\n\nThis club uses {{ navbar_brand }} to manage club memberships.\nYou can renew it here: {{ renew_link }}\n{% load email_tags %}{% email_footer_text %}\n',
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block header %}{% email_club_header %}{% endblock %}\n{% block content %}\nHey {{ name|default:"there" }},<br><br>Your membership with <b>{{ club.name }}</b> is expiring soon.<br><br>This club uses {{ navbar_brand }} to manage club memberships.<br><a href=\'{{ renew_link }}\'>Click here to renew your membership</a>\n{% endblock %}\n',
    ),
    "in_person_auction_welcome": (
        "Thanks for joining {{tos.auction}}",
        "{% load email_tags %}Hey {{ tos.name|first_name|default:\"there\" }},\n\nThank you for joining {{tos.auction}}!  This is an in-person auction that starts {{ tos.auction_date_as_localized_string }}.  You can get directions here: {{tos.pickup_location.directions_link}}\n\nSee the auction's rules here: https://{{domain}}/auctions/{{tos.auction.slug}}/\n\nSee you there!\n\nQuestions?  Just reply and we'll help!\n{% load email_tags %}{% email_footer_text %}\n",
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block header %}{% email_club_header %}{% endblock %}\n{% block content %}\nHey {{ tos.name|first_name|default:"there" }},<br>\n<br>\nThank you for joining {{tos.auction}}!  This is an in-person auction that starts {{ tos.auction_date_as_localized_string }}.  <a href="{{tos.pickup_location.directions_link}}">Get directions here</a>.<br>\n<br>\nIf you want to sell lots, you can <a href="https://{{domain}}{{tos.auction.add_lot_link}}">add them here</a>.<br>\n<br>\nMake sure to <a href="https://{{domain}}/auctions/{{tos.auction.slug}}/">read the auction\'s rules</a>.<br>\n<br>\nSee you there!<br>\n<br>\nQuestions?  Just reply and we\'ll help!\n{% endblock %}\n',
    ),
    "invoice_ready": (
        "{{ subject }}",
        '{% load email_tags %}Hey {{ name|first_name|default:"there" }},\n\n{{ subject }}.  {% if invoice.status == "PAID" %}Your invoice is paid and nothing more is owed; this is your receipt. {% if invoice.user_should_be_paid %}You were paid{% else %}You paid{% endif %}{% elif invoice.user_should_be_paid %}You will be paid{% else %}You owe a total of{% endif %} ${{ invoice.absolute_amount|floatformat:2}}{% if location %}\n\n{% if invoice.auction.is_online %}\nYou must meet at {{ location }} to exchange your lots.\n\nSee you there!{% endif %}{% endif %}\n\nhttps://{{domain}}/invoices/{{invoice.no_login_link}}/\n\n{% if invoice.status != "PAID" %}{{ invoice.auction.invoice_payment_instructions | default:""}}{% endif %}\n{% load email_tags %}{% email_footer_text %}\n',
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block header %}{% email_club_header %}{% endblock %}\n{% block content %}\nHey {{ name|first_name|default:"there" }},<br><br>\n\n{{ subject }}.  {% if invoice.status == "PAID" %}Your invoice is paid and nothing more is owed; this is your receipt. {% if invoice.user_should_be_paid %}You were paid{% else %}You paid{% endif %}{% elif invoice.user_should_be_paid %}You will be paid{% else %}You owe a total of{% endif %} ${{ invoice.absolute_amount|floatformat:2}}{% if location %}\n{% if invoice.auction.is_online %}<br><br>\nYou must meet at {{ location }} to exchange your lots.<br><br>\n\nSee you there!{% endif %}{% endif %}<br><br>\n\n{% email_button %}<a href=\'https://{{domain}}/invoices/{{invoice.no_login_link}}/?src=notification\'>View your invoice</a>{% endemail_button %}{% if invoice.status != "PAID" %}{{ invoice.auction.invoice_payment_instructions | default:""}}{% endif %}\n{% endblock %}\n',
    ),
    "join_auction_reminder": (
        "Don't forget to join {{ auction }}",
        "Hey {{ user.first_name|default:\"there\" }},\n\nThanks for checking out {{ auction }}!  Don't forget to join:  Read the rules and click the green button at the bottom of this page:\nhttps://{{ domain }}/auctions/{{auction.slug}}\n\n{% if auction.allow_bidding_on_lots %}Once you join, make sure to bid on any lots you're interested in!{% else %}Don't miss out!{% endif %}\n\n{% for lot in lots %}\n* {{ lot.lot_name }}: https://{{lot.full_lot_link}}\n\n{% endfor %}\n\nGot questions?  Having trouble?  Just reply and we'll help you!\n\nTurn these emails off at https://{{ domain }}/notifications/\n{% load email_tags %}{% email_footer_text %}\n",
        "{% extends \"email/base.html\" %}{% load email_tags %}\n{% block header %}{% email_club_header %}{% endblock %}\n{% block content %}\nHey {{ user.first_name|default:\"there\" }},<br><br>\n\nThanks for checking out {{ auction }}!  Don't forget to join: read the rules and click the green button at the bottom of the page.\n{% email_button %}<a href='https://{{ domain }}/auctions/{{auction.slug}}?src={{uuid}}'>Read the rules and join</a>{% endemail_button %}\n\n{% if auction.allow_bidding_on_lots %}Once you join, make sure to bid on any lots you're interested in!{% else %}Don't miss out!{% endif %}<br><br>\n\n{% for lot in lots %}\n<b>{{ lot.lot_name }}</b><br>\n<a href=\"https://{{lot.full_lot_link}}?src={{uuid}}\">{% if lot.thumbnail %}{% if lot.thumbnail.image %}<img src='https://{{ domain }}{{ lot.thumbnail.image.lot_list.url }}'></img>{% else %}<img src='{{ lot.thumbnail.url }}' style='max-width:250px; max-height:150px; object-fit:cover;'></img>{% endif %}<br>{% endif %}View and bid on this lot</a><br><br>\n\n{% endfor %}\n\nGot questions?  Having trouble?  Just reply and we'll help you!<br><br>\n\n<br><small>Turn these emails off under your <a href='https://{{ domain }}/notifications/'>preferences</a></small>\n{% endblock %}\n",
    ),
    "lot_ended_relist": (
        "Lot ended",
        'Hey {{ lot.user.first_name|default:"there" }},\n\nYour lot, {{ lot.lot_name }}, has ended.  If you want to relist it, click here: https://{{ domain }}/lots/new/?copy={{ lot.lot_number }}\n{% load email_tags %}{% email_footer_text %}\n',
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ lot.user.first_name|default:"there" }},<br>\n<br>\nYour lot, {{ lot.lot_name }}, has ended.  If you want to relist it:\n{% email_button %}<a href=\'https://{{ domain }}/lots/new/?copy={{ lot.lot_number }}\'>Relist this lot</a>{% endemail_button %}\n{% endblock %}\n',
    ),
    "non_auction_lot_seller": (
        "{{ lot.lot_name }} is now sold!",
        'Hey {{ lot.user.first_name|default:"there" }},\n\nYou\'ve sold {{ lot.lot_name }} for ${{lot.winning_price}} to {{ lot.winner.first_name}} {{lot.winner.last_name}}.\n\nReply to this email to contact the winner and coordinate payment and lot exchange.\n{% load email_tags %}{% email_footer_text %}\n',
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ lot.user.first_name|default:"there" }},<br><br>\n\nYou\'ve sold {{ lot.lot_name }} for ${{lot.winning_price}} to {{ lot.winner.first_name}} {{lot.winner.last_name}}<br><br>\n\nReply to this email to contact the winner and coordinate payment and lot exchange.\n{% endblock %}\n',
    ),
    "non_auction_lot_winner": (
        "{{ lot.lot_name }} is now sold!",
        'Hey {{ lot.winner.first_name|default:"there" }},\n\nYou\'ve won {{ lot.lot_name }} for ${{lot.winning_price}} from {{ lot.user.first_name }} {{ lot.user.last_name }}.\n\nReply to this email to contact the seller and coordinate payment and lot exchange.\n{% load email_tags %}{% email_footer_text %}\n',
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ lot.winner.first_name|default:"there" }},<br><br>\n\nYou\'ve won {{ lot.lot_name }} for ${{lot.winning_price}} from {{ lot.user.first_name }} {{ lot.user.last_name }}.<br><br>\n\nReply to this email to contact the seller and coordinate payment and lot exchange.\n{% endblock %}\n',
    ),
    "online_auction_welcome": (
        "Thanks for joining {{tos.auction}}",
        "{% load email_tags %}Hey {{ tos.name|first_name|default:\"there\" }},\n\nThank you for joining {{tos.auction}}!  This is an online auction with in-person lot exchange.\n\n{{ closer_location_warning }}\nSome things to keep in mind:\n* Bidding ends on {{ tos.auction_date_as_localized_string }}.  If last-minute bids are placed on a lot, the end time will be extended: https://{{ domain }}/faq#how-exactly-do-dynamic-endings-work\n* The winning bid is determined by the second highest bidder, so you should bid what an item is worth to you.  You'll only pay $1 more than the second highest bid.\n* If you want to sell lots, you can do so now.\n* Any lots you win will need to be picked up{% if tos.auction.multi_location %} at {{ tos.pickup_location }},{% endif %}{% if not tos.pickup_location.users_must_coordinate_pickup%} on {{ tos.pickup_time_as_localized_string }}{% endif %}.  You can get directions here: {{tos.pickup_location.directions_link}}\n{% if tos.auction.multi_location and tos.second_pickup_time_as_localized_string %}* This is a multi-location auction; you can bid on lots at any location, and the club will coordinate transport between locations.  If you win lots from other locations, you'll need to return on {{tos.second_pickup_time_as_localized_string}} to pick them up.{% endif %}\n\nQuestions?  Just reply and we'll help!\n{% load email_tags %}{% email_footer_text %}\n",
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block header %}{% email_club_header %}{% endblock %}\n{% block content %}\nHey {{ tos.name|first_name|default:"there" }},<br>\n<br>\nThank you for joining {{tos.auction}}!  This is an online auction with in-person lot exchange.<br>\n\n{{ closer_location_warning_html }}<br>\nSome things to keep in mind:<ul>\n<li>Bidding ends on {{ tos.auction_date_as_localized_string }}.  Expect prices to increase -- sometimes dramatically! -- on the last day.  If last-minute bids are placed on a lot, the end time will be extended.  <a href="https://{{ domain }}/faq#how-exactly-do-dynamic-endings-work">More about dynamic endings</a></li>\n<li> The winning bid is determined by the second highest bidder, so you should bid what an item is worth to you.  You\'ll only pay $1 more than the second highest bid.</li>\n<li> If you want to sell lots, you can do so now.  <a href="https://{{domain}}{{tos.auction.add_lot_link}}">Click here to get started.</a></li>\n<li> Any lots you win will need to be picked up{% if tos.auction.multi_location %} at {{ tos.pickup_location }},{% endif %}{% if not tos.pickup_location.users_must_coordinate_pickup%} on {{ tos.pickup_time_as_localized_string }}{% endif %}.  <a href="{{tos.pickup_location.directions_link}}">Get directions</a></li>\n{% if tos.auction.multi_location and tos.second_pickup_time_as_localized_string %}<li> This is a multi-location auction; you can bid on lots at any location, and the club will coordinate transport between locations.  If you win lots from other locations, you\'ll need to return on {{tos.second_pickup_time_as_localized_string}} to pick them up.</li>{% endif %}</ul>\n<br>\n<br>\nQuestions?  Just reply and we\'ll help!\n{% endblock %}\n',
    ),
    "outbid_notification": (
        "You've been outbid!",
        'Hey {{ name|default:"there" }},\n\nYou\'ve been outbid on lot {{ lot.lot_number_display }} - {{ lot.lot_name }}.\n\nBid more here: https://{{ lot.full_lot_link }}\n\nGood luck!\n{% load email_tags %}{% email_footer_text %}\n',
        "{% extends \"email/base.html\" %}{% load email_tags %}\n{% block header %}{% email_club_header %}{% endblock %}\n{% block content %}\nHey {{ name|default:\"there\" }},<br><br>\n\nYou've been outbid on lot {{ lot.lot_number_display }} - <b>{{ lot.lot_name }}</b><br>\n\n{% if lot.thumbnail %}{% if lot.thumbnail.image %}<img src='https://{{ domain }}{{ lot.thumbnail.image.lot_list.url }}'></img>{% else %}<img src='{{ lot.thumbnail.url }}' style='max-width:250px; max-height:150px; object-fit:cover;'></img>{% endif %}<br>{% endif %}\n\n{% email_button %}<a href='https://{{ lot.full_lot_link }}?src=outbid'>Increase your bid</a>{% endemail_button %}\n\nGood luck!\n{% endblock %}\n",
    ),
    "reprint_reminder": (
        "Some of your labels for {{ tos.auction }} need to be reprinted",
        "{% load email_tags %}Hey {{ tos.name|first_name|default:\"there\" }},\n\nSome of your lots have sold with buy now!\n\nTo help get these to the winner, a new label needs to be printed with the winner's name. If you're able to print a new label before the auction, that would be great.  Click here: https://{{domain}}{{tos.auction.label_print_unprinted_link}} (this will only print labels that need to be printed) and place these labels on your sold lot(s).\n\nIf printing isn't possible, please notify the auction staff when you arrive so we can assist.\n\nThank you, and we'll see you at {{ tos.auction }}\n\nQuestions?  Just reply and we'll help!\n{% load email_tags %}{% email_footer_text %}\n",
        "{% extends \"email/base.html\" %}{% load email_tags %}\n{% block header %}{% email_club_header %}{% endblock %}\n{% block content %}\nHey {{ tos.name|first_name|default:\"there\" }},<br><br>\n\nSome of your lots have sold with buy now!<br><br>\n\nTo help get these to the winner, a new label needs to be printed with the winner's name. If you're able to print a new label before the auction, that would be great.  <a href='https://{{domain}}{{tos.auction.label_print_unprinted_link}}'>Click here to print your labels</a> (this will only print labels that need to be printed) and place these labels on your sold lot(s).<br><br>\n\nIf printing isn't possible, please notify the auction staff when you arrive so we can assist.<br><br>\n\nThank you, and we'll see you at {{ tos.auction }}<br><br>\n\nQuestions?  Just reply and we'll help!\n{% endblock %}\n",
    ),
    "unread_chat_messages": (
        "Unread chat messages on {{domain}}",
        'Hey {{ name|default:"there" }},\n\nNew messages at https://{{domain}}/messages/\n{% load email_tags %}{% email_footer_text %}\n',
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ name|default:"there" }},<br><br>\n\n{% if data.my_lot_subscriptions_count and data.email_me_when_people_comment_on_my_lots %}\nPeople have been chatting about your lots.  Take a look and answer any questions that have come up:<br><br>\n{% for sub in data.my_lot_subscriptions %}\n\t<a href="https://{{ sub.lot.full_lot_link }}?src=chat_notification">{{ sub.lot.lot_name }}</a> ({{sub.new_message_count}} new message{% if sub.new_message_count != 1%}s{%endif%})<br><br>\n{% endfor %}\n{% endif %}\n{% if data.other_lot_subscriptions_count and data.email_me_about_new_chat_replies %}\nMessages on lots you\'ve commented on:<br><br>\n{% for sub in data.other_lot_subscriptions %}\n\t<a href="https://{{ sub.lot.full_lot_link }}?src=chat_notification">{{ sub.lot.lot_name }}</a> ({{sub.new_message_count}} new message{% if sub.new_message_count != 1%}s{%endif%})<br><br>\n{% endfor %}\n{% endif %}\nMake sure to sign in -- messages only show up for logged in users.<br><br>\n\n<small><a href="https://{{ domain }}/messages/">Manage messages</a></small>\n{% endblock %}\n',
    ),
    "user_joined_auction_despite_ban": (
        "A user you may have banned in the past has joined {{ tos.auction }}",
        'Hey {{ tos.auction.created_by.first_name|default:"there" }},\n\n{{ tos.name }} joined {{ tos.auction}}.  Their IP address is {{ tos.user.userdata.last_ip_address }}, the same as a user you have banned in the past, {{ tos.trying_to_avoid_ban }}.\n{% load email_tags %}{% email_footer_text %}\n',
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ tos.auction.created_by.first_name|default:"there" }},<br>\n<br>\n{{ tos.name }} joined {{ tos.auction}}.  Their IP address is {{ tos.user.userdata.last_ip_address }}, the same as a user you have banned in the past, {{ tos.trying_to_avoid_ban }}.<br>\n<br>\nYou can <a href="https://{{domain}}{{tos.auction.user_admin_link}}?query={{tos}}">view their contact info here</a>.\n{% endblock %}\n',
    ),
    "watched_items_ending": (
        "Lots you've watched are ending soon",
        'Hey {{ name|default:"there" }},\n\nMake sure to bid on the lots you\'ve watched!\n\n{{ watched_url|safe }}\n{% load email_tags %}{% email_footer_text %}\n',
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ name|default:"there" }},<br><br>\n\nMake sure to bid on the lots you\'ve watched!<br><br>\n\n{% email_button %}<a href="{{ watched_url }}">View your watched lots</a>{% endemail_button %}\n{% endblock %}\n',
    ),
    "weekly_promo_email": (
        "The latest updates from {{ domain }}",
        'Hey {{ name|default:"there" }},\n\nHere a quick summary of new stuff you might be interested in:\n{% if auctions %}\nAuctions near you:\n{% for auction in auctions %}\n{{ auction.title }}\n({{ auction.distance|floatformat:0 }} miles away)\nhttps://{{domain}}/?{{auction.slug}}\n\n{% endfor %}\n{%endif%}\n{% if nearby_lots %}\nLots available for pickup near you:\n{% for lot in nearby_lots %}\n{{ lot.lot_name }}\nhttps://{{ domain }}/lots/{{ lot.lot_number }}/{{ lot.slug }}/\n\n{% endfor %}\n{%endif%}\n{% if shippable_lots %}\nLots available for shipping:\n{% for lot in shippable_lots %}\n{{ lot.lot_name }}\nhttps://{{ domain }}/lots/{{ lot.lot_number }}/{{ lot.slug }}/\n\n{% endfor %}\n{%endif%}\n\nVisit the site here: https://{{ domain }}/\n\nManage your notifications: https://{{ domain }}/notifications/\n{% if special_message %}\n\n{{ special_message }}\n{% endif %}\n{% load email_tags %}{% email_footer_text %}\n',
        "{% extends \"email/base.html\" %}{% load email_tags %}\n{% block content %}\nHey {{ name|default:\"there\" }},<br><br>\n\n{% if special_message %}<br><br>\n{{ special_message }}<br><br>\n{% endif %}\n\nHere a quick summary of new stuff you might be interested in:<br><br>\n{% if auctions %}\n<h3>Auctions near you</h3>\n{% for auction in auctions %}\n<a href='https://{{domain}}/?{{auction.slug}}=&src=weekly_email&uid={{unsubscribe}}'>{{ auction.title }}</a> ({{ auction.distance|floatformat:0 }} miles away)<br><br>\n\n{% endfor %}\n{%endif%}\n{% if nearby_lots %}\n<h3>Lots available for pickup near you</h3>\n{% for lot in nearby_lots %}\n<b>{{ lot.lot_name }}</b><br>\n<a href=\"https://{{ domain }}/lots/{{ lot.lot_number }}/{{ lot.slug }}/?src=weekly_email&uid={{unsubscribe}}\">{% if lot.thumbnail %}{% if lot.thumbnail.image %}<img src='https://{{ domain }}{{ lot.thumbnail.image.lot_list.url }}'></img>{% else %}<img src='{{ lot.thumbnail.url }}' style='max-width:250px; max-height:150px; object-fit:cover;'></img>{% endif %}<br>{% endif %}View and bid on this lot</a><br><br>\n\n{% endfor %}\n{%endif%}\n{% if shippable_lots %}\n<h3>Lots available for shipping</h3>\n{% for lot in shippable_lots %}\n<b>{{ lot.lot_name }}</b><br>\n<a href=\"https://{{ domain }}/lots/{{ lot.lot_number }}/{{ lot.slug }}/?src=weekly_email&uid={{unsubscribe}}\">{% if lot.thumbnail %}{% if lot.thumbnail.image %}<img src='https://{{ domain }}{{ lot.thumbnail.image.lot_list.url }}'></img>{% else %}<img src='{{ lot.thumbnail.url }}' style='max-width:250px; max-height:150px; object-fit:cover;'></img>{% endif %}<br>{% endif %}View and bid on this lot</a><br><br>\n{% endfor %}\n{%endif%}\n\nThere's lots more, too!\n{% email_button %}<a href=\"https://{{ domain }}/?src=weekly_email&uid={{unsubscribe}}\">See everything</a>{% endemail_button %}\n\n<br><small><a href=\"https://{{ domain }}/notifications/\">Manage your notifications</a></small>\n{% endblock %}\n",
    ),
    "wrong_location_selected": (
        "A user may have selected the wrong location in {{ tos.auction }}",
        'Hey {{ tos.auction.created_by.first_name|default:"there" }},\n\n{{ tos.name }} joined {{ tos.auction}}.  They may have selected the wrong pickup location -- {{ tos.closest_location_for_this_user}} is approximately {{tos.closer_location_savings}} miles closer to them, but they\'ve selected {{ tos.pickup_location }} instead.\n{% load email_tags %}{% email_footer_text %}\n',
        '{% extends "email/base.html" %}{% load email_tags %}\n{% block content %}\nHey {{ tos.auction.created_by.first_name|default:"there" }},<br>\n<br>\n{{ tos.name }} joined {{ tos.auction}}.  They may have selected the wrong pickup location -- {{ tos.closest_location_for_this_user}} is approximately {{tos.closer_location_savings}} miles closer to them, but they\'ve selected {{ tos.pickup_location }} instead.<br>\n<br>\nYou can <a href="https://{{domain}}{{tos.auction.user_admin_link}}?query={{tos}}">change their pickup location for them here</a>, but don\'t make changes without talking with them first!<br>\n<br>\nTheir email is {{ tos.email }}\n{% endblock %}\n',
    ),
}


def forwards(apps, schema_editor):
    EmailTemplate = apps.get_model("post_office", "EmailTemplate")
    for name, (subject, content, html_content) in TEMPLATES.items():
        EmailTemplate.objects.update_or_create(
            name=name,
            language="",
            defaults={"subject": subject, "content": content, "html_content": html_content},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0474_lot_sales_recorded"),
        ("post_office", "0011_models_help_text"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
