# Generated by Django 5.2.17 on 2026-10-01 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0476_post_auction_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmember",
            name="membership_carried_by",
            field=models.ForeignKey(
                blank=True,
                help_text="A household or family membership: this member's dates are copied from that member's on every save, and every way to renew or pay dues is closed to this member. One level deep.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carried_memberships",
                to="auctions.clubmember",
                verbose_name="Membership carried with",
            ),
        ),
    ]
