# Generated by Django 5.2.17 on 2026-10-01 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import auctions.documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0478_welcome_letter_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchPage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=auctions.documents.models.document_storage,
                        upload_to=auctions.documents.models.document_upload_to,
                    ),
                ),
                ("pdf_page", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=auctions.documents.models.document_storage,
                        upload_to=auctions.documents.models.document_upload_to,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("read", models.BooleanField(db_index=True, default=False)),
                ("text", models.TextField(blank=True)),
                ("read_with", models.CharField(blank=True, max_length=100)),
                ("assignments", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Everyone on the site"),
                            ("club", "Members of its club"),
                            ("private", "Only me"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("year", models.PositiveSmallIntegerField(blank=True, help_text="Year it was written", null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=auctions.documents.models.document_storage,
                        upload_to=auctions.documents.models.document_upload_to,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting to be read"),
                            ("processing", "Being read"),
                            ("ready", "Ready"),
                            ("failed", "Couldn't be read"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True, help_text="What reading the file left out, said plainly.")),
                ("text", models.TextField(blank=True, help_text="Markdown read out of the file.")),
                (
                    "text_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Somebody corrected the text by hand, so re-indexing never re-reads the file.",
                    ),
                ),
                ("parser_version", models.CharField(blank=True, max_length=40)),
                ("chunker_version", models.CharField(blank=True, max_length=20)),
                (
                    "read_with",
                    models.CharField(blank=True, help_text="The model that read its pictures, if any.", max_length=100),
                ),
                ("auto_fields", models.JSONField(blank=True, default=list)),
                ("described_with", models.CharField(blank=True, max_length=100)),
                ("topics", models.JSONField(blank=True, default=list)),
                (
                    "removed",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden from everyone, e.g. after a copyright notice. The file is kept.",
                    ),
                ),
                ("removed_reason", models.CharField(blank=True, max_length=300)),
                ("createdon", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("indexed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Times the reader died on this without finishing; three and it has failed."
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="auctions.club",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("pages", models.ManyToManyField(blank=True, related_name="documents", to="auctions.batchpage")),
                ("species", models.ManyToManyField(blank=True, related_name="documents", to="auctions.species")),
            ],
        ),
        migrations.AddField(
            model_name="copyrightnotice",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="The library document the material was, when it could be worked out from the URLs given. Taking it down is ticking Removed on the document.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copyright_notices",
                to="auctions.document",
            ),
        ),
        migrations.CreateModel(
            name="DocumentBatch",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Everyone on the site"),
                            ("club", "Members of its club"),
                            ("private", "Only me"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for more pages"),
                            ("reading", "Reading the pages"),
                            ("stitching", "Putting the articles together"),
                            ("done", "Done"),
                            ("failed", "Couldn't be finished"),
                        ],
                        db_index=True,
                        default="reading",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("stitched_through", models.PositiveIntegerField(default=0)),
                ("articles", models.JSONField(blank=True, default=dict)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_batches",
                        to="auctions.club",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="auctions.documentbatch",
            ),
        ),
        migrations.AddField(
            model_name="batchpage",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="auctions.documentbatch"
            ),
        ),
        migrations.CreateModel(
            name="DocumentFeedback",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unreadable", "The text is garbled or missing"),
                            ("species", "Wrong species"),
                            ("topics", "Wrong topics"),
                            ("details", "Wrong title, author or year"),
                            ("duplicate", "A duplicate of another document"),
                            ("offensive", "Offensive, or doesn't belong here"),
                            ("other", "Something else"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=2000)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="feedback", to="auctions.document"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField()),
                ("heading", models.CharField(blank=True, max_length=500)),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                ("text", models.TextField()),
                ("start", models.PositiveIntegerField(default=0)),
                ("end", models.PositiveIntegerField(default=0)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("embedding", models.BinaryField(blank=True, null=True)),
                ("embedding_model", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="auctions.document"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["document", "position"], name="docchunk_doc_position")],
            },
        ),
        migrations.CreateModel(
            name="DocumentImageText",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sha256", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=100)),
                ("text", models.TextField(blank=True)),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="image_texts", to="auctions.document"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "sha256", "model"), name="one_reading_per_picture_model"
                    )
                ],
            },
        ),
    ]
