# Generated by Django 5.2.17 on 2026-10-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0479_library"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_sent_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the invoice email or push actually went. Unset before 2026-10-02.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="opened_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the emailed link was first opened. Unset on invoices opened before 2026-10-02.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AbandonedBid",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("typed", "Typed an amount and left"),
                            ("blocked", "Pressed Place bid and was told they can't bid"),
                            ("confirm", "Opened the confirmation and cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True)),
                ("updatedon", models.DateTimeField(auto_now=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="abandoned_bids", to="auctions.lot"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("lot", "user"), name="abandoned_bid_one_per_lot")],
            },
        ),
    ]
