# Generated by Django 5.2.17 on 2026-10-04 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0481_post_auction_survey_checkbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="merge_into_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Another account this user asked to be merged into. That account finishes it; see auctions.account_merge.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="merge_requested_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
