# Generated by Django 5.2.17 on 2026-10-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0482_userdata_merge_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicegrammar",
            name="cloud_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Off"),
                    ("gpt-live-transcribe", "gpt-live-transcribe (about $1 an hour)"),
                    ("gpt-4o-transcribe", "gpt-4o-transcribe (about 36c an hour, waits for pauses)"),
                    ("gpt-4o-mini-transcribe", "gpt-4o-mini-transcribe (about 18c an hour, waits for pauses)"),
                ],
                default="gpt-live-transcribe",
                help_text="Listen through OpenAI in a web browser (a laptop at the auction, or a phone's browser). Charged to this site's OpenAI key per minute of listening. Off leaves only the app.",
                max_length=40,
            ),
        ),
    ]
