# Generated by Django 5.2.17 on 2026-10-06 01:02

from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0483_voicegrammar_cloud_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="library_enabled",
            field=models.BooleanField(
                default=auctions.models.get_default_library_enabled,
                help_text="Show this user /library/ and the library's tools on /mcp/.",
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="voice_cloud_enabled",
            field=models.BooleanField(
                default=auctions.models.get_default_voice_cloud_enabled,
                help_text="Let this user's web browser listen through OpenAI on Set lot winners (Voice grammar's cloud model, on this site's key). The app listens without it.",
                verbose_name="Listen through OpenAI",
            ),
        ),
    ]
