# Generated by Django 5.2.17 on 2026-10-06 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0484_userdata_library_voice_cloud_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speciessearchcache",
            name="accepts",
        ),
        migrations.RemoveField(
            model_name="speciessearchcache",
            name="rejects",
        ),
        migrations.CreateModel(
            name="SpeciesNameVote",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "search_text",
                    models.CharField(
                        help_text="The lot's name, normalised the way SpeciesSearchCache keys it.", max_length=120
                    ),
                ),
                ("agrees", models.BooleanField()),
                ("updatedon", models.DateTimeField(auto_now=True)),
                (
                    "chosen",
                    models.ForeignKey(
                        blank=True,
                        help_text="What the lot carried instead, when it disagreed.  Blank for a lot it was taken off.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="auctions.species",
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="species_name_vote", to="auctions.lot"
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        help_text='The answer the lot was offered.  Blank for a remembered "not a species".',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_votes",
                        to="auctions.species",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Whose save decided it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["search_text", "species"], name="auctions_sp_search__9249c4_idx")],
            },
        ),
    ]
