# Generated by Django 5.2.17 on 2026-10-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0485_species_name_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctiontos",
            name="paddle_printed_name",
            field=models.CharField(blank=True, default="", max_length=181),
        ),
        migrations.AddField(
            model_name="auctiontos",
            name="paddle_printed_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
