# Generated by Django 5.2.17 on 2026-10-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0487_seed_command_palette_paddles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donationemail",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("own_email", "Email, in your own mailbox"),
                    ("webform", "Their donation request form"),
                    ("phone", "Phone"),
                    ("in_person", "In person"),
                ],
                db_index=True,
                default="email",
                help_text="How this contact happened. Only email this site sent or wrote counts against the daily email allowance.",
                max_length=20,
            ),
        ),
    ]
