# Generated by Django 5.2.17 on 2026-10-07 12:15

from django.db import migrations, models

import auctions.models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0488_donationemail_own_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="voice_cloud_enabled",
            field=models.BooleanField(
                default=auctions.models.get_default_voice_cloud_enabled,
                help_text="Let this user listen through OpenAI on Set lot winners, in a web browser or in the app (Voice grammar's cloud model, on this site's key). The app's own recognizer needs neither.",
                verbose_name="Listen through OpenAI",
            ),
        ),
        migrations.AlterField(
            model_name="voicegrammar",
            name="cloud_model",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Off"),
                    ("gpt-live-transcribe", "gpt-live-transcribe (about $1 an hour)"),
                    ("gpt-4o-transcribe", "gpt-4o-transcribe (about 36c an hour, waits for pauses)"),
                    ("gpt-4o-mini-transcribe", "gpt-4o-mini-transcribe (about 18c an hour, waits for pauses)"),
                ],
                default="gpt-live-transcribe",
                help_text="Listen through OpenAI, in a web browser (a laptop at the auction, or a phone's browser) or in the app. Charged to this site's OpenAI key per minute of listening. Off leaves only the app's own recognizer, which needs neither this nor the account setting.",
                max_length=40,
            ),
        ),
    ]
