# Generated by Django 5.2.17 on 2026-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0489_voice_cloud_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Shown at the top of your club page: when you meet, and why somebody should come.",
                verbose_name="About this club",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="donation_context",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Passed to the language model with every donation email it writes, so it doesn't have to be retyped for each vendor. For example: “We're a non-profit club of 120 members. Our spring auction raises money for our speaker program.”",
                verbose_name="Club information for donation emails",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="donation_email_mode",
            field=models.CharField(
                choices=[("routed", "Send mail from this site"), ("copy", "Copy/paste to my email")],
                default="routed",
                help_text="From this site, the email comes from an address that files the vendor's reply against them. With copy/paste, you send it from your own email and record replies yourself, by hand or with an AI assistant.",
                max_length=20,
                verbose_name="How to send donation emails",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="donation_followup_days",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1 day"), (3, "3 days"), (7, "1 week"), (14, "2 weeks"), (30, "1 month")],
                default=7,
                help_text="How long to wait for a reply before a vendor shows up as due for a follow-up. A week is about right.",
                verbose_name="Follow up after",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Where you meet. Search Google maps with this address, then drag the pin. This is how the club finder knows where you are.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="min_quantity",
            field=models.IntegerField(
                default=5,
                help_text="Minimum quantity in a lot to be eligible for BAP points. Stops one fry in a bag earning points. Plants, snails and live food are exempt.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="only_donation_lots",
            field=models.BooleanField(
                default=False,
                help_text="Require all BAP lots to be a donation. For clubs whose program is “breed it and donate it to the auction”.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="only_sold_lots",
            field=models.BooleanField(
                default=False,
                help_text="Require lots to be sold for points to be awarded. Uncheck to give points for submitted and unsold lots. With Auto add points on, unsold lots get theirs a day after the auction ends.",
                verbose_name="Only sold lots",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="points_for_custom_checkbox",
            field=models.IntegerField(
                default=0,
                help_text="Bonus BAP points awarded when the custom checkbox is checked on a lot. Leave at 0 to disable. For example, call the checkbox “CARES species” and give it 5.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="send_membership_renewal_confirmation",
            field=models.BooleanField(
                default=False,
                help_text="A receipt with the new date, sent whenever somebody renews, however they paid.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="send_welcome_email_to_new_members",
            field=models.BooleanField(
                default=False,
                help_text="Sent when somebody joins or you add them, with a link to their membership, and their card if you use barcodes.",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="separate_cap",
            field=models.BooleanField(
                default=False,
                help_text="Live food cultures, snails and other inverts earn CAP (Culture Award Program) points instead of BAP. Without this, live food earns nothing.",
                verbose_name="Separate Live Food Culture Award Program (CAP)",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="separate_hap",
            field=models.BooleanField(
                default=False,
                help_text="Plants earn HAP (Horticultural Award Program) points, with their own leaderboard, instead of BAP.",
                verbose_name="Separate Horticultural Award Program (HAP)",
            ),
        ),
    ]
