# Generated by Django 5.2.17 on 2026-10-08 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0490_club_setting_help_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assistantskillrequest",
            options={"ordering": ["-createdon"], "verbose_name": "Feature request"},
        ),
        migrations.CreateModel(
            name="AgentProposal",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.CharField(max_length=200)),
                (
                    "reason",
                    models.TextField(
                        blank=True, default="", help_text="Why the agent wants it, and what it read that says so."
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text='Tool calls to run in order: [{"tool": ..., "arguments": {...}}].'
                    ),
                ),
                (
                    "results",
                    models.JSONField(blank=True, default=list, help_text="What each step answered when it ran."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for you"),
                            ("applied", "Done"),
                            ("failed", "Stopped on an error"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which assistant proposed it: the OAuth application's name or the API key's.",
                        max_length=100,
                    ),
                ),
                ("decided_on", models.DateTimeField(blank=True, null=True)),
                ("createdon", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_proposals_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-createdon"],
            },
        ),
    ]
