# Generated by Django 5.2.17 on 2026-10-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0491_agent_proposals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="days_between_same_species_lots",
            field=models.IntegerField(
                default=0,
                help_text="Like the rule above, but by scientific name; 0 allows points every time.",
                verbose_name="Days between same species lots",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="donation_context",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Used in every donation email we write, e.g. “120 members; the spring auction pays for speakers.”",
                verbose_name="Club information for donation emails",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="donation_email_mode",
            field=models.CharField(
                choices=[("routed", "Send mail from this site"), ("copy", "Copy/paste to my email")],
                default="routed",
                help_text="From this site, replies are recorded for you; with copy/paste, you record them yourself.",
                max_length=20,
                verbose_name="How to send donation emails",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="send_membership_expiration_reminders",
            field=models.BooleanField(
                default=False,
                help_text="Emails members who have paid before a link to renew here; members may not expect it from this site.",
            ),
        ),
        migrations.AlterField(
            model_name="userapikey",
            name="allow_writes",
            field=models.BooleanField(
                default=False, help_text="Lets this key add and change lots, check-ins, invoices and members."
            ),
        ),
    ]
