# Generated by Django 5.2.17 on 2026-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0492_help_text_trim"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantskillrequest",
            name="target",
            field=models.CharField(
                choices=[("site", "Site"), ("app", "App"), ("both", "Site and app")],
                default="site",
                help_text="Which repository the build changes: this site, the mobile app, or both.",
                max_length=10,
            ),
        ),
    ]
