# Generated by Django 5.2.17 on 2026-10-09 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0493_feature_request_target"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppCrash",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Same bug, same fingerprint: the kind, the error's type and its top frames.",
                        max_length=40,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("dart", "Dart error"), ("native", "Native crash"), ("anr", "Not responding")],
                        max_length=10,
                    ),
                ),
                ("platform", models.CharField(choices=[("android", "Android"), ("ios", "iOS")], max_length=10)),
                (
                    "fatal",
                    models.BooleanField(
                        default=True,
                        help_text="False for an error the app survived, such as one inside a button handler.",
                    ),
                ),
                ("app_version", models.CharField(blank=True, default="", max_length=40)),
                ("os_version", models.CharField(blank=True, default="", max_length=100)),
                ("device", models.CharField(blank=True, default="", max_length=100)),
                ("message", models.TextField(blank=True, default="")),
                ("stack", models.TextField(blank=True, default="")),
                (
                    "occurred_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the phone says it happened; a native crash arrives on the next launch.",
                        null=True,
                    ),
                ),
                ("createdon", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-createdon"],
            },
        ),
    ]
