# Generated by Django 5.2.17 on 2026-10-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0494_app_crash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmusage",
            name="destination",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="For a navigation, the palette_routes key it landed on. This is what palette_shortcut_candidates on /mcp/admin/ reads: a query that resolves to the same destination every time never needs to be asked about again.",
                max_length=100,
            ),
        ),
    ]
