name: Docker images build and test
on:
  push:
  pull_request:
    branches: [master]

jobs:
  image-build:
    name: Test Images Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/scripts/prepare-ci.sh
      - run: docker compose build
      - run: docker compose up --detach --wait --wait-timeout 60
      - run: docker compose exec web python3 manage.py test --parallel=1
      - run: docker compose down
