name: Docker images build and test
on:
  push:
  pull_request:
    branches: [master]

jobs:
  image-build:
    name: Test Images Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add swap space
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - run: ./.github/scripts/prepare-ci.sh
      - run: docker compose build
      - run: docker compose up --detach --wait --wait-timeout 60

      - run: docker compose exec web python3 manage.py test --parallel=1

      - if: failure()
        run: docker compose logs web

      - run: docker compose down
